ppm-java: TConnection Class Reference
TConnection Class Reference
A connection between two endpoints.
Public Member Functions
VAudioPort_Output Get_FromPort ()
VAudioPort_Input Get_ToPort ()
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static void CreateInstance (String idFromPort, String idToPort)
Creates a connection from endpoint idFromPort to endpoint idToPort.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Private Member Functions
TConnection (VAudioPort_Output fromPort, VAudioPort_Input toPort)
cTor.
Static Private Member Functions
static String _GetID ()
Private Attributes
VAudioPort_Output fSource
The Source port.
VAudioPort_Input fTarget
The target port.
Static Private Attributes
static int gCounter = -1
Counter to achieve unique ID of this connection.
Detailed Description
A connection between two endpoints.
This object just ensures that the connection is browseable. It won't handle any data flow.
Author
Peter Hoppe
Definition at line 28 of file TConnection.java.
Constructor & Destructor Documentation
TConnection (VAudioPort_Output fromPort, VAudioPort_Input toPort) private
cTor.
Caches fromPort and toPort, so we won't need to query those from the global registry.
Parameters
fromPort Source port
toPort Target port
Definition at line 84 of file TConnection.java.
References TConnection._GetID(), TConnection.fSource, and TConnection.fTarget.
Referenced by TConnection.CreateInstance().
     {
         super (TConnection._GetID ());
         fSource     = fromPort;
         fTarget     = toPort;
     }
Member Function Documentation
static String _GetID () static private
Returns
Creates the unique ID as which we register this connection.
Definition at line 56 of file TConnection.java.
References TConnection.gCounter.
Referenced by TConnection.TConnection().
     {
         String ret;
         gCounter++;
         ret = TConnection.class.getCanonicalName () + "_" + gCounter;
         return ret;
     }
void _Register () protected
Definition at line 112 of file TConnection.java.
     {
         TController.Register (this);
     }
static void CreateInstance (String idFromPort, String idToPort) static
Creates a connection from endpoint idFromPort to endpoint idToPort.
Parameters
idFromPort Unique ID, source port.
idToPort Unique ID, target port.
Definition at line 37 of file TConnection.java.
References TController.GetObject(), and TConnection.TConnection().
     {
         VAudioPort_Output   fromPort;
         VAudioPort_Input    toPort;
         fromPort        = (VAudioPort_Output) TController.GetObject (idFromPort);
         toPort          = (VAudioPort_Input)  TController.GetObject (idToPort);
         fromPort.SetTarget (toPort);
         new TConnection (fromPort, toPort);
     }
VAudioPort_Output Get_FromPort ()
Returns
The source port.
Definition at line 95 of file TConnection.java.
References TConnection.fSource.
     {
         return fSource;
     }
VAudioPort_Input Get_ToPort ()
Returns
The target port.
Definition at line 103 of file TConnection.java.
References TConnection.fTarget.
     {
         return fTarget;
     }
Member Data Documentation
VAudioPort_Output fSource private
The Source port.
Definition at line 69 of file TConnection.java.
Referenced by TConnection.Get_FromPort(), and TConnection.TConnection().
VAudioPort_Input fTarget private
The target port.
Definition at line 75 of file TConnection.java.
Referenced by TConnection.Get_ToPort(), and TConnection.TConnection().
int gCounter = -1 static private
Counter to achieve unique ID of this connection.
Definition at line 51 of file TConnection.java.
Referenced by TConnection._GetID().
The documentation for this class was generated from the following file:
TConnection.java