ppm-java: TAudioContext_JackD_Stats Class Reference
TAudioContext_JackD_Stats Class Reference
Runtime statistics for a TAudioContext_JackD.
Public Member Functions
TAudioContext_JackD_Stats (TAudioContext_JackD host)
cTor.
String GetDumpStr ()
Private Attributes
TAudioContext_JackD fHost
The hosting module.
Detailed Description
Runtime statistics for a TAudioContext_JackD.
Author
Peter Hoppe
Definition at line 26 of file TAudioContext_JackD_Stats.java.
Constructor & Destructor Documentation
TAudioContext_JackD_Stats (TAudioContext_JackD host)
cTor.
Parameters
host The hosting module.
Definition at line 38 of file TAudioContext_JackD_Stats.java.
References TAudioContext_JackD_Stats.fHost.
     {
         fHost = host;
     }
Member Function Documentation
String GetDumpStr ()
Returns
The current runtime statistics as text dump.
Implements IStats.
Definition at line 47 of file TAudioContext_JackD_Stats.java.
References TAudioContext_JackD_Stats.fHost, VAudioProcessor.GetPortIn(), VAudioProcessor.GetPortOut(), and TAudioContext_JackD.IsWorking().
     {
         int                             i;
         int                             n;
         String                          id;
         TAudioContext_Endpoint_In       ip;
         TAudioContext_Endpoint_Out      op;
         TAtomicBuffer_Stats             s;
         String                          ret;
         /* First dump line */
         id      = fHost.GetID ();
         ret     = "JackD_driver ["      + id +
                   "]: sampleRate="      + fHost.GetSampleRate () +
                   ", isWorking="        + fHost.IsWorking () +
                   "\n";
         /* Add one line of statistics per input port. */
         n = fHost.GetNumPortsIn ();
         if (n >= 1)
         {
             ret += "    Inputs:\n";
             for (i = 0; i < n; i++)
             {
                 ip          = (TAudioContext_Endpoint_In) fHost.GetPortIn (i);
                 s           = ip.StatsGet ();
                 id          = ip.GetID ();
                 ret        += "        i/p [" + id              +
                               "]: "           + s.GetDumpStr () +
                               "\n";
             }
         }
         else
         {
             ret += "    Inputs: None\n";
         }
         /* Add one line of statistics per output port. [100] */
         n = fHost.GetNumPortsOut ();
         if (n >= 1)
         {
             ret += "    Outputs:\n";
             for (i = 0; i < n; i++)
             {
                 op          = (TAudioContext_Endpoint_Out) fHost.GetPortOut (i);
                 id          = op.GetID ();
                 ret        += "        o/p [" + id + "]\n";
             }
         }
         else
         {
             ret += "    Outputs: None\n";
         }
         return ret;
     }
Member Data Documentation
TAudioContext_JackD fHost private
The hosting module.
Definition at line 31 of file TAudioContext_JackD_Stats.java.
Referenced by TAudioContext_JackD_Stats.GetDumpStr(), and TAudioContext_JackD_Stats.TAudioContext_JackD_Stats().
The documentation for this class was generated from the following file:
TAudioContext_JackD_Stats.java