ppm-java: TNodeConverterDb Class Reference
TNodeConverterDb Class Reference
Converts a raw value [0, 1] into its equivalent dB value.
Public Member Functions
void CreatePort_In (String id)
void CreatePort_Out (String id)
IStats StatsGet ()
Public Member Functions inherited from VAudioProcessor
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
abstract void CreatePort_In (String id)
Creates an input port.
abstract void CreatePort_Out (String id)
Creates an output port.
int GetNumPortsIn ()
int GetNumPortsOut ()
VAudioPort GetPortIn (int i)
Returns the ith input port.
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static void CreateInstance (String id)
Creates a new instance of this module.
Static Public Attributes
static final double gkMinDB = -130
Minimum dB level.
static final double gkMinThreshold = 3.16E-08f
Voltage (= raw value) corresponding to gkMinDB.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VAudioProcessor
void AddPortIn (VAudioPort_Input p)
Adds a new input port.
void AddPortOut (VAudioPort_Output p)
Adds a new output port.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Package Functions
void Receive (float sample)
Receives a sample value from the associated endpoint and converts it to its equivalent value in dB.
Private Member Functions
TNodeConverterDb (String id)
cTor.
Private Attributes
TNodeConverterDb_Stats fStats
The statistics record.
Detailed Description
Converts a raw value [0, 1] into its equivalent dB value.
We use the following conversion scheme:
Raw values Values (dB)
< 10-7.5 -130
10-7.5 .. 1 -130 .. 0
Author
Peter Hoppe
Definition at line 43 of file TNodeConverterDb.java.
Constructor & Destructor Documentation
TNodeConverterDb (String id) private
cTor.
Parameters
id Unique ID as which we register this module.
Definition at line 76 of file TNodeConverterDb.java.
References TNodeConverterDb.fStats.
Referenced by TNodeConverterDb.CreateInstance().
     {
         super (id, 1, 1);
         fStats = new TNodeConverterDb_Stats (this);
         TController.StatAddProvider (this);
     }
Member Function Documentation
void _Register () protected
Definition at line 121 of file TNodeConverterDb.java.
     {
         TController.Register (this);
     }
static void CreateInstance (String id) static
Creates a new instance of this module.
Parameters
id Unique ID as which we register this module.
Definition at line 61 of file TNodeConverterDb.java.
References TNodeConverterDb.TNodeConverterDb().
     {
         new TNodeConverterDb (id);
     }
void CreatePort_In (String id)
Definition at line 87 of file TNodeConverterDb.java.
References VAudioProcessor.AddPortIn().
     {
         TNodeConverterDb_Endpoint_In p;
         p = new TNodeConverterDb_Endpoint_In (id, this);
         AddPortIn (p);
     }
void CreatePort_Out (String id)
Definition at line 99 of file TNodeConverterDb.java.
References VAudioProcessor.AddPortOut().
     {
         TNodeConverterDb_Endpoint_Out       p;
         p = new TNodeConverterDb_Endpoint_Out (id, this);
         AddPortOut (p);
     }
void Receive (float sample) package
Receives a sample value from the associated endpoint and converts it to its equivalent value in dB.
Parameters
sample The sample value.
Definition at line 132 of file TNodeConverterDb.java.
References VAudioProcessor.GetPortOut(), TNodeConverterDb.gkMinDB, and TNodeConverterDb.gkMinThreshold.
     {
         double                          x;
         float                           dB;
         TNodeConverterDb_Endpoint_Out   out;
         if (sample >= gkMinThreshold)                                   /* Re calculations: [100] */
         {
             x = 20 * Math.log10 (sample);
         }
         else
         {
             x = gkMinDB;
         }
         dB  = (float) x;                                                /* [110] */
         fStats.SetValue (sample);
         fStats.SetDB    (dB);
         out = (TNodeConverterDb_Endpoint_Out) GetPortOut (0);
         out.PushSample (dB);
     }
IStats StatsGet ()
Returns
The current runtime statistics.
Implements IStatEnabled.
Definition at line 112 of file TNodeConverterDb.java.
References TNodeConverterDb.fStats.
     {
         return fStats;
     }
Member Data Documentation
TNodeConverterDb_Stats fStats private
The statistics record.
Updated during runtime.
Definition at line 69 of file TNodeConverterDb.java.
Referenced by TNodeConverterDb.StatsGet(), and TNodeConverterDb.TNodeConverterDb().
final double gkMinDB = -130 static
Minimum dB level.
Maps to PPM 0 .. PPM 1
Definition at line 48 of file TNodeConverterDb.java.
Referenced by TNodeConverterDb.Receive().
final double gkMinThreshold = 3.16E-08f static
Voltage (= raw value) corresponding to gkMinDB.
See [100] in the java source.
Definition at line 54 of file TNodeConverterDb.java.
Referenced by TNodeConverterDb.Receive().
The documentation for this class was generated from the following file:
TNodeConverterDb.java