ppm-java: VAudioPort_Output_Samples Class Reference
VAudioPort_Output_Samples Class Reference abstract
Base class for an output that sends single sample values.
Public Member Functions
VAudioPort_Output_Samples (String id, VAudioProcessor host)
cTor.
void PushSample (float sample)
Pushes a sample value out to the connected input.
Public Member Functions inherited from VAudioPort_Output
VAudioPort_Output (String id, VAudioProcessor host)
cTor.
void SetTarget (VAudioPort_Input target)
Connects this port to an input port.
Public Member Functions inherited from VAudioPort
VAudioPort (String id, VAudioProcessor host)
cTor.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Protected Member Functions
final String _GetType ()
final void _Visit (VAudioPort_Input_Chunks_Buffered target)
final void _Visit (VAudioPort_Input_Chunks_Unbuffered target)
final void _Visit (VAudioPort_Input_Samples target)
Protected Member Functions inherited from VAudioPort_Output
VAudioPort_Input _GetTarget ()
final void _SetTarget (VAudioPort_Input target)
Worker method to establish a connection to an input port, called by the _Visit(...) method of the runtime chose subtype.
final void _SetTarget_Log (VAudioPort_Input target, boolean isErr)
Logs a message when a connection to a VAudioPort_Input is made.
abstract void _Visit (VAudioPort_Input_Chunks_Buffered target)
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Chunks_Buffered.
abstract void _Visit (VAudioPort_Input_Chunks_Unbuffered target)
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Chunks_Unbuffered.
abstract void _Visit (VAudioPort_Input_Samples target)
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Samples.
Protected Member Functions inherited from VAudioPort
VAudioProcessor _GetHost ()
abstract String _GetType ()
Returns textual information of a concrete child's direct super type.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Detailed Description
Base class for an output that sends single sample values.
Author
Peter Hoppe
Definition at line 24 of file VAudioPort_Output_Samples.java.
Constructor & Destructor Documentation
VAudioPort_Output_Samples (String id, VAudioProcessor host)
cTor.
Parameters
id Unique ID as which we register this port.
host The audio processor hosting this port.
Definition at line 32 of file VAudioPort_Output_Samples.java.
     {
         super (id, host);
     }
Member Function Documentation
final String _GetType () protected
Definition at line 54 of file VAudioPort_Output_Samples.java.
     {
         return "VAudioPort_Output_Samples";
     }
final void _Visit (VAudioPort_Input_Chunks_Buffered target) protected
Definition at line 59 of file VAudioPort_Output_Samples.java.
References VAudioPort_Output._SetTarget_Log().
     {
         _SetTarget_Log (target, true);
     }
final void _Visit (VAudioPort_Input_Chunks_Unbuffered target) protected
Definition at line 64 of file VAudioPort_Output_Samples.java.
References VAudioPort_Output._SetTarget_Log().
     {
         _SetTarget_Log (target, true);
     }
final void _Visit (VAudioPort_Input_Samples target) protected
Definition at line 69 of file VAudioPort_Output_Samples.java.
References VAudioPort_Output._SetTarget().
     {
         _SetTarget (target);
     }
void PushSample (float sample)
Pushes a sample value out to the connected input.
Parameters
sample The sample value to send.
Definition at line 42 of file VAudioPort_Output_Samples.java.
References VAudioPort_Output._GetTarget().
     {
         VAudioPort_Input_Samples target;
         target = (VAudioPort_Input_Samples) _GetTarget ();
         target.ReceiveSample (sample);
     }
The documentation for this class was generated from the following file:
VAudioPort_Output_Samples.java