ppm-java: TBroker Class Reference
TBroker Class Reference
Receives events and sends them to subscribed clients.
Public Member Functions
TBroker ()
cTor.
void Broker (int e, String idSource)
Broker an event with no in-band parameter.
void Broker (int e, int arg0, String idSource)
Broker an event with one in-band parameter (int).
void Broker (int e, long arg0, String idSource)
Broker an event with one in-band parameter (long).
void Broker (int e, String arg0, String idSource)
Broker an event with one in-band parameter (String).
void Subscribe (VBrowseable subscribed, IEvented subscriber)
Subscribes an IEvented object (subscriber) to receive events from another VBrowseable (subscribed).
Private Member Functions
void _Broker (int e, String idSource, int argsType, int arg_0_0, long arg_0_1, String arg_1_0)
Internal broker worker method.
Private Attributes
TAtomicArrayMap
< TBrokerSubscriptionList > fSubscriptions
Complete list of subscriptions used in this session.
Static Private Attributes
static final int gkArgsNone = 0
Internal flag: No in-band parameter.
static final int gkArgsOneInt = 10
Internal flag: One in-band parameter of type int.
static final int gkArgsOneLong = 20
Internal flag: One in-band parameter of type long.
static final int gkArgsOneString = 30
Internal flag: One in-band parameter of type String.
Detailed Description
Receives events and sends them to subscribed clients.
This is the backbone of the runtime control messaging system connecting the various modules.
We identify an event by a plain vanilla integer constant. Java texbook approach would dictate using an enumerator or a dedicated class hierarchy for events. We deviate from the textbook approach, because both approaches involve creating objects. That's fine for the occasional event. However, for a constant stream of events (such as generated by the TTimer class) this results in ongoing creation of throw-away objects many times per second. This smells like a silly design. Therefore we resort to the out-of-date technique of using integer constants. This is much more performant.
Author
Peter Hoppe
See Also
IEvented
Definition at line 39 of file TBroker.java.
Constructor & Destructor Documentation
TBroker ()
cTor.
Definition at line 69 of file TBroker.java.
References TBroker.fSubscriptions.
     {
         fSubscriptions = new TAtomicArrayMap<> ();
     }
Member Function Documentation
void _Broker (int e, String idSource, int argsType, int arg_0_0, long arg_0_1, String arg_1_0) private
Internal broker worker method.
Parameters
e The event being brokered.
idSource ID of the module that has fired the event.
argsType Which type is the in-band parameter (none, int, long, String)?
arg_0_0 If in-band parameter is an int: Its value.
arg_0_1 If in-band parameter is a long: Its value.
arg_1_0 If in-band parameter is a String: Its value.
Definition at line 134 of file TBroker.java.
References TBrokerSubscription.GetSubscriber(), TBroker.gkArgsNone, TBroker.gkArgsOneInt, TBroker.gkArgsOneLong, and TBroker.gkArgsOneString.
Referenced by TBroker.Broker().
     {
         TBrokerSubscription     subscr;
         TBrokerSubscriptionList subscrList;
         int                     i;
         int                     n;
         IEvented                receiver;
         subscrList  = fSubscriptions.Get (idSource);
         n           = subscrList.GetNumElements ();
         if (n >= 1)
         {
             for (i = 0; i < n; i++)
             {
                 subscr      = subscrList.Get (i);
                 receiver    = (IEvented) subscr.GetSubscriber ();
                 if (argsType == gkArgsNone)                             /* [100] */
                 {
                     receiver.OnEvent (e);
                 }
                 else if (argsType == gkArgsOneInt)
                 {
                     receiver.OnEvent (e, arg_0_0);
                 }
                 else if (argsType == gkArgsOneLong)
                 {
                     receiver.OnEvent (e, arg_0_1);
                 }
                 else if (argsType == gkArgsOneString)
                 {
                     receiver.OnEvent (e, arg_1_0);
                 }
             }
         }
     }
void Broker (int e, String idSource)
Broker an event with no in-band parameter.
Parameters
e The event being brokered.
idSource ID of the module that has fired the event.
Definition at line 80 of file TBroker.java.
References TBroker._Broker(), and TBroker.gkArgsNone.
     {
         _Broker (e, idSource, gkArgsNone, 0, 0, null);
     }
void Broker (int e, int arg0, String idSource)
Broker an event with one in-band parameter (int).
The parameter carries extra information needed by the recipient.
Parameters
e The event being brokered.
arg0 The in-band parameter.
idSource ID of the module that has fired the event.
Definition at line 93 of file TBroker.java.
References TBroker._Broker(), and TBroker.gkArgsOneInt.
     {
         _Broker (e, idSource, gkArgsOneInt, arg0, 0, null);
     }
void Broker (int e, long arg0, String idSource)
Broker an event with one in-band parameter (long).
The parameter carries extra information needed by the recipient.
Parameters
e The event being brokered.
arg0 The in-band parameter.
idSource ID of the module that has fired the event.
Definition at line 106 of file TBroker.java.
References TBroker._Broker(), and TBroker.gkArgsOneLong.
     {
         _Broker (e, idSource, gkArgsOneLong, 0, arg0, null);
     }
void Broker (int e, String arg0, String idSource)
Broker an event with one in-band parameter (String).
The parameter carries extra information needed by the recipient.
Parameters
e The event being brokered.
arg0 The in-band parameter.
idSource ID of the module that has fired the event.
Definition at line 119 of file TBroker.java.
References TBroker._Broker(), and TBroker.gkArgsOneString.
     {
         _Broker (e, idSource, gkArgsOneString, 0, 0, arg0);
     }
void Subscribe (VBrowseable subscribed, IEvented subscriber)
Subscribes an IEvented object (subscriber) to receive events from another VBrowseable (subscribed).
The subscriber will receive all events emitted by the subscribed and needs to implement its own event filtering to listen to the events it's interested in.
Parameters
subscribed Subscribed.
subscriber Subscriber.
Definition at line 179 of file TBroker.java.
     {
         TBrokerSubscriptionList     subscrList;
         TBrokerSubscription         subscr;
         String                      key;
         boolean                     hasKey;
         key         = subscribed.GetID ();
         hasKey      = fSubscriptions.HasElement (key);
         if (hasKey)
         {
             subscrList = fSubscriptions.Get (key);
         }
         else
         {
             subscrList = new TBrokerSubscriptionList (subscribed);
             fSubscriptions.Set (key, subscrList);
         }
         subscr = new TBrokerSubscription (subscribed, subscriber);
         subscrList.Add (subscr);
     }
Member Data Documentation
TAtomicArrayMap<TBrokerSubscriptionList> fSubscriptions private
Complete list of subscriptions used in this session.
Definition at line 64 of file TBroker.java.
Referenced by TBroker.TBroker().
final int gkArgsNone = 0 static private
Internal flag: No in-band parameter.
Definition at line 44 of file TBroker.java.
Referenced by TBroker._Broker(), and TBroker.Broker().
final int gkArgsOneInt = 10 static private
Internal flag: One in-band parameter of type int.
Definition at line 49 of file TBroker.java.
Referenced by TBroker._Broker(), and TBroker.Broker().
final int gkArgsOneLong = 20 static private
Internal flag: One in-band parameter of type long.
Definition at line 54 of file TBroker.java.
Referenced by TBroker._Broker(), and TBroker.Broker().
final int gkArgsOneString = 30 static private
Internal flag: One in-band parameter of type String.
Definition at line 59 of file TBroker.java.
Referenced by TBroker._Broker(), and TBroker.Broker().
The documentation for this class was generated from the following file:
TBroker.java