ppm-java: TRegistry Class Reference
TRegistry Class Reference
A registry for browseable Objects.
Public Member Functions
TRegistry ()
cTor.
VAudioDriver GetAudioDriver ()
int GetNumFrontends ()
int GetNumObjects ()
VBrowseable GetObject (String id)
Queries the central storage for object id.
void Register (VAudioDriver d)
Registers the audio driver.
void Register (VBrowseable b)
Registers the given browseable.
void Register (VFrontend fe)
Registers the given frontend.
void Unregister (String id)
Unregisters the object with the given ID.
Private Attributes
VAudioDriver fAudioDriver
The audio driver.
TArrayMap< VFrontend > fFrontends
Active frontend(s).
TArrayMap< VBrowseable > fObjectsMap
The registry's main storage.
Detailed Description
A registry for browseable Objects.
Every object is registered by unique ID (Registry won't allow duplicate ID's). Clients can query and retrieve registered objects by their unique ID.
Author
Peter Hoppe
Definition at line 32 of file TRegistry.java.
Constructor & Destructor Documentation
TRegistry ()
cTor.
Definition at line 56 of file TRegistry.java.
References TRegistry.fAudioDriver, TRegistry.fFrontends, and TRegistry.fObjectsMap.
     {
         fObjectsMap     = new TArrayMap<> ();
         fFrontends      = new TArrayMap<> ();
         fAudioDriver    = null;
     }
Member Function Documentation
VAudioDriver GetAudioDriver ()
Returns
The audio driver.
Definition at line 66 of file TRegistry.java.
References TRegistry.fAudioDriver.
Referenced by TController._GetAudioDriver().
     {
         return fAudioDriver;
     }
int GetNumFrontends ()
Returns
The number of active front ends.
Definition at line 74 of file TRegistry.java.
     {
         int ret;
         ret = fFrontends.GetNumElements ();
         return ret;
     }
int GetNumObjects ()
Returns
The number of browseables stored.
Definition at line 86 of file TRegistry.java.
     {
         int ret;
         ret = fObjectsMap.GetNumElements ();
         return ret;
     }
VBrowseable GetObject (String id)
Queries the central storage for object id.
Parameters
id ID of the object searched for.
Returns
Queried object.
Definition at line 101 of file TRegistry.java.
Referenced by TController._GetAudioObject(), TController._StartStop(), and TController._SubscribeToEvents().
     {
         boolean         hasObject;
         VBrowseable     ret;
         hasObject = fObjectsMap.HasElement (id);
         if (hasObject)
         {
             ret = fObjectsMap.Get (id);
         }
         else
         {
             ret = null;
             TLogger.LogWarning ("Failed to get object", this, "GetObject (" + id + ")");
         }
         return ret;
     }
void Register (VAudioDriver d)
Registers the audio driver.
If another audio driver instance is already registered we'll log an error instead.
Parameters
d The driver to be registered.
Definition at line 126 of file TRegistry.java.
References TRegistry.fAudioDriver, and VBrowseable.GetID().
     {
         String      id;
         if (fAudioDriver == null)
         {   /* No driver registered yet - go ahead. */
             id              = d.GetID ();
             fAudioDriver    = d;
             fObjectsMap.Set (id, d);
             TLogger.LogMessage ("Audio driver registered", this, "Register (" + id + ")");
         }
         else
         {   /* Another audio driver is already registered. */
             TLogger.LogError
             (
                 "Audio driver already assigned to module: '" + fAudioDriver.GetID () +
                 "'. Can't reassign to module '" + d.GetID () + "'",
                 this,
                 "Register (VBrowseable b)"
             );
         }
     }
void Register (VBrowseable b)
Registers the given browseable.
Parameters
b Object to be registered.
Definition at line 154 of file TRegistry.java.
     {
         String      id;
         id      = b.GetID ();
         fObjectsMap.Set (id, b);
         TLogger.LogMessage ("Object registered", this, "Register (" + id + ")");
     }
void Register (VFrontend fe)
Registers the given frontend.
Parameters
fe Frontend to be registered.
Definition at line 168 of file TRegistry.java.
     {
         String      id;
         id = fe.GetID ();
         fObjectsMap.Set (id, fe);
         fFrontends.Set (id, fe);
         TLogger.LogMessage ("Frontend registered", this, "Register (" + id + ")");
     }
void Unregister (String id)
Unregisters the object with the given ID.
Parameters
id ID of the object to be unregistered.
Definition at line 183 of file TRegistry.java.
     {
         boolean         isFrontend;
         boolean         hasEntry;
         hasEntry    = fObjectsMap.HasElement (id);
         isFrontend  = fFrontends.HasElement  (id);
         if (hasEntry)
         {
             fObjectsMap.Remove (id);
             if (isFrontend)
             {
                 fFrontends.Remove (id);
             }
             if (isFrontend)
             {
                 TLogger.LogMessage ("Frontend removed", this, "Unregister (" + id + ")");
             }
             else
             {
                 TLogger.LogMessage ("Object removed", this, "Unregister (" + id + ")");
             }
         }
         else
         {
             TLogger.LogWarning ("Failed (Unknown id)", this, "Unregister (" + id + ")");
         }
     }
Member Data Documentation
VAudioDriver fAudioDriver private
The audio driver.
Definition at line 37 of file TRegistry.java.
Referenced by TRegistry.GetAudioDriver(), TRegistry.Register(), and TRegistry.TRegistry().
TArrayMap<VFrontend> fFrontends private
Active frontend(s).
These are kept in the main storage as well as in this storage. We need this extra bookkeeping so we can detect when the last frontend has been closed. In practice we'll use one front end only. But we still cater for the possibility to support multiple frontends.
Definition at line 46 of file TRegistry.java.
Referenced by TRegistry.TRegistry().
TArrayMap<VBrowseable> fObjectsMap private
The registry's main storage.
Definition at line 51 of file TRegistry.java.
Referenced by TRegistry.TRegistry().
The documentation for this class was generated from the following file:
TRegistry.java