ppm-java: VBrowseable Class Reference
VBrowseable Class Reference abstract
Base class for all browseable objects.
Public Member Functions
VBrowseable (String id)
cTor
String GetID ()
Protected Member Functions
abstract void _Register ()
Registers this object with the global registry.
Private Attributes
String fID
The unique ID under which this object can be found in the registry.
Detailed Description
Base class for all browseable objects.
Will automatically register with the global registry and can thus be accessed with an opaque ID. The ID must be unique; the registry will reject any double entries.
Every module, endpoint and connection in ppm-java is registered with the global registry and can be retrieved using its unique ID. This helps especially during session setup, as it enables us to use a simple and clean API to create and connect modules during the session setup.
The disadvantage is that browseables must be retrieved by their unique ID from the registry when they need to be accessed. This introduces a weak type system as the IDs carry no information about the type of the object retrieved. Also, it introduces the extra overhead of having to query the registry when retrieving a browseable. We can overcome these disadvantages by caching objects where they are used (e.g. private class fields). For example, endpoints keep their hosting module object as private field fHost.
The advantage of a simple syntax for session setup outweighs the disadvantage as it makes session setup much easier for the client.
Author
Peter Hoppe
Definition at line 46 of file VBrowseable.java.
Constructor & Destructor Documentation
VBrowseable (String id)
cTor
Parameters
id The unique ID under which we register this object with the registry.
Definition at line 59 of file VBrowseable.java.
References VBrowseable._Register(), and VBrowseable.fID.
     {
         fID         = id;
         _Register ();
     }
Member Function Documentation
abstract void _Register () abstract protected
Registers this object with the global registry.
We leave this as a virtual method, because inheriting classes might have unique requirements.
Referenced by VBrowseable.VBrowseable().
String GetID ()
Returns
The unique ID associated with this browseable.
Definition at line 68 of file VBrowseable.java.
References VBrowseable.fID.
Referenced by TNodePPMProcessor._CompensateCongestions(), TTimer._GetSaneInterval(), TAudioContext_JackD._LoadDriver(), VFrontend._OnTerminate(), TNodePump._Resolve_DataLoss(), VAudioPort_Output._SetTarget_Log(), TSink.OnEvent(), TGUINeedle_Surrogate.OnTerminate(), TGUILinearGauge_Surrogate.OnTerminate(), TRegistry.Register(), TTimer.SendTimerEvent(), and TSource.Start().
     {
         return fID;
     }
Member Data Documentation
String fID private
The unique ID under which this object can be found in the registry.
Definition at line 51 of file VBrowseable.java.
Referenced by VBrowseable.GetID(), and VBrowseable.VBrowseable().
The documentation for this class was generated from the following file:
VBrowseable.java