ppm-java: TDev_Trial_AtomicBuffer_Contention_01.TConsumer Class Reference
TDev_Trial_AtomicBuffer_Contention_01.TConsumer Class Reference
Public Member Functions
TConsumer (int id, TAtomicBuffer b)
void run ()
Private Member Functions
void TestNums ()
void PrintCorrupted (int iSample, float x0, float x1)
void PrintLogEntry (String message)
void PrintReport ()
Private Attributes
TAtomicBuffer fAtBuffer
int fID
int fDelay
int fNCorruptions
int fNEmptyFrames
Detailed Description
Definition at line 1170 of file TDev_Trial_AtomicBuffer_Contention_01.java.
Constructor & Destructor Documentation
TConsumer (int id, TAtomicBuffer b)
Definition at line 1178 of file TDev_Trial_AtomicBuffer_Contention_01.java.
References TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fAtBuffer, TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fDelay, TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fID, TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fNCorruptions, and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fNEmptyFrames.
         {
             fAtBuffer                   = b;
             fID                         = id;
             fDelay                      = 1;
             fNCorruptions               = 0;
             fNEmptyFrames               = 0;
         }
Member Function Documentation
void PrintCorrupted (int iSample, float x0, float x1) private
Definition at line 1240 of file TDev_Trial_AtomicBuffer_Contention_01.java.
References TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintLogEntry().
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TestNums().
         {
             String logEntry;
             logEntry = "Data corruption: iSample=" + iSample + "; x[iSample]=" + x1 + "; x[iSample-1]=" + x0;
             PrintLogEntry (logEntry);
         }
void PrintLogEntry (String message) private
Definition at line 1248 of file TDev_Trial_AtomicBuffer_Contention_01.java.
References TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fID, and TDev_Trial_AtomicBuffer_Contention_01.gLock.
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintCorrupted(), and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintReport().
         {
             String le;
             le = "Consumer [" + fID + "]: " + message;
             synchronized (gLock)                /* [100] */
             {
                 System.out.println (le);
             }
         }
void PrintReport () private
Definition at line 1259 of file TDev_Trial_AtomicBuffer_Contention_01.java.
References TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fNCorruptions, TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fNEmptyFrames, and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintLogEntry().
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.run().
         {
             String preamble;
             String postAmble;
             String logMessage;
             if (fNCorruptions >= 1)
             {
                 preamble = "Finished (fatal problem): ";
             }
             else
             {
                 preamble = "Finished (ok           ): ";
             }
             if (fNEmptyFrames >= 1)
             {
                 postAmble = "; Consumed a few empty frames (not critical)";
             }
             else
             {
                 postAmble = "";
             }
             logMessage = preamble + "nCorruptions: " + fNCorruptions + "; nEmptyFrames: " + fNEmptyFrames + postAmble;
             PrintLogEntry (logMessage);
         }
void run ()
Definition at line 1188 of file TDev_Trial_AtomicBuffer_Contention_01.java.
References TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fDelay, TDev_Trial_AtomicBuffer_Contention_01.gkNRunsConsumer, TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintReport(), and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TestNums().
         {
             int i;
             gNConsumersRunning.incrementAndGet ();
             for (i = 0; i < gkNRunsConsumer; i++)
             {
                 TestNums ();
                 try {Thread.sleep (fDelay);} catch (InterruptedException e) {}
                 fDelay += 9;
             }
             PrintReport ();
             gNConsumersRunning.decrementAndGet ();
         }
void TestNums () private
Definition at line 1203 of file TDev_Trial_AtomicBuffer_Contention_01.java.
References TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fNCorruptions, TDev_Trial_AtomicBuffer_Contention_01.TConsumer.fNEmptyFrames, TDev_Trial_AtomicBuffer_Contention_01.gkNNums, and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintCorrupted().
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.run().
         {
             int                 i;
             int                 n;
             float               x0;
             float               x1;
             float               dx;
             FloatBuffer         fb;
             fb              = fAtBuffer.Get ();
             n               = fb.capacity ();
             if (n == gkNNums)
             {
                 for (i = gkNNums-1; i >= 1; i--)
                 {
                     /* Corruption check - difference between sample[i] and
                      * sample[i-1] must be 1. If the tested buffer isn't
                      * thread safe then with some likelihood there will be
                      * another thread corrupting the order and the
                      * aforementioned difference would be disturbed.
                      */
                     x0      = fb.get (i-1);
                     x1      = fb.get (i);
                     dx      = x1 - x0;
                     if (dx != 1.0)
                     {
                         fNCorruptions++;
                         PrintCorrupted (i, x0, x1);
                     }
                 }
             }
             else
             {
                 fNEmptyFrames++;
             }
         }
Member Data Documentation
TAtomicBuffer fAtBuffer private
Definition at line 1172 of file TDev_Trial_AtomicBuffer_Contention_01.java.
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TConsumer().
int fDelay private
Definition at line 1174 of file TDev_Trial_AtomicBuffer_Contention_01.java.
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.run(), and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TConsumer().
int fID private
Definition at line 1173 of file TDev_Trial_AtomicBuffer_Contention_01.java.
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintLogEntry(), and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TConsumer().
int fNCorruptions private
Definition at line 1175 of file TDev_Trial_AtomicBuffer_Contention_01.java.
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintReport(), TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TConsumer(), and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TestNums().
int fNEmptyFrames private
Definition at line 1176 of file TDev_Trial_AtomicBuffer_Contention_01.java.
Referenced by TDev_Trial_AtomicBuffer_Contention_01.TConsumer.PrintReport(), TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TConsumer(), and TDev_Trial_AtomicBuffer_Contention_01.TConsumer.TestNums().
The documentation for this class was generated from the following file:
TDev_Trial_AtomicBuffer_Contention_01.java