ppm-java: TNodePump Class Reference
TNodePump Class Reference
A data pump.
Public Member Functions
void CreatePort_In (String id)
void CreatePort_Out (String id)
void OnEvent (int e)
Receive an event with no parameter.
void OnEvent (int e, int arg0)
Receive an event with one in-band integer as parameter.
void OnEvent (int e, long arg0)
Receive an event with one in-band long as parameter.
void OnEvent (int e, String arg0)
Receive an event with one in-band String as parameter.
IStats StatsGet ()
Public Member Functions inherited from VAudioProcessor
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
abstract void CreatePort_In (String id)
Creates an input port.
abstract void CreatePort_Out (String id)
Creates an output port.
int GetNumPortsIn ()
int GetNumPortsOut ()
VAudioPort GetPortIn (int i)
Returns the ith input port.
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static void CreateInstance (String id)
Creates a new instance of this module.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VAudioProcessor
void AddPortIn (VAudioPort_Input p)
Adds a new input port.
void AddPortOut (VAudioPort_Output p)
Adds a new output port.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Private Member Functions
TNodePump (String id)
cTor.
void _FetchAndSend ()
Fetches and sends the next sample chunk to the connected module.
void _Initialize ()
Initializes a few objects and sets the initial value for fTLast.
void _RecomputeRuntimeStats ()
Recomputes some runtime statistics for the next cycle (e.g.
void _Resolve_DataLoss ()
Compensates for data loss (i.e.
void _SendNextPacket ()
Retrieves next chunk of data.
Private Attributes
TAudioContext_JackD fAudioDriver
The global audio driver instance.
TNodePump_Endpoint_In fEndptIn
Input Endpoint.
TNodePump_Endpoint_Out fEndptOut
Output endpoint.
boolean fHasBeenInitialized
If false, then we still need to initialize some local properties.
int fNSamplesPerCycle
Number of samples per display engine cycle.
FloatBuffer fPacketLast
The sample chunk we are currently using to extract data.
int fSampleRate
The audio driver's sample rate.
TNodePump_Stats fStats
The statistics record.
long fTCycleDesired
For underrun/overrun compensation: Desired cycle time of the display engine.
long fTDelta
Time difference [ms] between this frame and last frame.
long fTLast
Absolute time [ms since 01.01.1970 00:00] when the current display engine cycle started.
Additional Inherited Members
Static Public Attributes inherited from IEvented
static final int gkEventBufferNotifyOverrun = 1210
Notification: An atomic buffer had an overrun.
static final int gkEventBufferNotifyUnderrun = 1200
Notification: An atomic buffer had an underrun.
static final int gkEventStart = 1000
Notification: Module has started.
static final int gkEventStop = 1010
Notification: Module has stopped.
static final int gkEventTimerAdjustInterval = 1120
Request: Change a TTimer's interval.
static final int gkEventTimerNotifyInterval = 1110
Notify: A TTimer changed interval.
static final int gkEventTimerTick = 1100
Notify: TTimer, new cycle.
Detailed Description
A data pump.
Fetches the audio data from the audio driver, repackages it in smaller chunks if needed and passes those on to further stages. Also, initiates cycle time correction to the GUI timer if we have data loss.
The data pump is designed to work together with an audio driver; it acts as a priority inversion barrier between audio driver and display engine. This enables the audio driver to work undisturbed, no matter what happens on the display driver side.
Author
Peter Hoppe
Definition at line 44 of file TNodePump.java.
Constructor & Destructor Documentation
TNodePump (String id) private
cTor.
Parameters
id Unique ID as which we register this module.
Definition at line 123 of file TNodePump.java.
References TNodePump.fAudioDriver, TNodePump.fEndptIn, TNodePump.fEndptOut, TNodePump.fHasBeenInitialized, TNodePump.fStats, TNodePump.fTCycleDesired, TNodePump.fTDelta, and TNodePump.fTLast.
Referenced by TNodePump.CreateInstance().
     {
         super (id, 1, 1);
         fStats                          = new TNodePump_Stats (this);
         fHasBeenInitialized             = false;
         fAudioDriver                    = null;
         fEndptIn                        = null;
         fEndptOut                       = null;
         fTLast                          = -1;
         fTCycleDesired                  = -1;
         fTDelta                         = -1;
         TController.StatAddProvider (this);
     }
Member Function Documentation
void _FetchAndSend () private
Fetches and sends the next sample chunk to the connected module.
Also, adjusts the cycle frequency so the data stream processed comprises the same number of samples per second as the data stream coming in from the audio driver.
Definition at line 233 of file TNodePump.java.
References TNodePump._RecomputeRuntimeStats(), TNodePump._Resolve_DataLoss(), and TNodePump._SendNextPacket().
Referenced by TNodePump.OnEvent().
     {
         /* Recompute timings and some other statistics. */
         _RecomputeRuntimeStats ();
         /* Retrieve next sample packet [110]. */
         _SendNextPacket ();
         /* Compensate input buffer overruns/underruns. */
         _Resolve_DataLoss ();
     }
void _Initialize () private
Initializes a few objects and sets the initial value for fTLast.
Definition at line 248 of file TNodePump.java.
References TNodePump.fAudioDriver, TNodePump.fEndptIn, TNodePump.fEndptOut, TNodePump.fPacketLast, TNodePump.fTLast, VAudioProcessor.GetPortIn(), and VAudioProcessor.GetPortOut().
Referenced by TNodePump.OnEvent().
     {
         TAtomicBuffer_Stats     endpointInStats;
         fAudioDriver        = TController.GetAudioDriver ();
         fEndptIn            = (TNodePump_Endpoint_In)  GetPortIn (0);
         fEndptOut           = (TNodePump_Endpoint_Out) GetPortOut (0);
         fTLast              = System.currentTimeMillis ();
         fPacketLast         = null;
         endpointInStats     = fEndptIn.StatsGet ();
         fStats.SetEndpointInStats (endpointInStats);
     }
void _RecomputeRuntimeStats () private
Recomputes some runtime statistics for the next cycle (e.g.
how many samples we should pass on).
Definition at line 266 of file TNodePump.java.
References TNodePump.fNSamplesPerCycle, TNodePump.fSampleRate, TNodePump.fTCycleDesired, TNodePump.fTDelta, and TNodePump.fTLast.
Referenced by TNodePump._FetchAndSend().
     {
         long                    tNow;
         long                    tDelta;
         double                  xSampleRate;
         double                  nSamplesPerCycle;
         tNow        = System.currentTimeMillis ();
         tDelta      = tNow - fTLast;
         if (fTCycleDesired <= -1)
         {
             fTCycleDesired = tDelta;
         }
         xSampleRate         = fAudioDriver.GetSampleRate ();
         nSamplesPerCycle    = tDelta * xSampleRate / 1000;              /* [140] */
         fTDelta             = tDelta;
         fTLast              = tNow;
         fSampleRate         = (int) xSampleRate;
         fNSamplesPerCycle   = (int) (nSamplesPerCycle);
         fStats.SetCycleTime             (fTDelta);
         fStats.SetNumSamplesPerCycle    (fNSamplesPerCycle);
         fStats.SetSampleRate            (fSampleRate);
     }
void _Register () protected
Definition at line 222 of file TNodePump.java.
     {
         TController.Register (this);
     }
void _Resolve_DataLoss () private
Compensates for data loss (i.e.
under/overruns) on the attached input buffer by issuing a request to the GUI timer to set the timer interval to a new value. If we have underruns this means that we aren't getting enough data which means the cycle interval is too short and needs to be longer. If we have overruns it means that the audio driver is delivering more data than we can process which means the cycle interval is too long.
Correction follows a simple linear strategy - for each cycle, if we detected data loss we increase or decrease the desired cycle time by one millisecond and notify the GUI timer that we request a change of cycle time.
Definition at line 307 of file TNodePump.java.
References TNodePump.fTCycleDesired, VBrowseable.GetID(), IEvented.gkEventTimerAdjustInterval, and TTimer.gkLoopIntervalMin.
Referenced by TNodePump._FetchAndSend().
     {
         String                          id;
         TAtomicBuffer_Stats             st;
         TAtomicBuffer_DumpRecord                         stRec;
         id      = GetID ();
         st      = fEndptIn.StatsGet ();
         stRec   = st.GetRecord ();
         if (stRec.fDiffOverUnderruns > 0)
         {   /* Overruns - meaning the JackD audio driver pushes more
             data than we handle at the moment => We must decrement
             GUI timer cycle interval. We use a simple linear decrement. */
             if (fTCycleDesired > TTimer.gkLoopIntervalMin)
             {
                 fTCycleDesired--;
                 TController.PostEvent (gkEventTimerAdjustInterval, fTCycleDesired, id);
             }
             st.Clear ();                                                /* [130 */
         }
         else if (stRec.fDiffOverUnderruns < 0)
         {   /* Underruns - meaning the GUI update cycle tries to draw too
              * much data => We must increment GUI timer cycle interval.
              * We use a simple linear increment. */
             fTCycleDesired++;
             TController.PostEvent (gkEventTimerAdjustInterval, fTCycleDesired, id);
             st.Clear ();                                                /* [130] */
         }
     }
void _SendNextPacket () private
Retrieves next chunk of data.
Since our cycle frequency is different than the frequency in which the JackD driver delivers data we need to chop the incoming packets up to process the same amount of samples per time as what's delivered by the audio driver.
Definition at line 344 of file TNodePump.java.
References TNodePump.fNSamplesPerCycle, and TNodePump.fPacketLast.
Referenced by TNodePump._FetchAndSend().
     {
         FloatBuffer         newPacket;
         int                 i;
         int                 nSamples;
         float               s;
         FloatBuffer         outPacket;
         newPacket = fEndptIn.FetchPacket ();
         if (newPacket != null)
         {
             /* If we have new data we discard any old data */
             fPacketLast = newPacket;            /* Discard previous packet.                                         */
             fPacketLast.rewind ();              /* Ensure read pointer and markers are at zero position.            */
             nSamples = fPacketLast.limit ();    /* How many samples are we talking about?                           */
             if (nSamples > fNSamplesPerCycle)   /* Too many samples?                                                */
             {                                   /* For now, only read what we need. Postpone rest for next cycle(s) */
                 nSamples = (int) fNSamplesPerCycle;
             }
         }
         else if (fPacketLast != null)
         {
             /* No fresh data available, but the previous packet may still have unresolved data */
             nSamples = fPacketLast.remaining ();
             if (nSamples > fNSamplesPerCycle)
             {   /* We have too much data to crunch. Only use as much as needed. */
                 nSamples = (int) fNSamplesPerCycle;
             }
             else if (nSamples <= 0)
             {   /* No data left to read. Delete packet. */
                 fPacketLast = null;
             }
             /* else-case: All the possible values in [1, fNSamplesPerCycle] */
             /* At this point, nSamples will be between 0 and fNSamplesPerCycle. */
         }
         else
         {   /* No data available */
             nSamples = 0;
         }
         if (nSamples >= 1)
         {
             /* We've got samples to send. Assemble an output packet (= new object). [120] */
             outPacket = FloatBuffer.allocate (nSamples);
             for (i = 1; i <= nSamples; i++)
             {
                 s = fPacketLast.get ();
                 outPacket.put (s);
             }
         }
         else
         {
             /* We've got no samples to send. Send a null packet. */
             outPacket = null;
         }
         /* Push sample data to the next module. */
         fEndptOut.PushPacket (outPacket);
     }
static void CreateInstance (String id) static
Creates a new instance of this module.
Parameters
id Unique ID as which we register this module.
Definition at line 53 of file TNodePump.java.
References TNodePump.TNodePump().
     {
         new TNodePump (id);
     }
void CreatePort_In (String id)
Definition at line 142 of file TNodePump.java.
References VAudioProcessor.AddPortIn(), EAtomicBuffer_CopyPolicy.kCopyOnGet, and EAtomicBuffer_IfInvalidPolicy.kReturnNull.
     {
         TNodePump_Endpoint_In       p;
         p = new TNodePump_Endpoint_In (id, this, EAtomicBuffer_CopyPolicy.kCopyOnGet, EAtomicBuffer_IfInvalidPolicy.kReturnNull);
         AddPortIn (p);
     }
void CreatePort_Out (String id)
Definition at line 154 of file TNodePump.java.
References VAudioProcessor.AddPortOut().
     {
         TNodePump_Endpoint_Out      p;
         p = new TNodePump_Endpoint_Out (id, this);
         AddPortOut (p);
     }
void OnEvent (int e)
Receive an event with no parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
Implements IEvented.
Definition at line 166 of file TNodePump.java.
References TNodePump._FetchAndSend(), TNodePump._Initialize(), TNodePump.fHasBeenInitialized, and IEvented.gkEventTimerTick.
     {
         if (e == gkEventTimerTick)
         {
             if (fHasBeenInitialized)
             {
                 _FetchAndSend ();
             }
             else
             {
                 _Initialize ();                                         /* [100] */
                 fHasBeenInitialized = true;
             }
         }
     }
void OnEvent (int e, int arg0)
Receive an event with one in-band integer as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 186 of file TNodePump.java.
     {
         // Do nothing
     }
void OnEvent (int e, long arg0)
Receive an event with one in-band long as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 195 of file TNodePump.java.
     {
         // Do nothing
     }
void OnEvent (int e, String arg0)
Receive an event with one in-band String as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 204 of file TNodePump.java.
     {
         // Do nothing
     }
IStats StatsGet ()
Returns
The current runtime statistics.
Implements IStatEnabled.
Definition at line 213 of file TNodePump.java.
References TNodePump.fStats.
     {
         return fStats;
     }
Member Data Documentation
TAudioContext_JackD fAudioDriver private
The global audio driver instance.
Definition at line 61 of file TNodePump.java.
Referenced by TNodePump._Initialize(), and TNodePump.TNodePump().
TNodePump_Endpoint_In fEndptIn private
Input Endpoint.
For this module, it's easier to have it cached.
Definition at line 66 of file TNodePump.java.
Referenced by TNodePump._Initialize(), and TNodePump.TNodePump().
TNodePump_Endpoint_Out fEndptOut private
Output endpoint.
For this module, it's easier to have it cached.
Definition at line 71 of file TNodePump.java.
Referenced by TNodePump._Initialize(), and TNodePump.TNodePump().
boolean fHasBeenInitialized private
If false, then we still need to initialize some local properties.
Most notably, we need to determine the time of the first incoming IEvented#gkEventTimerTick. This time of the first timer event will become the initial time. From the second timer tick onwards we always compute the time difference to the previous frame which we need to calculate various runtime statistics.
Definition at line 81 of file TNodePump.java.
Referenced by TNodePump.OnEvent(), and TNodePump.TNodePump().
int fNSamplesPerCycle private
Number of samples per display engine cycle.
Definition at line 86 of file TNodePump.java.
Referenced by TNodePump._RecomputeRuntimeStats(), and TNodePump._SendNextPacket().
FloatBuffer fPacketLast private
The sample chunk we are currently using to extract data.
Definition at line 91 of file TNodePump.java.
Referenced by TNodePump._Initialize(), and TNodePump._SendNextPacket().
int fSampleRate private
The audio driver's sample rate.
Definition at line 96 of file TNodePump.java.
Referenced by TNodePump._RecomputeRuntimeStats().
TNodePump_Stats fStats private
The statistics record.
Updated during runtime.
Definition at line 101 of file TNodePump.java.
Referenced by TNodePump.StatsGet(), and TNodePump.TNodePump().
long fTCycleDesired private
For underrun/overrun compensation: Desired cycle time of the display engine.
Definition at line 106 of file TNodePump.java.
Referenced by TNodePump._RecomputeRuntimeStats(), TNodePump._Resolve_DataLoss(), and TNodePump.TNodePump().
long fTDelta private
Time difference [ms] between this frame and last frame.
Definition at line 111 of file TNodePump.java.
Referenced by TNodePump._RecomputeRuntimeStats(), and TNodePump.TNodePump().
long fTLast private
Absolute time [ms since 01.01.1970 00:00] when the current display engine cycle started.
Definition at line 116 of file TNodePump.java.
Referenced by TNodePump._Initialize(), TNodePump._RecomputeRuntimeStats(), and TNodePump.TNodePump().
The documentation for this class was generated from the following file:
TNodePump.java