ppm-java: TTimer Class Reference
TTimer Class Reference
Emits a constant stream of IEvented#gkEventTimerTick events, on event per given interval.
Public Member Functions
long GetInterval ()
void OnEvent (int e)
Receive an event with no parameter.
void OnEvent (int e, int arg0)
Receive an event with one in-band integer as parameter.
void OnEvent (int e, long arg0)
Receive an event with one in-band long as parameter.
void OnEvent (int e, String arg0)
Receive an event with one in-band String as parameter.
void Start ()
Starts the module.
void Stop ()
Stops the module.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static void CreateInstance (String id, int intervalMs)
Creates a new TTimer instance.
Static Public Attributes
static final int gkLoopIntervalMin = 10
Minimum interval.
Static Public Attributes inherited from IEvented
static final int gkEventBufferNotifyOverrun = 1210
Notification: An atomic buffer had an overrun.
static final int gkEventBufferNotifyUnderrun = 1200
Notification: An atomic buffer had an underrun.
static final int gkEventStart = 1000
Notification: Module has started.
static final int gkEventStop = 1010
Notification: Module has stopped.
static final int gkEventTimerAdjustInterval = 1120
Request: Change a TTimer's interval.
static final int gkEventTimerNotifyInterval = 1110
Notify: A TTimer changed interval.
static final int gkEventTimerTick = 1100
Notify: TTimer, new cycle.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Package Functions
void SendTimerEvent ()
Sends the IEvented#gkEventTimerTick event to all subscribers.
Private Member Functions
TTimer (String id, int delayMs)
cTor.
long _GetSaneInterval (long delayMs)
Returns a sanitized timer interval, if the given value was out of bounds.
Private Attributes
TTimerWorker fWorker
The internal worker thread which does the actual looping and event triggering.
Detailed Description
Emits a constant stream of IEvented#gkEventTimerTick events, on event per given interval.
Modules can subscribe to this timer and will then receive the events. Recipients can use the timer events to perform regular tasks.
Modules, in turn can send IEvented#gkEventTimerAdjustInterval events to change the interval time in this timer. This is the basis of the data contention compensation we use in the display engine.
Author
Peter Hoppe
See Also
TController::Create_Connection_Events(String, String)
TNodePump::_Resolve_DataLoss()
Definition at line 39 of file TTimer.java.
Constructor & Destructor Documentation
TTimer (String id, int delayMs) private
cTor.
Parameters
id Unique ID as which we register this timer.
delayMs Requested timer interval, in ms. We enforce a lower limit of gkLoopIntervalMin ms.
Definition at line 72 of file TTimer.java.
References TTimer._GetSaneInterval(), and TTimer.fWorker.
Referenced by TTimer.CreateInstance().
     {
         super (id);
         long d;
         d       = _GetSaneInterval (delayMs);
         fWorker = new TTimerWorker (this, d);
     }
Member Function Documentation
long _GetSaneInterval (long delayMs) private
Returns a sanitized timer interval, if the given value was out of bounds.
Parameters
delayMs The suggested interval.
Returns
The suggested interval, if it's larger than (or equal to) gkLoopIntervalMin. Otherwise, returns gkLoopIntervalMin
Definition at line 179 of file TTimer.java.
References VBrowseable.GetID(), and TTimer.gkLoopIntervalMin.
Referenced by TTimer.OnEvent(), and TTimer.TTimer().
     {
         long ret;
         if (delayMs >= gkLoopIntervalMin)
         {
             ret = delayMs;
         }
         else
         {
             ret = gkLoopIntervalMin;
             TLogger.LogError
             (
                 "For timer '" + GetID () + "': Given interval must be >= " +
                 gkLoopIntervalMin + ". Given: " + delayMs +
                 ". Set to " + ret, this, "cTor"
             );
         }
         return ret;
     }
void _Register () protected
Definition at line 155 of file TTimer.java.
     {
         TController.Register (this);
     }
static void CreateInstance (String id, int intervalMs) static
Creates a new TTimer instance.
Parameters
id Unique ID as which we register this timer.
intervalMs Requested timer interval, in ms. We enforce a lower limit of gkLoopIntervalMin ms.
Definition at line 55 of file TTimer.java.
References TTimer.TTimer().
     {
         new TTimer (id, intervalMs);
     }
long GetInterval ()
Returns
This timer's interval in ms.
Definition at line 85 of file TTimer.java.
     {
         long ret;
         ret = fWorker.GetInterval ();
         return ret;
     }
void OnEvent (int e)
Receive an event with no parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
Implements IEvented.
Definition at line 98 of file TTimer.java.
     {
         // Do nothing
     }
void OnEvent (int e, int arg0)
Receive an event with one in-band integer as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 107 of file TTimer.java.
     {
     }
void OnEvent (int e, long arg0)
Receive an event with one in-band long as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 115 of file TTimer.java.
References TTimer._GetSaneInterval(), and IEvented.gkEventTimerAdjustInterval.
     {
         long         newIntervalMs;
         if (e == gkEventTimerAdjustInterval)
         {
             newIntervalMs = _GetSaneInterval (arg0);
             fWorker.SetInterval (newIntervalMs);
         }
     }
void OnEvent (int e, String arg0)
Receive an event with one in-band String as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 130 of file TTimer.java.
     {
         // Do nothing
     }
void SendTimerEvent () package
Sends the IEvented#gkEventTimerTick event to all subscribers.
Definition at line 163 of file TTimer.java.
References VBrowseable.GetID(), and IEvented.gkEventTimerTick.
     {
         String id;
         id = GetID ();
         TController.PostEvent (IEvented.gkEventTimerTick, id);
     }
void Start ()
Starts the module.
Implements IControllable.
Definition at line 138 of file TTimer.java.
     {
         fWorker.start ();
     }
void Stop ()
Stops the module.
Implements IControllable.
Definition at line 146 of file TTimer.java.
     {
         fWorker.Stop ();
     }
Member Data Documentation
TTimerWorker fWorker private
The internal worker thread which does the actual looping and event triggering.
Definition at line 63 of file TTimer.java.
Referenced by TTimer.TTimer().
final int gkLoopIntervalMin = 10 static
Minimum interval.
Definition at line 46 of file TTimer.java.
Referenced by TNodePPMProcessor._CompensateCongestions(), TTimer._GetSaneInterval(), and TNodePump._Resolve_DataLoss().
The documentation for this class was generated from the following file:
TTimer.java