ppm-java: VAudioPort_Output Class Reference
VAudioPort_Output Class Reference abstract
Base class for an output audio port.
Public Member Functions
VAudioPort_Output (String id, VAudioProcessor host)
cTor.
void SetTarget (VAudioPort_Input target)
Connects this port to an input port.
Public Member Functions inherited from VAudioPort
VAudioPort (String id, VAudioProcessor host)
cTor.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Protected Member Functions
VAudioPort_Input _GetTarget ()
final void _SetTarget (VAudioPort_Input target)
Worker method to establish a connection to an input port, called by the _Visit(...) method of the runtime chose subtype.
final void _SetTarget_Log (VAudioPort_Input target, boolean isErr)
Logs a message when a connection to a VAudioPort_Input is made.
abstract void _Visit (VAudioPort_Input_Chunks_Buffered target)
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Chunks_Buffered.
abstract void _Visit (VAudioPort_Input_Chunks_Unbuffered target)
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Chunks_Unbuffered.
abstract void _Visit (VAudioPort_Input_Samples target)
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Samples.
Protected Member Functions inherited from VAudioPort
VAudioProcessor _GetHost ()
abstract String _GetType ()
Returns textual information of a concrete child's direct super type.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Private Attributes
VAudioPort_Input fTarget
The input connected to this output.
Detailed Description
Base class for an output audio port.
An output port is always associated with a hosting audio processor. It's connected with another VAudioPort_Input to where it sends its data. Every time this port sends data it will trigger a processing cycle in the audio processor associated with the connected input.
To ensure type safety the connection mechanism uses the visitor pattern for the connection to an input port. This class is the visitor base class and provides the prototypes for the _Visit(...) methods.
Author
Peter Hoppe
Definition at line 36 of file VAudioPort_Output.java.
Constructor & Destructor Documentation
VAudioPort_Output (String id, VAudioProcessor host)
cTor.
Parameters
id Unique ID as which we register this port.
Definition at line 48 of file VAudioPort_Output.java.
     {
         super (id, host);
         TLogger.LogMessage ("Processor: '" + host.GetID () + "': Creating output port '" + id + "'", this, "cTor");
     }
Member Function Documentation
VAudioPort_Input _GetTarget () protected
Returns
The input port we are connected to.
Definition at line 69 of file VAudioPort_Output.java.
References VAudioPort_Output.fTarget.
Referenced by VAudioPort_Output_Chunks_NeedsBuffer.PushPacket(), VAudioPort_Output_Chunks_NoBuffer.PushPacket(), and VAudioPort_Output_Samples.PushSample().
     {
         return fTarget;
     }
final void _SetTarget (VAudioPort_Input target) protected
Worker method to establish a connection to an input port, called by the _Visit(...) method of the runtime chose subtype.
Parameters
target The input port we connect to.
Definition at line 80 of file VAudioPort_Output.java.
References VAudioPort_Output._SetTarget_Log(), and VAudioPort_Output.fTarget.
Referenced by VAudioPort_Output_Chunks_NeedsBuffer._Visit(), VAudioPort_Output_Samples._Visit(), and VAudioPort_Output_Chunks_NoBuffer._Visit().
     {
         fTarget = target;
         _SetTarget_Log (target, false);
     }
final void _SetTarget_Log (VAudioPort_Input target, boolean isErr) protected
Logs a message when a connection to a VAudioPort_Input is made.
Parameters
target The audio port we connect to.
isErr if false, indicate a valid connection, if true, indicate a faulty connection.
Definition at line 93 of file VAudioPort_Output.java.
References VAudioPort._GetType(), and VBrowseable.GetID().
Referenced by VAudioPort_Output._SetTarget(), VAudioPort_Output_Samples._Visit(), VAudioPort_Output_Chunks_NoBuffer._Visit(), and VAudioPort_Output_Chunks_NeedsBuffer._Visit().
     {
         String      msg;
         msg  =     "Connecting endpoints: '"
                  + GetID()
                  + "' ("
                  + _GetType ()
                  + ")  -> '"
                  + target.GetID ()
                  + "' ("
                  + target._GetType ()
                  + "): ";
         if (isErr)
         {
             msg += "Failure: Incompatible endpoint types";
             TLogger.LogWarning (msg, this, "SetTarget");
         }
         else
         {
             msg += "OK";
             TLogger.LogMessage (msg, this, "SetTarget");
         }
     }
abstract void _Visit (VAudioPort_Input_Chunks_Buffered target) abstract protected
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Chunks_Buffered.
Parameters
target The visitor.
abstract void _Visit (VAudioPort_Input_Chunks_Unbuffered target) abstract protected
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Chunks_Unbuffered.
Parameters
target The visitor.
abstract void _Visit (VAudioPort_Input_Samples target) abstract protected
Visitor pattern: Visit method, called if the visitor is of type VAudioPort_Input_Samples.
Parameters
target The visitor.
void SetTarget (VAudioPort_Input target)
Connects this port to an input port.
This is the entry method.
Parameters
target The input port we connect to.
Definition at line 61 of file VAudioPort_Output.java.
     {
         target._Accept (this);
     }
Member Data Documentation
VAudioPort_Input fTarget private
The input connected to this output.
Definition at line 41 of file VAudioPort_Output.java.
Referenced by VAudioPort_Output._GetTarget(), and VAudioPort_Output._SetTarget().
The documentation for this class was generated from the following file:
VAudioPort_Output.java