ppm-java: TConsole_TextOut Class Reference
TConsole_TextOut Class Reference
A simple text-only frontend.
Public Member Functions
void CreatePort_In (String id)
void OnEvent (int e)
Receive an event with no parameter.
void OnEvent (int e, int arg0)
Receive an event with one in-band integer as parameter.
void OnEvent (int e, long arg0)
Receive an event with one in-band long as parameter.
void OnEvent (int e, String arg0)
Receive an event with one in-band String as parameter.
void Start ()
Starts the module.
void Stop ()
Stops the module.
Public Member Functions inherited from VFrontend
VFrontend (String id, int nMaxChanIn)
final void CreatePort_Out (String id)
Public Member Functions inherited from VAudioProcessor
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
abstract void CreatePort_In (String id)
Creates an input port.
abstract void CreatePort_Out (String id)
Creates an output port.
int GetNumPortsIn ()
int GetNumPortsOut ()
VAudioPort GetPortIn (int i)
Returns the ith input port.
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static final void CreateInstance (String id)
Creates a new instance of this frontend.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VFrontend
void _OnTerminate ()
Handler for: Frontend terminated.
Protected Member Functions inherited from VAudioProcessor
void AddPortIn (VAudioPort_Input p)
Adds a new input port.
void AddPortOut (VAudioPort_Output p)
Adds a new output port.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Package Functions
void Receive (float sample, int iPort)
Receives a sample value and prints it to stdout as JSON record.
Private Member Functions
TConsole_TextOut (String id)
cTor.
void _PushRecord (ERecordType fieldType, String info, float sample, int iPort)
Creates a JSON record from the given parameters.
Static Private Attributes
static final String gkRecordTypeInfo = "info"
Signifier, info record.
static final String gkRecordTypeSample = "sample"
Signifier, sample record.
Additional Inherited Members
Static Public Attributes inherited from IEvented
static final int gkEventBufferNotifyOverrun = 1210
Notification: An atomic buffer had an overrun.
static final int gkEventBufferNotifyUnderrun = 1200
Notification: An atomic buffer had an underrun.
static final int gkEventStart = 1000
Notification: Module has started.
static final int gkEventStop = 1010
Notification: Module has stopped.
static final int gkEventTimerAdjustInterval = 1120
Request: Change a TTimer's interval.
static final int gkEventTimerNotifyInterval = 1110
Notify: A TTimer changed interval.
static final int gkEventTimerTick = 1100
Notify: TTimer, new cycle.
Detailed Description
A simple text-only frontend.
Writes a stream of records in JSON format to STDOUT. Caters for a special use case where we want to stream the metering information over a network connection to another host. As the JSON records are written to STDOUT it's possible to pipe them to another program, e.g. a web socket provider. This frontend produces two types of records:
Sample record
A record containing a value (sample). Contains the sample value and which channel it's for. Record scheme:
{
    "type":     "sample",       // Record type ID
    "value":    float-value,    // The sample value
    "port":     int-value       // For which port (0: Left channel, 1: Right channel)
}
Info record
A record containing in-band information (e.g. "Metering stops"). Record scheme:
{
    "type":     "info",         // Record type ID
    "value":    string          // The info message
}
To create info records we use ppm-java's event system. If you use this frontend, make sure that you connect the frontend instance to an event emitter that sends the control messages.
Note that the info record API isn't fully developed yet.
Author
Peter Hoppe
///
Todo:
This frontend needs further development, as we haven't yet fully developed the info record API. So far, only "Start" and "Stop" are implemented. More items are needed, e.g. "is the audio in mono or stereo?"
Definition at line 65 of file TConsole_TextOut.java.
Constructor & Destructor Documentation
TConsole_TextOut (String id) private
cTor.
Parameters
id Unique ID as which we register this frontend.
Definition at line 96 of file TConsole_TextOut.java.
Referenced by TConsole_TextOut.CreateInstance().
     {
         super (id, 2);
     }
Member Function Documentation
void _PushRecord (ERecordType fieldType, String info, float sample, int iPort) private
Creates a JSON record from the given parameters.
Parameters
fieldType Type of record.
info If it's an info record, this is the info payload.
sample If it's a sample record, this is the sample value.
iPort If it's a sample record, the port the sample is for (L or R).
Definition at line 199 of file TConsole_TextOut.java.
References TConsole_TextOut.gkRecordTypeInfo, TConsole_TextOut.gkRecordTypeSample, ERecordType.kInfo, and ERecordType.kSample.
Referenced by TConsole_TextOut.Receive(), TConsole_TextOut.Start(), and TConsole_TextOut.Stop().
     {
         String record;
         if (fieldType == ERecordType.kInfo)
         {
             record =
             "{" +
                 "'type':'"  + gkRecordTypeInfo       + "',"  +
                 "'value':'" + info                   + "'"   +
             "}";
         }
         else if (fieldType == ERecordType.kSample)
         {
             record =
             "{" +
                 "'type':'"  + gkRecordTypeSample     + "',"  +
                 "'value':'" + sample                 + "',"  +
                 "'port':'"  + iPort                  + "'"   +
             "}";
         }
         else
         {
             record = "{'type':'null'}";
         }
         System.out.println (record);
     }
void _Register () protected
Definition at line 175 of file TConsole_TextOut.java.
     {
         TController.Register (this);
     }
static final void CreateInstance (String id) static
Creates a new instance of this frontend.
Parameters
id Unique ID as which we register this frontend.
Definition at line 85 of file TConsole_TextOut.java.
References TConsole_TextOut.TConsole_TextOut().
     {
         new TConsole_TextOut (id);
     }
void CreatePort_In (String id)
Definition at line 105 of file TConsole_TextOut.java.
References VAudioProcessor.AddPortIn().
     {
         TConsole_TextOut_Endpoint_In   p;
         p       = new TConsole_TextOut_Endpoint_In (id, this);
         AddPortIn (p);
     }
void OnEvent (int e)
Receive an event with no parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
Implements IEvented.
Definition at line 117 of file TConsole_TextOut.java.
     {
         // TODO Auto-generated method stub
     }
void OnEvent (int e, int arg0)
Receive an event with one in-band integer as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 127 of file TConsole_TextOut.java.
     {
         // TODO Auto-generated method stub
     }
void OnEvent (int e, long arg0)
Receive an event with one in-band long as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 137 of file TConsole_TextOut.java.
     {
         // TODO Auto-generated method stub
     }
void OnEvent (int e, String arg0)
Receive an event with one in-band String as parameter.
Parameters
e ID of the event we send. Must be one of the constants gkEvent... provided here.
arg0 The in-band parameter.
Implements IEvented.
Definition at line 147 of file TConsole_TextOut.java.
     {
         // TODO Auto-generated method stub
     }
void Receive (float sample, int iPort) package
Receives a sample value and prints it to stdout as JSON record.
Parameters
sample The sample value.
iPort Which port the sample value is for.
Definition at line 186 of file TConsole_TextOut.java.
References TConsole_TextOut._PushRecord(), and ERecordType.kSample.
     {
         _PushRecord (ERecordType.kSample, null, sample, iPort);
     }
void Start ()
Starts the module.
Implements IControllable.
Definition at line 157 of file TConsole_TextOut.java.
References TConsole_TextOut._PushRecord(), and ERecordType.kInfo.
     {
         _PushRecord (ERecordType.kInfo, "event_meter_start", 0, 0);
     }
void Stop ()
Stops the module.
Implements IControllable.
Definition at line 166 of file TConsole_TextOut.java.
References TConsole_TextOut._PushRecord(), and ERecordType.kInfo.
     {
         _PushRecord (ERecordType.kInfo, "event_meter_stop", 0, 0);
     }
Member Data Documentation
final String gkRecordTypeInfo = "info" static private
Signifier, info record.
Definition at line 73 of file TConsole_TextOut.java.
Referenced by TConsole_TextOut._PushRecord().
final String gkRecordTypeSample = "sample" static private
Signifier, sample record.
Definition at line 78 of file TConsole_TextOut.java.
Referenced by TConsole_TextOut._PushRecord().
The documentation for this class was generated from the following file:
TConsole_TextOut.java