ppm-java: TAtomicDouble Class Reference
TAtomicDouble Class Reference
An thread safe double value.
Public Member Functions
TAtomicDouble ()
cTor.
double Get ()
void Set (double value)
Sets the value.
Private Member Functions
void _Lock ()
Definitely acquire the lock on the critical section (spin lock, as it's merry-go-round until lock has been acquired).
void _Unlock ()
Definitely release the lock on the critical section (spin lock, as it's merry-go-round until lock has been released).
Private Attributes
AtomicInteger fLock
The lock.
double fValue
The value.
Static Private Attributes
static final int gkLocked = 1
Flag value: A thread acquired the lock.
static final int gkUnlocked = 0
Flag value: Value can be accessed.
Detailed Description
An thread safe double value.
Author
Peter Hoppe
Definition at line 26 of file TAtomicDouble.java.
Constructor & Destructor Documentation
TAtomicDouble ()
cTor.
Definition at line 51 of file TAtomicDouble.java.
References TAtomicDouble.fLock, TAtomicDouble.fValue, and TAtomicDouble.gkUnlocked.
     {
         fLock  = new AtomicInteger (gkUnlocked);
         fValue = 0;
     }
Member Function Documentation
void _Lock () private
Definitely acquire the lock on the critical section (spin lock, as it's merry-go-round until lock has been acquired).
Definition at line 87 of file TAtomicDouble.java.
References TAtomicDouble.gkLocked, and TAtomicDouble.gkUnlocked.
Referenced by TAtomicDouble.Get(), and TAtomicDouble.Set().
     {
         boolean isLocked;
         isLocked = false;
         while (! isLocked)
         {
             isLocked = fLock.compareAndSet (gkUnlocked, gkLocked);
         }
     }
void _Unlock () private
Definitely release the lock on the critical section (spin lock, as it's merry-go-round until lock has been released).
Definition at line 102 of file TAtomicDouble.java.
References TAtomicDouble.gkLocked, and TAtomicDouble.gkUnlocked.
Referenced by TAtomicDouble.Get(), and TAtomicDouble.Set().
     {
         boolean isUnlocked;
         isUnlocked = false;
         while (! isUnlocked)
         {
             isUnlocked = fLock.compareAndSet (gkLocked, gkUnlocked);
         }
     }
double Get ()
Returns
The value.
Definition at line 60 of file TAtomicDouble.java.
References TAtomicDouble._Lock(), TAtomicDouble._Unlock(), and TAtomicDouble.fValue.
Referenced by TGUILinearGauge_Surrogate_Stats_Record.GetDumpStr(), TGUINeedle_Surrogate_Stats_Record.GetDumpStr(), TNodePeakEstimator_Stats.GetDumpStr(), TNodeConverterDb_Stats.GetDumpStr(), TNodeIntegrator_PPMBallistics_Stats.GetDumpStr(), and TNodePPMProcessor_Stats.GetDumpStr().
     {
         double ret;
         _Lock ();
         ret = fValue;
         _Unlock ();
         return ret;
     }
void Set (double value)
Sets the value.
Parameters
value The value.
Definition at line 76 of file TAtomicDouble.java.
References TAtomicDouble._Lock(), TAtomicDouble._Unlock(), and TAtomicDouble.fValue.
     {
         _Lock ();
         fValue = value;
         _Unlock ();
     }
Member Data Documentation
AtomicInteger fLock private
The lock.
Definition at line 41 of file TAtomicDouble.java.
Referenced by TAtomicDouble.TAtomicDouble().
double fValue private
The value.
Definition at line 46 of file TAtomicDouble.java.
Referenced by TAtomicDouble.Get(), TAtomicDouble.Set(), and TAtomicDouble.TAtomicDouble().
final int gkLocked = 1 static private
Flag value: A thread acquired the lock.
Definition at line 31 of file TAtomicDouble.java.
Referenced by TAtomicDouble._Lock(), and TAtomicDouble._Unlock().
final int gkUnlocked = 0 static private
Flag value: Value can be accessed.
Definition at line 36 of file TAtomicDouble.java.
Referenced by TAtomicDouble._Lock(), TAtomicDouble._Unlock(), and TAtomicDouble.TAtomicDouble().
The documentation for this class was generated from the following file:
TAtomicDouble.java