ppm-java: VAudioPort Class Reference
VAudioPort Class Reference abstract
Base class for all audio ports.
Public Member Functions
VAudioPort (String id, VAudioProcessor host)
cTor.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Protected Member Functions
VAudioProcessor _GetHost ()
abstract String _GetType ()
Returns textual information of a concrete child's direct super type.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Private Attributes
VAudioProcessor fHost
The audio processor hosting this port.
Detailed Description
Base class for all audio ports.
An audio port is always associated with a hosting VAudioProcessor.
Author
Peter Hoppe
Definition at line 25 of file VAudioPort.java.
Constructor & Destructor Documentation
VAudioPort (String id, VAudioProcessor host)
cTor.
Parameters
id Unique ID as which we register this port.
host The audio processor hosting this port.
Definition at line 38 of file VAudioPort.java.
References VAudioPort.fHost.
     {
         super (id);
         fHost = host;
     }
Member Function Documentation
VAudioProcessor _GetHost () protected
Returns
The audio processor hosting this port.
Definition at line 48 of file VAudioPort.java.
References VAudioPort.fHost.
Referenced by TNodePeakEstimator_Endpoint_In.ReceivePacket(), TGUILinearGauge_Endpoint_In.ReceiveSample(), TGUINeedle_Endpoint_In.ReceiveSample(), TNodeConverterDb_Endpoint_In.ReceiveSample(), TConsole_TextOut_Endpoint_In.ReceiveSample(), TConsole_LinearGauge_Endpoint_In.ReceiveSample(), and TNodeIntegrator_PPMBallistics_Endpoint_In.ReceiveSample().
     {
         return fHost;
     }
abstract String _GetType () abstract protected
Returns textual information of a concrete child's direct super type.
To accomodate a special case where clients connect incompatible endpoints; We then throw an exception which reports the incompatibility with details about the conflicting types.
If this application remains a Java application we could use Java introspection. However, it's going to be ported to C++, and there we'd have to resort to ominous tricks to get the name of the supertype of a class. It's much more straight forward to provide a short method that returns a string. It's just one of them things saying "ouch"...
Returns
Type information as text
Referenced by VAudioPort_Output._SetTarget_Log().
Member Data Documentation
VAudioProcessor fHost private
The audio processor hosting this port.
Definition at line 30 of file VAudioPort.java.
Referenced by VAudioPort._GetHost(), and VAudioPort.VAudioPort().
The documentation for this class was generated from the following file:
VAudioPort.java