ppm-java: TCommandlineParser Class Reference
TCommandlineParser Class Reference
Bespoke parser for ppm-java commandline options.
Public Member Functions
TCommandlineParser ()
cTor.
TSessionProperties Parse (String[] args)
Parses the given commandline arguments.
Private Member Functions
void _Init ()
Sets up the parsing template and help text.
String _GetHelpText ()
Private Attributes
Options fCommandlineOptions
Commandline option template.
String fHelpText
Help text, when shown.
Static Private Attributes
static final String gkCommandlineSyntax
Commandline syntax explanation, for the help text.
Detailed Description
Bespoke parser for ppm-java commandline options.
Author
Peter Hoppe
Definition at line 34 of file TCommandlineParser.java.
Constructor & Destructor Documentation
TCommandlineParser ()
cTor.
Definition at line 57 of file TCommandlineParser.java.
References TCommandlineParser._Init().
     {
         _Init ();
     }
Member Function Documentation
String _GetHelpText () private
Returns
The help text.
Definition at line 150 of file TCommandlineParser.java.
References TCommandlineParser.fCommandlineOptions, and TCommandlineParser.gkCommandlineSyntax.
Referenced by TCommandlineParser._Init().
     {
         StringWriter        sw;
         PrintWriter         pw;
         StringBuffer        sb;
         HelpFormatter       hf;
         String              ret;
         sw = new StringWriter ();
         pw = new PrintWriter (sw);
         hf = new HelpFormatter ();
         hf.printHelp
         (
             pw,                                 /* writer to which the help will be written */
             80,                                 /* number of characters to be displayed on each line */
             gkCommandlineSyntax,                /* syntax for this application */
             "",                                 /* banner to display at the beginning of the help */
             fCommandlineOptions,                /* Options instance */
             4,                                  /* number of characters of padding to be prefixed to each line */
             4,                                  /* the number of characters of padding to be prefixed to each description line */
             "",                                 /* the banner to display at the end of the help */
             true                                /* whether to print an automatically generated usage statement */
         );
         sb  = sw.getBuffer ();
         ret = sb.toString ();
         return ret;
     }
void _Init () private
Sets up the parsing template and help text.
Definition at line 105 of file TCommandlineParser.java.
References TCommandlineParser._GetHelpText(), TCommandlineParser.fCommandlineOptions, and TCommandlineParser.fHelpText.
Referenced by TCommandlineParser.TCommandlineParser().
     {
         Option                  printHelp;
         Option                  showDebugWindow;
         Option                  logFilePath;
         Option                  uiType;
         Option                  consoleWidth;
         Option                  useDeprecatedPPMProcessor;
         consoleWidth = new Option ("w", "consoleWidth", true, "If guitype is 'consoleLinear': Width of meter in terminal columns.");
         consoleWidth.setRequired (false);
         logFilePath = new Option ("l", "logFile", true, "Path to log file");
         logFilePath.setRequired (false);
         logFilePath.setArgName  ("path");
         logFilePath.setType     (String.class);
         printHelp = new Option ("h", "help", false, "Print this message");
         printHelp.setRequired (false);
         showDebugWindow = new Option ("d",  "debug", false, "Show debug window");
         showDebugWindow.setRequired (false);
         uiType = new Option ("u", "uiType", true, "Which UI to use. Possible values: 'guiRadial', 'guiLinear', 'consoleLinear', 'consoleText'");
         uiType.setRequired (false);
         uiType.setArgName  ("typeID");
         uiType.setType     (String.class);
         useDeprecatedPPMProcessor = new Option ("x", "dPPMProc", false, "Use the deprecated PPM processor. Experimental development stage feature.");
         useDeprecatedPPMProcessor.setRequired (false);
         fCommandlineOptions = new Options ();
         fCommandlineOptions.addOption (printHelp);
         fCommandlineOptions.addOption (showDebugWindow);
         fCommandlineOptions.addOption (logFilePath);
         fCommandlineOptions.addOption (uiType);
         fCommandlineOptions.addOption (consoleWidth);
         fCommandlineOptions.addOption (useDeprecatedPPMProcessor);
         fHelpText = _GetHelpText ();
     }
TSessionProperties Parse (String[] args)
Parses the given commandline arguments.
Show help text if there's a problem with the arguments.
Parameters
args Given commandline arguments.
Returns
The session properties, or null if there's a problem.
Definition at line 69 of file TCommandlineParser.java.
References TCommandlineParser.fCommandlineOptions, and TCommandlineParser.fHelpText.
     {
         boolean                 isOK;
         CommandLineParser       clp;
         CommandLine             cl;
         TSessionProperties      ret;
         /* Parse commandline */
         isOK    = true;
         cl      = null;
         ret     = new TSessionProperties ();
         ret.SetHelpText (fHelpText);
         try
         {
             clp = new DefaultParser ();
             cl  = clp.parse (fCommandlineOptions, args);
         }
         catch (ParseException e)
         {
             isOK = false;
             ret.SetErrorMessage (e.getMessage ());
         }
         /* Parsing complete. Set program properties. */
         if (isOK)
         {
             ret.Set (cl);
             isOK = ret.IsValid ();                                      /* [100] */
         }
         return ret;
     }
Member Data Documentation
Options fCommandlineOptions private
Commandline option template.
Options will be validated against this.
Definition at line 47 of file TCommandlineParser.java.
Referenced by TCommandlineParser._GetHelpText(), TCommandlineParser._Init(), and TCommandlineParser.Parse().
String fHelpText private
Help text, when shown.
Definition at line 52 of file TCommandlineParser.java.
Referenced by TCommandlineParser._Init(), and TCommandlineParser.Parse().
final String gkCommandlineSyntax static private
Initial value:
=
              "java -jar /path/to/ppm.jar [-h | --help] [-d | --debug] [-x | --dPPMProc] "
            + "(-l <path> | --logFile=<path>) (-u <ui_type> | --uiType=<ui_type>) "
            + "(-w <n> | --consoleWidth=<n>)"
Commandline syntax explanation, for the help text.
Definition at line 39 of file TCommandlineParser.java.
Referenced by TCommandlineParser._GetHelpText().
The documentation for this class was generated from the following file:
TCommandlineParser.java