ppm-java: TLogger Class Reference
TLogger Class Reference
The global logger.
Static Public Member Functions
static void CreateInstance ()
Creates a global logger.
static void CreateInstance (String filePath)
Creates a global logger.
static void LogError (String msg, Object source, String method)
Logs a fatal error.
static void LogMessage (String msg)
Logs an info message.
static void LogMessage (String msg, Object source)
Logs an info message.
static void LogMessage (String msg, Object source, String method)
Logs an info message.
static void LogWarning (String msg)
Logs a warning message.
static void LogWarning (String msg, Object source)
Logs a warning message.
static void LogWarning (String msg, Object source, String method)
Logs a warning message.
Private Member Functions
TLogger ()
cTor.
TLogger (String filePath)
cTor.
void _Init (ELogTarget target, String filePath)
Does any necessary setup work.
void _Log (String msg, ELogLevel lv, Object source, String method)
Writes a log entry.
Private Attributes
Logger fLogger
In the background we use the java logging API.
Static Private Attributes
static TLogger gLogger = null
The logger singleton.
Detailed Description
The global logger.
Logs all messages to a file or to stdout. Access via static methods only.
Author
Peter Hoppe
Definition at line 32 of file TLogger.java.
Constructor & Destructor Documentation
TLogger () private
cTor.
Log messages will end up on stdout.
Definition at line 149 of file TLogger.java.
References TLogger._Init(), and ELogTarget.kStdOut.
Referenced by TLogger.CreateInstance().
     {
         _Init (ELogTarget.kStdOut, null);
     }
TLogger (String filePath) private
cTor.
Log messages will be written to a log file.
Parameters
filePath The log file's path.
Definition at line 159 of file TLogger.java.
References TLogger._Init(), and ELogTarget.kFile.
     {
         _Init (ELogTarget.kFile, filePath);
     }
Member Function Documentation
void _Init (ELogTarget target, String filePath) private
Does any necessary setup work.
Parameters
target The target to send log messages to.
filePath The log file to write to, if target is ELogTarget#kFile. Otherwise ignored.
Definition at line 171 of file TLogger.java.
References TLogger.fLogger, and ELogTarget.kFile.
Referenced by TLogger.TLogger().
     {
         Logger                          rootLogger;
         Handler[]                       handlers;
         int                             i;
         int                             nHandlers;
         Handler                         cH;
         FileHandler                     fH;
         SimpleFormatter                 sF;
         if (target == ELogTarget.kFile)
         {
             /* Remove console handlers; we write log entries to a log file */
             rootLogger = Logger.getLogger ("");
             handlers   = rootLogger.getHandlers ();
             nHandlers  = handlers.length;
             if (nHandlers >= 1)
             {
                 for (i = 0; i < nHandlers; i++)
                 {
                     cH = handlers [i];
                     if (cH instanceof ConsoleHandler)
                     {
                         rootLogger.removeHandler (cH);
                     }
                 }
             }
             try
             {
                 sF = new SimpleFormatter ();
                 fH = new FileHandler (filePath);
                 fH.setFormatter (sF);
                 fLogger = Logger.getLogger (Logger.GLOBAL_LOGGER_NAME);
                 fLogger.addHandler (fH);
             }
             catch (SecurityException | IOException e)
             {
                 e.printStackTrace();
             }
         }
         else
         {
             fLogger = Logger.getGlobal ();
         }
     }
void _Log (String msg, ELogLevel lv, Object source, String method) private
Writes a log entry.
Depending on the log target, the message will either be written to a log file or to stdout/stderr.
Parameters
msg The message to log
lv The log level
source Name of the class from which the log entry originates.
method Name of the method from which the log entry originates.
Definition at line 227 of file TLogger.java.
     {
         String      src;
         String      m;
         String      dtime;
         src = "";
         if (source != null)
         {
             src = source.getClass ().getCanonicalName ();
         }
         if (method != null)
         {
             src += "::" + method;
         }
         dtime = new Date().toString ();
         m     = dtime + ": " + src + ": " + msg;
         switch (lv)
         {
             case kError:
                 fLogger.severe (m);
                 break;
             case kMessage:
                 fLogger.info (m);
                 break;
             case kWarn:
                 fLogger.warning (m);
                 break;
             default:
                 fLogger.info (m);
         }
     }
static void CreateInstance () static
Creates a global logger.
That one writes to stdout.
Definition at line 37 of file TLogger.java.
References TLogger.gLogger, and TLogger.TLogger().
     {
         if (gLogger == null)
         {
             gLogger = new TLogger ();
         }
     }
static void CreateInstance (String filePath) static
Creates a global logger.
That one writes to a file.
Parameters
filePath Log file path.
Definition at line 50 of file TLogger.java.
References TLogger.gLogger, and TLogger.TLogger().
     {
         if (gLogger == null)
         {
             gLogger = new TLogger (filePath);
         }
     }
static void LogError (String msg, Object source, String method) static
Logs a fatal error.
Parameters
msg The error message.
source Object of which class the log was coming from.
method In which method did the error occur.
Definition at line 70 of file TLogger.java.
References ELogLevel.kError.
     {
         gLogger._Log (msg, ELogLevel.kError, source, method);
     }
static void LogMessage (String msg) static
Logs an info message.
Parameters
msg The message.
Definition at line 80 of file TLogger.java.
References ELogLevel.kMessage.
     {
         gLogger._Log (msg, ELogLevel.kMessage, null, null);
     }
static void LogMessage (String msg, Object source) static
Logs an info message.
Parameters
msg The message.
source Object of which class the log was coming from.
Definition at line 91 of file TLogger.java.
References ELogLevel.kMessage.
     {
         gLogger._Log (msg, ELogLevel.kMessage, source, null);
     }
static void LogMessage (String msg, Object source, String method) static
Logs an info message.
Parameters
msg The message.
source Object of which class the log was coming from.
method In which method did the error occur.
Definition at line 103 of file TLogger.java.
References ELogLevel.kMessage.
     {
         gLogger._Log (msg, ELogLevel.kMessage, source, method);
     }
static void LogWarning (String msg) static
Logs a warning message.
Parameters
msg The message.
Definition at line 113 of file TLogger.java.
References ELogLevel.kWarn.
     {
         gLogger._Log (msg, ELogLevel.kWarn, null, null);
     }
static void LogWarning (String msg, Object source) static
Logs a warning message.
Parameters
msg The message.
source Object of which class the log was coming from.
Definition at line 124 of file TLogger.java.
References ELogLevel.kWarn.
     {
         gLogger._Log (msg, ELogLevel.kWarn, source, null);
     }
static void LogWarning (String msg, Object source, String method) static
Logs a warning message.
Parameters
msg The message.
source Object of which class the log was coming from.
method In which method did the error occur.
Definition at line 136 of file TLogger.java.
References ELogLevel.kWarn.
     {
         gLogger._Log (msg, ELogLevel.kWarn, source, method);
     }
Member Data Documentation
Logger fLogger private
In the background we use the java logging API.
Definition at line 144 of file TLogger.java.
Referenced by TLogger._Init().
TLogger gLogger = null static private
The logger singleton.
Definition at line 61 of file TLogger.java.
Referenced by TLogger.CreateInstance().
The documentation for this class was generated from the following file:
TLogger.java