ppm-java: TAudioContext_JackD Class Reference
TAudioContext_JackD Class Reference
Audio driver for the JackD server.
Public Member Functions
void CreatePort_Out (String id)
int GetSampleRate ()
boolean IsWorking ()
void process (JJackAudioEvent e)
void Start ()
Starts the module.
TAudioContext_JackD_Stats StatsGet ()
void Stop ()
Stops the module.
Public Member Functions inherited from VAudioDriver
VAudioDriver (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
final void CreatePort_In (String id)
Public Member Functions inherited from VAudioProcessor
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
abstract void CreatePort_In (String id)
Creates an input port.
abstract void CreatePort_Out (String id)
Creates an output port.
int GetNumPortsIn ()
int GetNumPortsOut ()
VAudioPort GetPortIn (int i)
Returns the ith input port.
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static void CreateInstance (String idClient, int nMaxChanIn, int nMaxChanOut)
Creates the JackD audio driver instance.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VAudioProcessor
void AddPortIn (VAudioPort_Input p)
Adds a new input port.
void AddPortOut (VAudioPort_Output p)
Adds a new output port.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Private Member Functions
TAudioContext_JackD (String idClient, int nMaxChanIn, int nMaxChanOut)
cTor.
void _LoadDriver ()
Loads and initializes the JackD driver.
void _ProcessInputs (JJackAudioEvent e)
Processes data ready to be sent to the Jack driver i.e.
void _ProcessOutputs (JJackAudioEvent e)
Processes data ready to be retrieved from the Jack driver i.e.
void _StopDriver ()
Stops the JackD driver.
Private Attributes
boolean fIsWorking
true if this driver is in working order, i.e.
int fSampleRate
Sample rate (samp/sec) as determined by the running instance of JackD.
TAudioContext_JackD_Stats fStats
Runtime statistics for diagnostic and debugging purposes.
Static Private Attributes
static TAudioContext_JackD gContext = null
The JackD driver singleton.
Detailed Description
Audio driver for the JackD server.
Author
Peter Hoppe
Definition at line 36 of file TAudioContext_JackD.java.
Constructor & Destructor Documentation
TAudioContext_JackD (String idClient, int nMaxChanIn, int nMaxChanOut) private
cTor.
Creates a new instance and registers it with the global TRegistry under the given id.
Parameters
idClient Unique ID as which the JackD driver's instance can be accessed in the global Registry.
nMaxChanIn Maximum number of input channels. Specify -1 for: No limit.
nMaxChanOut Maximum number of output channels. Specify -1 for: No limit.
See Also
TRegistry
Definition at line 96 of file TAudioContext_JackD.java.
References TAudioContext_JackD.fIsWorking, TAudioContext_JackD.fSampleRate, and TAudioContext_JackD.fStats.
Referenced by TAudioContext_JackD.CreateInstance().
     {
         super (idClient, nMaxChanIn, nMaxChanOut);                      /* [110] */
         TLogger.LogMessage ("Creating JackD bridge (singleton)", this, "cTor ('" + idClient + ")");
         fStats          = new TAudioContext_JackD_Stats (this);
         fSampleRate     = -1;
         fIsWorking      = false;
         TController.StatAddProvider (this);
     }
Member Function Documentation
void _LoadDriver () private
Loads and initializes the JackD driver.
Definition at line 183 of file TAudioContext_JackD.java.
References TAudioContext_JackD.fIsWorking, TAudioContext_JackD.fSampleRate, VBrowseable.GetID(), VAudioProcessor.GetNumPortsIn(), and VAudioProcessor.GetNumPortsOut().
Referenced by TAudioContext_JackD.Start().
     {
         String  idClient;
         int     nPortsIn;
         int     nPortsOut;
         int     nPorts;
         idClient    = GetID ();
         nPortsIn    = GetNumPortsIn ();
         nPortsOut   = GetNumPortsOut ();
         nPorts      = nPortsIn + nPortsOut;
         /* Setting properties for the underlying JJack framework.      */
         System.setProperty ("jjack.client.name",                    idClient);
         System.setProperty ("jjack.ports",                          Integer.toString (nPorts));
         System.setProperty ("jjack.ports.in",                       Integer.toString (nPortsOut));
         System.setProperty ("jjack.ports.out",                      Integer.toString (nPortsIn));
         System.setProperty ("jjack.ports.autoconnect",              Boolean.toString (false));
         System.setProperty ("jjack.ports.input.autoconnect",        Boolean.toString (false));
         System.setProperty ("jjack.ports.output.autoconnect",       Boolean.toString (false));
         TLogger.LogMessage ("Loading JackD audio bridge.", this, "_LoadDriver ()");
         /* Dummy call to load JJack driver. JJackSystem has a static
          * block at the beginning which loads the JNI system library */
         JJackSystem.class.getName ();
         fIsWorking  = JJackSystem.isInitialized ();
         if (fIsWorking)
         {
             fSampleRate = JJackSystem.getSampleRate ();
             /* Plug this instance into JackD. From now on process(JJackAudioEvent)
              * will be called by JackD, in regular intervals. */
             TLogger.LogMessage ("Activating JackD driver.", this, "_LoadDriver");
             TLogger.LogMessage (JJackSystem.getInfo ());
             JJackSystem.setProcessor (this);
         }
         else
         {
             TLogger.LogError ("JackD driver did not load successfully", this, "_LoadDriver");
         }
     }
void _ProcessInputs (JJackAudioEvent e) private
Processes data ready to be sent to the Jack driver i.e.
towards the JackD server). This sounds paradox, but we define ports as INPUTS which receive data from our program and send it to the JackD server.
We use a very crude overflow protection - this saves us lots of code which has to deal with exceptions, resp. loop over the buffered samples etc. This is time critical data handling, therefore we want to keep it as simple as possible.
The client program is responsible to ensure that data frames don't exceed the prescribed buffer length.
Parameters
e The handle allowing access to the input buffers.
Definition at line 241 of file TAudioContext_JackD.java.
References VAudioProcessor.GetNumPortsIn(), and VAudioProcessor.GetPortIn().
Referenced by TAudioContext_JackD.process().
     {
         TAudioContext_Endpoint_In    portIn;
         int                             nPorts;
         int                             i;
         int                             nSampIn;
         int                             nSampOut;
         FloatBuffer                     bIn;
         FloatBuffer                     bOut;
         nPorts = GetNumPortsIn ();
         if (nPorts >= 1)
         {
             for (i = 0; i < nPorts; i++)
             {
                 portIn      = (TAudioContext_Endpoint_In) GetPortIn (i);
                 bIn         = portIn.FetchPacket ();
                 bOut        = e.getOutput (i);
                 nSampIn     = bIn.capacity ();
                 nSampOut    = bOut.capacity ();
                 /* [100] */
                 if (nSampIn <= nSampOut)
                 {
                     bOut.put (bIn);
                 }
             }
         }
     }
void _ProcessOutputs (JJackAudioEvent e) private
Processes data ready to be retrieved from the Jack driver i.e.
away from the JackD server and towards the client program. This sounds paradox, but we define ports as OUTPUTS which receive data from the JackD server and send it to the client program.
Parameters
e The handle allowing access to the output buffers.
Definition at line 279 of file TAudioContext_JackD.java.
References VAudioProcessor.GetNumPortsOut(), and VAudioProcessor.GetPortOut().
Referenced by TAudioContext_JackD.process().
     {
         TAudioContext_Endpoint_Out   portOut;
         int                             nPorts;
         int                             i;
         FloatBuffer                     b;
         nPorts = GetNumPortsOut ();
         if (nPorts >= 1)
         {
             for (i = 0; i < nPorts; i++)
             {
                 portOut = (TAudioContext_Endpoint_Out) GetPortOut (i);
                 b       = e.getInput (i);
                 portOut.PushPacket (b);
             }
         }
     }
void _Register () protected
Definition at line 175 of file TAudioContext_JackD.java.
     {
         TController.Register (this);
     }
void _StopDriver () private
Stops the JackD driver.
Definition at line 301 of file TAudioContext_JackD.java.
Referenced by TAudioContext_JackD.Stop().
     {
         try
         {
             TLogger.LogMessage ("Stopping JackD driver", this, "Stop ()");
             JJackSystem.shutdown ();
         }
         catch (JJackException e)
         {
             TLogger.LogError ("Exception during Jack bridge shutdown: " + e.getMessage (), this, "Stop ()");
             e.printStackTrace();
         }
     }
static void CreateInstance (String idClient, int nMaxChanIn, int nMaxChanOut) static
Creates the JackD audio driver instance.
Must only be called once.
Parameters
idClient Unique ID as which the JackD driver's instance can be accessed in the global Registry.
nMaxChanIn Maximum number of input channels. Specify -1 for: No limit.
nMaxChanOut Maximum number of output channels. Specify -1 for: No limit.
Exceptions
IllegalStateException If this method has been called before.
See Also
TRegistry#GetAudioDriver(), TRegistry#GetObject(String)
Definition at line 57 of file TAudioContext_JackD.java.
References TAudioContext_JackD.gContext, and TAudioContext_JackD.TAudioContext_JackD().
     {
         if (gContext != null)
         {
             throw new IllegalStateException ("TAudioContext_JackD is already instantiated.");
         }
         gContext = new TAudioContext_JackD (idClient, nMaxChanIn, nMaxChanOut);
     }
void CreatePort_Out (String id)
Definition at line 111 of file TAudioContext_JackD.java.
References VAudioProcessor.AddPortOut().
     {
         TAudioContext_Endpoint_Out       p;
         p = new TAudioContext_Endpoint_Out (id, this);
         AddPortOut (p);
     }
int GetSampleRate ()
Returns
The sample rate (in samples / sec) during this session.
Definition at line 122 of file TAudioContext_JackD.java.
References TAudioContext_JackD.fSampleRate.
     {
         return fSampleRate;
     }
boolean IsWorking ()
Returns
true if the underlying JackD driver has loaded successfully and can thus be used, false otherwise.
Definition at line 131 of file TAudioContext_JackD.java.
References TAudioContext_JackD.fIsWorking.
Referenced by TAudioContext_JackD_Stats.GetDumpStr().
     {
         return fIsWorking;
     }
void process (JJackAudioEvent e)
Definition at line 140 of file TAudioContext_JackD.java.
References TAudioContext_JackD._ProcessInputs(), and TAudioContext_JackD._ProcessOutputs().
     {
         _ProcessOutputs (e);
         _ProcessInputs (e);
     }
void Start ()
Starts the module.
Implements IControllable.
Definition at line 149 of file TAudioContext_JackD.java.
References TAudioContext_JackD._LoadDriver().
     {
         _LoadDriver ();
     }
TAudioContext_JackD_Stats StatsGet ()
Returns
The current runtime statistics.
Implements IStatEnabled.
Definition at line 157 of file TAudioContext_JackD.java.
References TAudioContext_JackD.fStats.
     {
         return fStats;
     }
void Stop ()
Stops the module.
Implements IControllable.
Definition at line 166 of file TAudioContext_JackD.java.
References TAudioContext_JackD._StopDriver().
     {
         _StopDriver ();
     }
Member Data Documentation
boolean fIsWorking private
true if this driver is in working order, i.e.
ready to connect to a client.
Read-only access via IsWorking().
Definition at line 71 of file TAudioContext_JackD.java.
Referenced by TAudioContext_JackD._LoadDriver(), TAudioContext_JackD.IsWorking(), and TAudioContext_JackD.TAudioContext_JackD().
int fSampleRate private
Sample rate (samp/sec) as determined by the running instance of JackD.
Read-only access via GetSampleRate().
Definition at line 77 of file TAudioContext_JackD.java.
Referenced by TAudioContext_JackD._LoadDriver(), TAudioContext_JackD.GetSampleRate(), and TAudioContext_JackD.TAudioContext_JackD().
TAudioContext_JackD_Stats fStats private
Runtime statistics for diagnostic and debugging purposes.
Definition at line 82 of file TAudioContext_JackD.java.
Referenced by TAudioContext_JackD.StatsGet(), and TAudioContext_JackD.TAudioContext_JackD().
TAudioContext_JackD gContext = null static private
The JackD driver singleton.
Definition at line 43 of file TAudioContext_JackD.java.
Referenced by TAudioContext_JackD.CreateInstance().
The documentation for this class was generated from the following file:
TAudioContext_JackD.java