ppm-java: VAudioProcessor Class Reference
VAudioProcessor Class Reference abstract
Base class for all modules processing audio samples.
Public Member Functions
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
abstract void CreatePort_In (String id)
Creates an input port.
abstract void CreatePort_Out (String id)
Creates an output port.
int GetNumPortsIn ()
int GetNumPortsOut ()
VAudioPort GetPortIn (int i)
Returns the ith input port.
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Protected Member Functions
void AddPortIn (VAudioPort_Input p)
Adds a new input port.
void AddPortOut (VAudioPort_Output p)
Adds a new output port.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Private Attributes
TArrayMap< VAudioPort_Input > fPortsIn
Input ports.
TArrayMap< VAudioPort_Output > fPortsOut
Output ports.
Detailed Description
Base class for all modules processing audio samples.
An audio processor can have any number of inputs and any number of outputs.
Mostly, an audio processor receives sample data from its input ports, does some work with the sample data and pushes the result to its output ports. Some audio processors only receive data (e.g. VFrontend), some others only send data (e.g. VAudioDriver).
Processing is normally driven from the input side - whenever data is pushed to the inputs, they will push the data on to the processor which will then do the processing with the data and then push the result to its outputs. There are exceptions, for example an audio driver receives sample data from an external source and pushes the data on to its outputs at the appropriate time.
This class does all the admin related to input and output ports. Port objects can be accessed by index or by key. Index based access is useful a client wishes to enumerate all ports.
Author
Peter Hoppe
Definition at line 46 of file VAudioProcessor.java.
Constructor & Destructor Documentation
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
Parameters
id The unique ID under which we register this object with the registry.
nMaxChanIn Maximum number of input channels. Specify -1 for: No limit.
nMaxChanOut Maximum number of output channels. Specify -1 for: No limit.
Definition at line 68 of file VAudioProcessor.java.
References VAudioProcessor.fPortsIn, and VAudioProcessor.fPortsOut.
     {
         super (id);
         fPortsIn    = new TArrayMap<> (nMaxChanIn);
         fPortsOut   = new TArrayMap<> (nMaxChanOut);
     }
Member Function Documentation
void AddPortIn (VAudioPort_Input p) protected
Adds a new input port.
Parameters
p The input port added.
Definition at line 181 of file VAudioProcessor.java.
Referenced by TNodePeakEstimator.CreatePort_In(), TGUILinearGauge_Surrogate.CreatePort_In(), TNodeConverterDb.CreatePort_In(), TGUINeedle_Surrogate.CreatePort_In(), TConsole_TextOut.CreatePort_In(), TNodeIntegrator_PPMBallistics.CreatePort_In(), TNodePump.CreatePort_In(), TConsole_LinearGauge.CreatePort_In(), and TNodePPMProcessor.CreatePort_In().
     {
         String key;
         key = p.GetID ();
         fPortsIn.Set (key, p);
     }
void AddPortOut (VAudioPort_Output p) protected
Adds a new output port.
Parameters
p The output port added.
Definition at line 194 of file VAudioProcessor.java.
Referenced by TNodePeakEstimator.CreatePort_Out(), TNodeConverterDb.CreatePort_Out(), TAudioContext_JackD.CreatePort_Out(), TNodeIntegrator_PPMBallistics.CreatePort_Out(), TNodePump.CreatePort_Out(), and TNodePPMProcessor.CreatePort_Out().
     {
         String key;
         key = p.GetID ();
         fPortsOut.Set (key, p);
     }
abstract void CreatePort_In (String id) abstract
Creates an input port.
It's up to the concrete implementation to provide the input port class.
Parameters
id Unique ID under which we register the new input port.
abstract void CreatePort_Out (String id) abstract
Creates an output port.
It's up to the concrete implementation to provide the output port class.
Parameters
id Unique ID under which we register the new output port.
int GetNumPortsIn ()
Returns
The number of input ports.
Definition at line 95 of file VAudioProcessor.java.
Referenced by TAudioContext_JackD._LoadDriver(), and TAudioContext_JackD._ProcessInputs().
     {
         int ret;
         ret = fPortsIn.GetNumElements ();
         return ret;
     }
int GetNumPortsOut ()
Returns
The number of output ports.
Definition at line 107 of file VAudioProcessor.java.
Referenced by TAudioContext_JackD._LoadDriver(), and TAudioContext_JackD._ProcessOutputs().
     {
         int ret;
         ret = fPortsOut.GetNumElements ();
         return ret;
     }
VAudioPort GetPortIn (int i)
Returns the ith input port.
Parameters
i Zero based index of the requested port.
Returns
Input port [i].
Definition at line 122 of file VAudioProcessor.java.
Referenced by TNodePPMProcessor._CompensateCongestions(), TNodePump._Initialize(), TNodePPMProcessor._ProcessChunk(), TAudioContext_JackD._ProcessInputs(), and TAudioContext_JackD_Stats.GetDumpStr().
     {
         VAudioPort ret;
         ret = fPortsIn.Get (i);
         return ret;
     }
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
Parameters
key Unique ID of the requested port.
Returns
Input port [key].
Definition at line 137 of file VAudioProcessor.java.
     {
         VAudioPort_Input ret;
         ret = fPortsIn.Get (key);
         return ret;
     }
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
Parameters
i Zero based index of the requested port.
Returns
Output port [i].
Definition at line 152 of file VAudioProcessor.java.
Referenced by TNodePump._Initialize(), TNodePPMProcessor._ProcessChunk(), TAudioContext_JackD._ProcessOutputs(), TAudioContext_JackD_Stats.GetDumpStr(), TNodeConverterDb.Receive(), TNodePeakEstimator.ReceivePacket(), and TNodeIntegrator_PPMBallistics.SetRef().
     {
         VAudioPort_Output ret;
         ret = fPortsOut.Get (i);
         return ret;
     }
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Parameters
key Unique ID of the requested port.
Returns
Output port [key].
Definition at line 167 of file VAudioProcessor.java.
     {
         VAudioPort_Output ret;
         ret = fPortsOut.Get (key);
         return ret;
     }
Member Data Documentation
TArrayMap<VAudioPort_Input> fPortsIn private
Input ports.
Definition at line 51 of file VAudioProcessor.java.
Referenced by VAudioProcessor.VAudioProcessor().
TArrayMap<VAudioPort_Output> fPortsOut private
Output ports.
Definition at line 56 of file VAudioProcessor.java.
Referenced by VAudioProcessor.VAudioProcessor().
The documentation for this class was generated from the following file:
VAudioProcessor.java