ppm-java: TMain Class Reference
TMain Class Reference
Main class.
Static Public Member Functions
static void main (String[] args)
Application entry point.
Private Member Functions
TMain (String[] args)
cTor.
void _Init (String[] args)
Initializer.
Private Attributes
TSessionProperties fSessionProps
Properties for the current session.
TSetup fSetupAgent
The setup executor.
Detailed Description
Main class.
Sets up the streaming apparatus. We use a very modular design connecting various modules. Since this is a concept test we have the freedom to try various designs and study the behaviour.
Lightweight modules
A group of modules, each having a very limited functionality, connected to form a complex apparatus. This is the current design.
Monolithic module
The entire PPM processor is one monolithic block performing the whole data processing from raw audio samples to GUI ready peak value stream. Now deprecated, but kept for education purposes.
The lighweight module design has the advantage of high flexibility as it's fairly inexpensive to create new kinds of modules (e.g. a history view showing the last minute of metering data). It comes at a price of multiple data copying between some modules and some boilerplate code and modules with trivial functionality (e.g. the peak estimator). However, the flexibility trumps, as it makes the design much more scalable.
Author
Peter Hoppe
Definition at line 50 of file TMain.java.
Constructor & Destructor Documentation
TMain (String[] args) private
cTor.
Parameters
args Commandline arguments. See user documentation.
Definition at line 77 of file TMain.java.
References TMain._Init().
Referenced by TMain.main().
     {
         _Init (args);
     }
Member Function Documentation
void _Init (String[] args) private
Initializer.
Sets up the session according to the commandline args and starts all the modules.
Parameters
args Commandline arguments. See user documentation.
Definition at line 87 of file TMain.java.
References TMain.fSessionProps, TMain.fSetupAgent, and TSessionProperties.GetHelpText().
Referenced by TMain.TMain().
     {
         TCommandlineParser          cp;
         boolean                     isValid;
         String                      errMsg;
         cp            = new TCommandlineParser ();
         fSessionProps = cp.Parse (args);
         isValid       = fSessionProps.IsValid ();
         if (isValid)
         {
             fSetupAgent = new TSetup ();
             fSetupAgent.ExecuteWith (fSessionProps);
         }
         else
         {
             errMsg = fSessionProps.GetErrorMessage () + "\n" +
                      "-----------------------------------------------------------------\n" +
                      fSessionProps.GetHelpText ();
             throw new IllegalArgumentException (errMsg);
         }
     }
static void main (String[] args) static
Application entry point.
Parameters
args Commandline arguments. See user documentation.
Definition at line 57 of file TMain.java.
References TMain.TMain().
     {
         new TMain (args);
     }
Member Data Documentation
TSessionProperties fSessionProps private
Properties for the current session.
Definition at line 65 of file TMain.java.
Referenced by TMain._Init().
TSetup fSetupAgent private
The setup executor.
Definition at line 70 of file TMain.java.
Referenced by TMain._Init().
The documentation for this class was generated from the following file:
TMain.java