ppm-java: TDev_Trial_ReadWrite_FloatBuffer_01 Class Reference
TDev_Trial_ReadWrite_FloatBuffer_01 Class Reference
Trial: FloatBuffer: Write -> Flip -> Read.
Static Public Member Functions
static void main (String[] args)
Static Private Member Functions
static void _Test_01 ()
static void _DumpDetails (FloatBuffer fb)
Detailed Description
Trial: FloatBuffer: Write -> Flip -> Read.
Definition at line 23 of file TDev_Trial_ReadWrite_FloatBuffer_01.java.
Member Function Documentation
static void _DumpDetails (FloatBuffer fb) static private
Definition at line 74 of file TDev_Trial_ReadWrite_FloatBuffer_01.java.
Referenced by TDev_Trial_ReadWrite_FloatBuffer_01._Test_01().
     {
         int     i;
         int     n;
         float   x;
         System.out.println ("--------------------------------------------------------------------------------------------");
         System.out.println ("position: " + fb.position () + ", limit: " + fb.limit () + ", capacity: " + fb.capacity ());
         n = fb.capacity ();
         for (i = 0; i < n; i++)
         {
             x = fb.get (i);
             System.out.println (i + " -> " + x);
         }
     }
static void _Test_01 () static private
Definition at line 33 of file TDev_Trial_ReadWrite_FloatBuffer_01.java.
References TDev_Trial_ReadWrite_FloatBuffer_01._DumpDetails().
Referenced by TDev_Trial_ReadWrite_FloatBuffer_01.main().
     {
         final int               kNRuns = 10;
         int                     i;
         FloatBuffer             fb;
         fb = FloatBuffer.allocate (12);
         _DumpDetails (fb);
         for (i = 0; i < kNRuns; i++)
         {
             fb.put (i);
             _DumpDetails (fb);
         }
         System.out.println ("============================================================================================");
         System.out.println ("fb->flip()");
         fb.flip ();
         try
         {
             _DumpDetails (fb);
         }
         catch (Exception e)
         {
             System.out.println (e.getMessage ());
             e.printStackTrace ();
         }
         System.out.println ("============================================================================================");
         System.out.println ("fb->flip()");
         fb.flip ();
         try
         {
             _DumpDetails (fb);
         }
         catch (Exception e)
         {
             System.out.println (e.getMessage ());
             e.printStackTrace ();
         }
     }
static void main (String[] args) static
Definition at line 25 of file TDev_Trial_ReadWrite_FloatBuffer_01.java.
References TDev_Trial_ReadWrite_FloatBuffer_01._Test_01().
     {
         _Test_01 ();
     }
The documentation for this class was generated from the following file:
TDev_Trial_ReadWrite_FloatBuffer_01.java