ppm-java: TConsole_LinearGauge Class Reference
TConsole_LinearGauge Class Reference
A linear gauge on the console.
Public Member Functions
TConsole_LinearGauge (String id, int barLen)
cTor.
void CreatePort_In (String id)
void Start ()
Starts the module.
void Stop ()
Stops the module.
Public Member Functions inherited from VFrontend
VFrontend (String id, int nMaxChanIn)
final void CreatePort_Out (String id)
Public Member Functions inherited from VAudioProcessor
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
abstract void CreatePort_In (String id)
Creates an input port.
abstract void CreatePort_Out (String id)
Creates an output port.
int GetNumPortsIn ()
int GetNumPortsOut ()
VAudioPort GetPortIn (int i)
Returns the ith input port.
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static void CreateInstance (String id, int widthCols)
Creates a new instance of this frontend.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VFrontend
void _OnTerminate ()
Handler for: Frontend terminated.
Protected Member Functions inherited from VAudioProcessor
void AddPortIn (VAudioPort_Input p)
Adds a new input port.
void AddPortOut (VAudioPort_Output p)
Adds a new output port.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Package Functions
void _Receive (float level, int iChannel)
Receives a level update on the given channel.
Static Package Attributes
static final int gkNumSections = 7
Number of sections (PPM has seven).
Private Member Functions
void _Init (int barLen)
initializes the UI - sanitized the bar length and prepares all pre cached decorations.
void _RefreshFrame ()
Redraws the UI - worker method.
void _RefreshUI ()
If the refresh timer has expired: Redraws the UI and restarts the timer [110].
Private Attributes
int fBarLen
Length of gauge after sanitization.
String fEmptyBar
Pre cached bar with decorations.
String fFramebar
Pre cached outer bar.
TConsole_LinearGauge_MeterUI fMeterL
UI for meter itself, left channel.
TConsole_LinearGauge_MeterUI fMeterR
UI for meter itself, right channel.
String fNumBar
pre cached PPM divisions, numbers.
int fNumColsPerSection
Width of each section, in characters.
TTickTimer fRefreshTimer
Timer to redraw the UI [110].
Static Private Attributes
static final String gkAnsiCursorPosBottom = "\u001B[7;1H"
Ansi control sequence: Position cursor at the bottom of the gauge.
static final String gkAnsiCursorPosTop = "\u001B[1;1H"
Ansi control sequence: Position cursor at the top of the gauge.
static final String gkAnsiCursorPosMeterL = "\u001B[2;1H"
Ansi control sequence: Position cursor at the left of the left channel bar.
static final String gkAnsiCursorPosMeterR = "\u001B[4;1H"
Ansi control sequence: Position cursor at the left of the right channel bar.
static final String gkAnsiScreenClear = "\u001B[2J"
Ansi control sequence: Clear the screen.
static final int gkBarLenMax = 280
Maximum allowed width of gauge, in characters.
static final int gkBarLenMin = 14
Minimum allowed width of gauge, in characters.
static final long gkRefreshInterval = 2000
Interval [ms] to refresh (redraw) the UI [110].
static final String gkTickmarkChar = "|"
Character used for the tick marks.
Detailed Description
A linear gauge on the console.
Author
Peter Hoppe
Definition at line 28 of file TConsole_LinearGauge.java.
Constructor & Destructor Documentation
TConsole_LinearGauge (String id, int barLen)
cTor.
Parameters
id Unique ID as which we register this frontend.
barLen Length of gauge on screen (in columns)
Definition at line 140 of file TConsole_LinearGauge.java.
References TConsole_LinearGauge._Init(), TConsole_LinearGauge.fBarLen, TConsole_LinearGauge.fMeterL, TConsole_LinearGauge.fMeterR, TConsole_LinearGauge.fRefreshTimer, and TConsole_LinearGauge.gkRefreshInterval.
Referenced by TConsole_LinearGauge.CreateInstance().
     {
         super (id, 2);
         _Init (barLen);
         fMeterL             = new TConsole_LinearGauge_MeterUI (fBarLen);
         fMeterR             = new TConsole_LinearGauge_MeterUI (fBarLen);
         fRefreshTimer       = new TTickTimer                   (gkRefreshInterval);
     }
Member Function Documentation
void _Init (int barLen) private
initializes the UI - sanitized the bar length and prepares all pre cached decorations.
Parameters
barLen The bar length to be used. Will be sanitized: Bar length limited to given boundaries, gkBarLenMin and gkBarLenMax, and divisible by gkNumSections.
Definition at line 225 of file TConsole_LinearGauge.java.
References TConsole_LinearGauge.fBarLen, TConsole_LinearGauge.fEmptyBar, TConsole_LinearGauge.fFramebar, TConsole_LinearGauge.fNumBar, TConsole_LinearGauge.fNumColsPerSection, TConsole_LinearGauge.gkBarLenMax, TConsole_LinearGauge.gkBarLenMin, TConsole_LinearGauge.gkNumSections, and TConsole_LinearGauge.gkTickmarkChar.
Referenced by TConsole_LinearGauge.TConsole_LinearGauge().
     {
         int             i;
         String          spaces;
         /* Set bar length to sane value. Bar length must be divisable by gkNumSections */
         if (barLen < gkBarLenMin)
         {
             fBarLen = gkBarLenMin;
         }
         else if (barLen > gkBarLenMax)
         {
             fBarLen = gkBarLenMax;
         }
         else
         {
             fBarLen = gkNumSections * (barLen / gkNumSections);         /* [100] */
         }
         fNumColsPerSection = fBarLen / gkNumSections;
         /* Precompute fixed frame elements */
         spaces = "";
         for (i = 1; i <= fNumColsPerSection-1; i++)
         {
             spaces += " ";
         }
         fFramebar = gkTickmarkChar;
         for (i = 1; i <= gkNumSections; i++)
         {
             fFramebar += spaces + gkTickmarkChar;
         }
         fNumBar = "0";
         for (i = 1; i <= gkNumSections; i++)
         {
             fNumBar += spaces + i;
         }
         fEmptyBar = "";
         for (i = 1; i <= fBarLen; i++)
         {
             fEmptyBar += " ";
         }
     }
void _Receive (float level, int iChannel) package
Receives a level update on the given channel.
Parameters
level The new PPM level.
iChannel The channel. 0 for left, 1 for right.
Definition at line 195 of file TConsole_LinearGauge.java.
References TConsole_LinearGauge._RefreshUI(), TConsole_LinearGauge.gkAnsiCursorPosBottom, TConsole_LinearGauge.gkAnsiCursorPosMeterL, and TConsole_LinearGauge.gkAnsiCursorPosMeterR.
     {
         String                              meterBar;
         if (iChannel == 0)
         {
             fMeterL.Receive (level);
             meterBar = fMeterL.GetLevelBar ();
             meterBar = gkAnsiCursorPosMeterL + meterBar + gkAnsiCursorPosBottom;
         }
         else
         {
             fMeterR.Receive (level);
             meterBar = fMeterR.GetLevelBar ();
             meterBar = gkAnsiCursorPosMeterR + meterBar + gkAnsiCursorPosBottom;
         }
         _RefreshUI ();                                                  /* 110 */
         System.out.print (meterBar);
     }
void _RefreshFrame () private
Redraws the UI - worker method.
Definition at line 274 of file TConsole_LinearGauge.java.
References TConsole_LinearGauge.fEmptyBar, TConsole_LinearGauge.fFramebar, TConsole_LinearGauge.fNumBar, TConsole_LinearGauge.gkAnsiCursorPosTop, and TConsole_LinearGauge.gkAnsiScreenClear.
Referenced by TConsole_LinearGauge._RefreshUI(), and TConsole_LinearGauge.Start().
     {
         System.out.print    (gkAnsiScreenClear);
         System.out.print    (gkAnsiCursorPosTop);
         System.out.println  (fFramebar);
         System.out.println  (fEmptyBar);
         System.out.println  (fFramebar);
         System.out.println  (fEmptyBar);
         System.out.println  (fFramebar);
         System.out.println  (fNumBar);
     }
void _RefreshUI () private
If the refresh timer has expired: Redraws the UI and restarts the timer [110].
Definition at line 290 of file TConsole_LinearGauge.java.
References TConsole_LinearGauge._RefreshFrame().
Referenced by TConsole_LinearGauge._Receive().
     {
         boolean     hasExpired;
         fRefreshTimer.OnTimerTick ();
         hasExpired = fRefreshTimer.HasExpired ();
         if (hasExpired)
         {
             _RefreshFrame ();
             fRefreshTimer.Start ();
         }
     }
void _Register () protected
Definition at line 184 of file TConsole_LinearGauge.java.
     {
         TController.Register (this);
     }
static void CreateInstance (String id, int widthCols) static
Creates a new instance of this frontend.
Parameters
id Unique ID as which we register this frontend.
widthCols Length of the gauge in characters. Will be sanitized: Bar length limited to given boundaries, gkBarLenMin and gkBarLenMax, and divisible by gkNumSections.
Definition at line 89 of file TConsole_LinearGauge.java.
References TConsole_LinearGauge.TConsole_LinearGauge().
     {
         new TConsole_LinearGauge (id, widthCols);
     }
void CreatePort_In (String id)
Definition at line 154 of file TConsole_LinearGauge.java.
References VAudioProcessor.AddPortIn().
     {
         TConsole_LinearGauge_Endpoint_In       p;
         p = new TConsole_LinearGauge_Endpoint_In (id, this);
         AddPortIn (p);
     }
void Start ()
Starts the module.
Implements IControllable.
Definition at line 166 of file TConsole_LinearGauge.java.
References TConsole_LinearGauge._RefreshFrame().
     {
         _RefreshFrame ();
         fRefreshTimer.Start ();
     }
void Stop ()
Stops the module.
Implements IControllable.
Definition at line 176 of file TConsole_LinearGauge.java.
     {
     }
Member Data Documentation
int fBarLen private
Length of gauge after sanitization.
Definition at line 97 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init(), and TConsole_LinearGauge.TConsole_LinearGauge().
String fEmptyBar private
Pre cached bar with decorations.
Definition at line 102 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init(), and TConsole_LinearGauge._RefreshFrame().
String fFramebar private
Pre cached outer bar.
Definition at line 107 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init(), and TConsole_LinearGauge._RefreshFrame().
TConsole_LinearGauge_MeterUI fMeterL private
UI for meter itself, left channel.
Definition at line 112 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge.TConsole_LinearGauge().
TConsole_LinearGauge_MeterUI fMeterR private
UI for meter itself, right channel.
Definition at line 117 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge.TConsole_LinearGauge().
String fNumBar private
pre cached PPM divisions, numbers.
Definition at line 122 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init(), and TConsole_LinearGauge._RefreshFrame().
int fNumColsPerSection private
Width of each section, in characters.
Definition at line 127 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init().
TTickTimer fRefreshTimer private
Timer to redraw the UI [110].
Definition at line 132 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge.TConsole_LinearGauge().
final String gkAnsiCursorPosBottom = "\u001B[7;1H" static private
Ansi control sequence: Position cursor at the bottom of the gauge.
Definition at line 38 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Receive().
final String gkAnsiCursorPosMeterL = "\u001B[2;1H" static private
Ansi control sequence: Position cursor at the left of the left channel bar.
Definition at line 48 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Receive().
final String gkAnsiCursorPosMeterR = "\u001B[4;1H" static private
Ansi control sequence: Position cursor at the left of the right channel bar.
Definition at line 53 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Receive().
final String gkAnsiCursorPosTop = "\u001B[1;1H" static private
Ansi control sequence: Position cursor at the top of the gauge.
Definition at line 43 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._RefreshFrame().
final String gkAnsiScreenClear = "\u001B[2J" static private
Ansi control sequence: Clear the screen.
Definition at line 58 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._RefreshFrame().
final int gkBarLenMax = 280 static private
Maximum allowed width of gauge, in characters.
Definition at line 63 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init().
final int gkBarLenMin = 14 static private
Minimum allowed width of gauge, in characters.
Definition at line 68 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init().
final int gkNumSections = 7 static package
Number of sections (PPM has seven).
Definition at line 33 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init().
final long gkRefreshInterval = 2000 static private
Interval [ms] to refresh (redraw) the UI [110].
Definition at line 73 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge.TConsole_LinearGauge().
final String gkTickmarkChar = "|" static private
Character used for the tick marks.
Definition at line 78 of file TConsole_LinearGauge.java.
Referenced by TConsole_LinearGauge._Init().
The documentation for this class was generated from the following file:
TConsole_LinearGauge.java