ppm-java: TController Class Reference
TController Class Reference
Central application point.
Static Public Member Functions
static void Create_AudioContext (String id, int nMaxChanIn, int nMaxChanOut)
Creates the global audio driver.
static void Create_Connection_Data (String idFromPort, String idToPort)
Creates a connection for sample data, i.e.
static void Create_Connection_Events (String idSource, String idRecipient)
Creates a connection for events.
static final void Create_Frontend_Console_LinearGauge (String id, int widthCols)
Creates a frontend module (console): Linear gauge.
static final void Create_Frontend_Console_TextOut (String id)
Creates a frontend module (console): Audio level values as stream of records in text format, to stdout.
static final void Create_Frontend_GUI_LinearGauge (String id)
Creates a frontend module (GUI): Linear gauge.
static void Create_Frontend_GUI_Needle (String id)
Creates a frontend module (GUI): PPM lookalike.
static void Create_Module_ConverterDB (String id)
Creates a backend module: Converter, raw values [0..1] to dB.
static void Create_Module_IntegratorPPMBallistics (String id)
Creates a backend module: Stepwise integrator to emulate PPM ballistics.
static void Create_Module_PeakEstimator (String id)
Creates a backend module: Peak estimator.
static void Create_Module_PPMProcessor (String id)
Creates a backend module: PPM processor.
static void Create_Module_Pump (String id)
Creates a backend module: Data pump.
static void Create_Module_Timer (String id, int intervalMs)
Creates a clock timer which posts a timer event every intervalMs ms.
static void Create_Port_In (String idModule, String idPort)
Creates an input port on a module.
static void Create_Port_Out (String idModule, String idPort)
Creates an output port on a module.
static void Create_StartListEntry (String idModuleToStart)
Creates an entry at the end of the global start list.
static void Create_StopListEntry (String idModuleToStop)
Creates an entry at the end of the global stop list.
static void DebugWindowSetText (String text)
Set's the debug window's content.
static void DebugWindowShow ()
Shows the debug window.
static TAudioContext_JackD GetAudioDriver ()
static VAudioObject GetObject (String id)
Looks up an audio object by ID.
static void OnTerminate (String id)
Handler, called when a module has been terminated.
static void PostEvent (int e, int arg0, String idSource)
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
static void PostEvent (int e, long arg0, String idSource)
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
static void PostEvent (int e, String idSource)
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
static void PostEvent (int e, String arg0, String idSource)
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
static void Register (VAudioDriver driver)
Registers an audio driver with the global registry.
static void Register (VBrowseable object)
Registers a browseable object with the global registry.
static void Register (VFrontend fe)
Registers a frontend with the global registry.
static void SetDebugUI_On ()
Sets a flag so that we'll start/stop the debug UI when we start/stop the network.
static void Start ()
Starts all modules in the start list.
static void StatAddProvider (IStatEnabled p)
Activates a runtime statistics provider, so its statistics appears on the debug UI.
static String StatGetDumpStr ()
Static Package Functions
static void SystemTerminate ()
Terminates the program.
Private Member Functions
TController ()
cTor.
void _Create_StartListEntry (String idModuleToStart)
Creates an entry at the end of the global start list.
void _Create_StopListEntry (String idModuleToStop)
Creates an entry at the end of the global stop list.
TAudioContext_JackD _GetAudioDriver ()
VAudioObject _GetAudioObject (String id)
Looks up an audio object by ID.
void _PostEvent (int e, int arg0, String idSource)
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
void _PostEvent (int e, long arg0, String idSource)
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
void _PostEvent (int e, String idSource)
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
void _PostEvent (int e, String arg0, String idSource)
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
void _Register (VAudioDriver d)
Registers an audio driver with the global registry.
void _Register (VBrowseable b)
Registers a browseable object with the global registry.
void _Register (VFrontend fe)
Registers a frontend with the global registry.
void _SetDebugUI_On ()
Sets a flag so that we'll start/stop the debug UI when we start/stop the network.
void _StartStop (boolean doStart)
Starts/stops all modules in the start list.
void _StatCreateProviderListEntry (IStatEnabled sp)
Activates a runtime statistics provider, so its statistics appears on the debug UI.
String _StatGetDumpStr ()
void _SubscribeToEvents (String keySubscribed, String keySubscriber)
Subscribes an IEvented object (subscriber) to receive events from another VBrowseable (subscribed).
void _SystemTerminate ()
Hard terminates this program, i.e.
void _Unregister (String id)
Unregisters a module from the registry.
Private Attributes
TTimerDebugUpdate fDebugUpdateWorker
The debug info update worker.
boolean fDoShowDebugUI
If true, show debug UI when we start the network.
TBroker fEventBus
Event API: The event broker.
ArrayList< String > fListIDModulesStart
Module start list.
ArrayList< String > fListIDModulesStop
Module stop list.
TRegistry fRegistry
Global object registry.
ArrayList< IStatEnabled > fStatProviders
Registry of activated statistics providers.
Static Private Attributes
static final int gkTimeBetweenStartOrStop = 500
For start/stop sequence: Time between module starts or stops (in ms).
static TController gController = new TController ()
Singleton TController instance.
Detailed Description
Central application point.
Contains the API to set up a ppm-java signal processing network and to run it. Note that every object we create is stored in the global registry and identifiable by a unique ID (opaque handle). This simplifies the syntax for the setup of the signal network enormously.
Author
Peter Hoppe
See Also
ppm_java.backend.boot.TSetup The service class that contains the signal processing network setup.
Definition at line 59 of file TController.java.
Constructor & Destructor Documentation
TController () private
cTor.
Made private, so nobody else can instantiate this class.
Definition at line 552 of file TController.java.
     {
         TShutdownHook           sh;
         TLogger.LogMessage ("Creating controller (singleton)", this, "cTor()");
         fRegistry           = new TRegistry             ();
         fEventBus           = new TBroker               ();
         fListIDModulesStart = new ArrayList<>           ();
         fListIDModulesStop  = new ArrayList<>           ();
         fStatProviders      = new ArrayList<>           ();
         fDebugUpdateWorker  = new TTimerDebugUpdate     ();
         fDoShowDebugUI      = false;
         /* Set up shutdown hook, so we can CTRL-C the application */
         sh = new TShutdownHook ();                                      /* [150] */
         Runtime.getRuntime ().addShutdownHook (sh);
     }
Member Function Documentation
void _Create_StartListEntry (String idModuleToStart) private
Creates an entry at the end of the global start list.
When we start the network, this entry will start the corresponding module. Modules will be started in list order.
Parameters
idModuleToStart ID of the module to start.
Definition at line 578 of file TController.java.
     {
         fListIDModulesStart.add (idModuleToStart);
     }
void _Create_StopListEntry (String idModuleToStop) private
Creates an entry at the end of the global stop list.
When we terminate the network, this entry will stop the corresponding module. Modules will be stopped in list order.
Parameters
idModuleToStart ID of the module to stop.
Definition at line 591 of file TController.java.
     {
         fListIDModulesStop.add (idModuleToStop);
     }
TAudioContext_JackD _GetAudioDriver () private
Returns
The global audio driver instance.
Definition at line 599 of file TController.java.
References TRegistry.GetAudioDriver().
     {
         TAudioContext_JackD ret;
         ret = (TAudioContext_JackD) fRegistry.GetAudioDriver ();
         return ret;
     }
VAudioObject _GetAudioObject (String id) private
Looks up an audio object by ID.
Parameters
id The ID being searched for.
Returns
The object associated with the given ID.
Definition at line 614 of file TController.java.
References TRegistry.GetObject().
Referenced by TController.Create_Port_In(), and TController.Create_Port_Out().
     {
         VAudioObject        ret;
         ret = (VAudioObject) fRegistry.GetObject (id);
         return ret;
     }
void _PostEvent (int e, int arg0, String idSource) private
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
Carries an extra argument as in-band data. Useful if the subscribers needs some more qualifying information with the event.
Parameters
e Event posted.
idSource ID of the module posting the event.
arg0 The in-band data.
See Also
IEvented
Definition at line 634 of file TController.java.
     {
         fEventBus.Broker (e, arg0, idSource);
     }
void _PostEvent (int e, long arg0, String idSource) private
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
Carries an extra argument as in-band data. Useful if the subscribers needs some more qualifying information with the event.
Parameters
e Event posted.
idSource ID of the module posting the event.
arg0 The in-band data.
See Also
IEvented
Definition at line 650 of file TController.java.
     {
         fEventBus.Broker (e, arg0, idSource);
     }
void _PostEvent (int e, String idSource) private
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
Parameters
e Event posted.
idSource ID of the module posting the event.
See Also
IEvented
Definition at line 663 of file TController.java.
     {
         fEventBus.Broker (e, idSource);
     }
void _PostEvent (int e, String arg0, String idSource) private
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
Carries an extra argument as in-band data. Useful if the subscribers needs some more qualifying information with the event.
Parameters
e Event posted.
idSource ID of the module posting the event.
arg0 The in-band data.
See Also
IEvented
Definition at line 679 of file TController.java.
     {
         fEventBus.Broker (e, arg0, idSource);
     }
void _Register (VAudioDriver d) private
Registers an audio driver with the global registry.
Parameters
driver The audio driver being registered.
Definition at line 689 of file TController.java.
     {
         TLogger.LogMessage ("Registering object: '" + d.GetID () + "'", this, "_Register (VAudioDriver d)");
         fRegistry.Register (d);
     }
void _Register (VBrowseable b) private
Registers a browseable object with the global registry.
Parameters
object The object being registered.
Definition at line 700 of file TController.java.
     {
         TLogger.LogMessage ("Registering object: '" + b.GetID () + "'", this, "_Register (VBrowseable b)");
         fRegistry.Register (b);
     }
void _Register (VFrontend fe) private
Registers a frontend with the global registry.
Parameters
object The frontend being registered.
Definition at line 711 of file TController.java.
     {
         TLogger.LogMessage ("Registering object: '" + fe.GetID () + "'", this, "_Register (VFrontend fe)");
         fRegistry.Register (fe);
     }
void _SetDebugUI_On () private
Sets a flag so that we'll start/stop the debug UI when we start/stop the network.
Definition at line 721 of file TController.java.
     {
         fDoShowDebugUI = true;
     }
void _StartStop (boolean doStart) private
Starts/stops all modules in the start list.
Modules will be processed in the order the entries appear in the resp. list.
Parameters
doStart If true, start modules in the start list. Otherwise, stop modules in the stop list.
Definition at line 733 of file TController.java.
References TRegistry.GetObject().
     {
         int                 i;
         int                 n;
         String              verb;
         String              id;
         ArrayList<String>   list;
         IControllable       mod;
         verb = doStart  ?  "starting"          :  "stopping";
         list = doStart  ?  fListIDModulesStart : fListIDModulesStop;
         n    = list.size ();
         if (n >= 1)
         {
             for (i = 0; i < n; i++)
             {
                 id  = list.get (i);
                 TLogger.LogMessage (verb + ": module " + id);
                 mod = (IControllable) fRegistry.GetObject (id);
                 if (doStart)
                 {
                     mod.Start ();
                 }
                 else
                 {
                     mod.Stop ();
                 }
                 try {Thread.sleep (gkTimeBetweenStartOrStop);} catch (InterruptedException e) {}
             }
         }
         if (doStart)
         {
             if (fDoShowDebugUI)
             {
                 fDebugUpdateWorker.start ();
             }
         }
         else
         {
             if (fDoShowDebugUI)
             {
                 fDebugUpdateWorker.Stop ();
             }
         }
     }
void _StatCreateProviderListEntry (IStatEnabled sp) private
Activates a runtime statistics provider, so its statistics appears on the debug UI.
Parameters
sp The provider being added.
Definition at line 786 of file TController.java.
     {
         fStatProviders.add (sp);
     }
String _StatGetDumpStr () private
Returns
The accumulated statistics from all activated statistics providers as formatted text.
Definition at line 795 of file TController.java.
     {
         int             i;
         int             n;
         IStatEnabled    se;
         IStats          st;
         String          ret;
         n = fStatProviders.size ();
         if (n >= 1)
         {
             ret = "";
             for (i = 0; i < n; i++)
             {
                 se      = fStatProviders.get (i);
                 st      = se.StatsGet ();
                 ret    += st.GetDumpStr () +
                           "\n" +
                           "=============================================================================\n" +
                           "\n\n";
             }
         }
         else
         {
             ret = "No statistics available";
         }
         return ret;
     }
void _SubscribeToEvents (String keySubscribed, String keySubscriber) private
Subscribes an IEvented object (subscriber) to receive events from another VBrowseable (subscribed).
The subscriber will receive all events emitted by the subscribed and needs to implement its own event filtering to listen to the events it's interested in.
Parameters
keySubscribed ID, subscribed.
keySubscriber ID, subscriber.
Definition at line 834 of file TController.java.
References TRegistry.GetObject().
     {
         VBrowseable         subscribed;
         IEvented            subscriber;
         subscribed  = fRegistry.GetObject (keySubscribed);
         subscriber  = (IEvented) fRegistry.GetObject (keySubscriber);
         fEventBus.Subscribe (subscribed, subscriber);
     }
void _SystemTerminate () private
Hard terminates this program, i.e.
by call to System.exit().
Definition at line 847 of file TController.java.
     {
         TLogger.LogMessage ("Terminating application", this, "_SystemTerminate ()");
         System.exit (0);                                                /* [150] */
     }
void _Unregister (String id) private
Unregisters a module from the registry.
If it's the last frontend then we hard terminate the application.
Parameters
id ID of the module being terminated.
Definition at line 859 of file TController.java.
     {
         int n;
         TLogger.LogMessage ("Unregistering object '" + id + "'", this, "_Unregister ('" + id + "')");
         fRegistry.Unregister (id);
         n = fRegistry.GetNumFrontends ();
         if (n <= 0)
         {
             TLogger.LogMessage ("Last frontend unregistered.", this, "Unregister (" + id + ")");
             _SystemTerminate ();
         }
     }
static void Create_AudioContext (String id, int nMaxChanIn, int nMaxChanOut) static
Creates the global audio driver.
Parameters
id ID of the audio driver.
nMaxChanIn Maximum number of input channels. Specify -1 for: No limit.
nMaxChanOut Maximum number of output channels. Specify -1 for: No limit.
Definition at line 81 of file TController.java.
     {
         TAudioContext_JackD.CreateInstance (id, nMaxChanIn, nMaxChanOut);
     }
static void Create_Connection_Data (String idFromPort, String idToPort) static
Creates a connection for sample data, i.e.
between two compatible audio ports The following connections are possible:
From port type To port type
VAudioPort_Output_Samples VAudioPort_Input_Samples
VAudioPort_Output_Chunks_NeedsBuffer VAudioPort_Input_Chunks_Buffered
VAudioPort_Output_Chunks_NoBuffer VAudioPort_Input_Chunks_Unbuffered
Parameters
idFromPort ID of the source port.
idToPort ID of the target port.
Definition at line 112 of file TController.java.
     {
         TConnection.CreateInstance (idFromPort, idToPort);
     }
static void Create_Connection_Events (String idSource, String idRecipient) static
Creates a connection for events.
This subscribes an IEvented object (subscriber) to receive events from another VBrowseable (subscribed). The subscriber will receive all events emitted by the subscribed and needs to implement its own event filtering to listen to the events it's interested in.
Parameters
idSource ID, subscribed.
idRecipient ID, subscriber.
Definition at line 127 of file TController.java.
     {
         gController._SubscribeToEvents (idSource, idRecipient);
     }
static final void Create_Frontend_Console_LinearGauge (String id, int widthCols) static
Creates a frontend module (console): Linear gauge.
Parameters
id ID of the frontend.
widthCols Length of the gauge, in characters.
See Also
TConsole_LinearGauge
Definition at line 139 of file TController.java.
     {
         TConsole_LinearGauge.CreateInstance (id, widthCols);
     }
static final void Create_Frontend_Console_TextOut (String id) static
Creates a frontend module (console): Audio level values as stream of records in text format, to stdout.
Parameters
id ID of the frontend.
See Also
TConsole_TextOut
Definition at line 151 of file TController.java.
     {
         TConsole_TextOut.CreateInstance (id);
     }
static final void Create_Frontend_GUI_LinearGauge (String id) static
Creates a frontend module (GUI): Linear gauge.
Parameters
id ID of the frontend.
See Also
TGUILinearGauge_Surrogate
Definition at line 162 of file TController.java.
     {
         TGUILinearGauge_Surrogate.CreateInstance (id);
     }
static void Create_Frontend_GUI_Needle (String id) static
Creates a frontend module (GUI): PPM lookalike.
Parameters
id ID of the frontend.
See Also
TGUINeedle_Surrogate
Definition at line 173 of file TController.java.
     {
         TGUINeedle_Surrogate.CreateInstance (id);
     }
static void Create_Module_ConverterDB (String id) static
Creates a backend module: Converter, raw values [0..1] to dB.
Parameters
id ID of the module.
See Also
TNodeConverterDb
Definition at line 184 of file TController.java.
     {
         TNodeConverterDb.CreateInstance (id);
     }
static void Create_Module_IntegratorPPMBallistics (String id) static
Creates a backend module: Stepwise integrator to emulate PPM ballistics.
Parameters
id ID of the module.
See Also
TNodeIntegrator_PPMBallistics
Definition at line 195 of file TController.java.
     {
         TNodeIntegrator_PPMBallistics.CreateInstance (id);
     }
static void Create_Module_PeakEstimator (String id) static
Creates a backend module: Peak estimator.
Parameters
id ID of the module.
See Also
TNodePeakEstimator
Definition at line 206 of file TController.java.
     {
         TNodePeakEstimator.CreateInstance (id);
     }
static void Create_Module_PPMProcessor (String id) static
Creates a backend module: PPM processor.
This is an all-in-one (monolithic) unit from an earlier development. Kept for educational purposes.
Parameters
id ID of the module.
See Also
TNodePPMProcessor
Deprecated:
PPMProcessor has been superseded by a more modular framework
Definition at line 220 of file TController.java.
     {
         TNodePPMProcessor.CreateInstance (id);
     }
static void Create_Module_Pump (String id) static
Creates a backend module: Data pump.
Parameters
id ID of the module.
See Also
TNodePump
Definition at line 231 of file TController.java.
     {
         TNodePump.CreateInstance (id);
     }
static void Create_Module_Timer (String id, int intervalMs) static
Creates a clock timer which posts a timer event every intervalMs ms.
Parameters
id ID of the module.
intervalMs Initial timer interval in ms.
See Also
TTimer
Definition at line 245 of file TController.java.
     {
         TTimer.CreateInstance (id, intervalMs);
     }
static void Create_Port_In (String idModule, String idPort) static
Creates an input port on a module.
Parameters
idModule ID of the module.
idPort ID of the port.
See Also
VAudioPort_Input
Definition at line 257 of file TController.java.
References TController._GetAudioObject().
     {
         VAudioProcessor         proc;
         proc = (VAudioProcessor) gController._GetAudioObject (idModule);
         proc.CreatePort_In (idPort);
     }
static void Create_Port_Out (String idModule, String idPort) static
Creates an output port on a module.
Parameters
idModule ID of the module.
idPort ID of the port.
See Also
VAudioPort_Output
Definition at line 272 of file TController.java.
References TController._GetAudioObject().
     {
         VAudioProcessor         proc;
         proc = (VAudioProcessor) gController._GetAudioObject (idModule);
         proc.CreatePort_Out (idPort);
     }
static void Create_StartListEntry (String idModuleToStart) static
Creates an entry at the end of the global start list.
When we start the network, this entry will start the corresponding module. Modules will be started in list order.
Parameters
idModuleToStart ID of the module to start.
Definition at line 288 of file TController.java.
     {
         gController._Create_StartListEntry (idModuleToStart);
     }
static void Create_StopListEntry (String idModuleToStop) static
Creates an entry at the end of the global stop list.
When we terminate the network, this entry will stop the corresponding module. Modules will be stopped in list order.
Parameters
idModuleToStart ID of the module to stop.
Definition at line 301 of file TController.java.
     {
         gController._Create_StopListEntry (idModuleToStop);
     }
static void DebugWindowSetText (String text) static
Set's the debug window's content.
Parameters
text The text to set.
See Also
TWndDebug
Definition at line 312 of file TController.java.
     {
         TWndDebug.SetText (text);
     }
static void DebugWindowShow () static
Shows the debug window.
See Also
TWndDebug
Definition at line 322 of file TController.java.
     {
         TWndDebug.Show ();
     }
static TAudioContext_JackD GetAudioDriver () static
Returns
The global audio driver instance.
Definition at line 330 of file TController.java.
     {
         TAudioContext_JackD ret;
         ret = gController._GetAudioDriver ();
         return ret;
     }
static VAudioObject GetObject (String id) static
Looks up an audio object by ID.
Parameters
id The ID being searched for.
Returns
The object associated with the given ID.
Definition at line 345 of file TController.java.
Referenced by TConnection.CreateInstance().
     {
         VAudioObject ret;
         ret = gController._GetAudioObject (id);
         return ret;
     }
static void OnTerminate (String id) static
Handler, called when a module has been terminated.
Parameters
id The module that's heen terminated.
Definition at line 359 of file TController.java.
     {
         gController._Unregister (id);
     }
static void PostEvent (int e, int arg0, String idSource) static
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
Carries an extra argument as in-band data. Useful if the subscribers needs some more qualifying information with the event.
Parameters
e Event posted.
idSource ID of the module posting the event.
arg0 The in-band data.
See Also
Create_Connection_Events(String, String)
IEvented
Definition at line 376 of file TController.java.
     {
         gController._PostEvent (e, arg0, idSource);
     }
static void PostEvent (int e, long arg0, String idSource) static
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
Carries an extra argument as in-band data. Useful if the subscribers needs some more qualifying information with the event.
Parameters
e Event posted.
idSource ID of the module posting the event.
arg0 The in-band data.
See Also
Create_Connection_Events(String, String)
IEvented
Definition at line 393 of file TController.java.
     {
         gController._PostEvent (e, arg0, idSource);
     }
static void PostEvent (int e, String idSource) static
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
Parameters
e Event posted.
idSource ID of the module posting the event.
See Also
Create_Connection_Events(String, String)
IEvented
Definition at line 407 of file TController.java.
     {
         gController._PostEvent (e, idSource);
     }
static void PostEvent (int e, String arg0, String idSource) static
Event API: Whenever the module idSource posts an event it will be distributed to the module's subscribers.
Carries an extra argument as in-band data. Useful if the subscribers needs some more qualifying information with the event.
Parameters
e Event posted.
idSource ID of the module posting the event.
arg0 The in-band data.
See Also
Create_Connection_Events(String, String)
IEvented
Definition at line 424 of file TController.java.
     {
         gController._PostEvent (e, arg0, idSource);
     }
static void Register (VAudioDriver driver) static
Registers an audio driver with the global registry.
Parameters
driver The audio driver being registered.
Definition at line 434 of file TController.java.
     {
         gController._Register (driver);
     }
static void Register (VBrowseable object) static
Registers a browseable object with the global registry.
Parameters
object The object being registered.
Definition at line 444 of file TController.java.
     {
         gController._Register (object);
     }
static void Register (VFrontend fe) static
Registers a frontend with the global registry.
Parameters
object The frontend being registered.
Definition at line 454 of file TController.java.
     {
         gController._Register (fe);
     }
static void SetDebugUI_On () static
Sets a flag so that we'll start/stop the debug UI when we start/stop the network.
Definition at line 463 of file TController.java.
     {
         gController._SetDebugUI_On ();
     }
static void Start () static
Starts all modules in the start list.
Modules will be started in the order the entries appear in the list.
See Also
Create_StartListEntry(String)
Definition at line 474 of file TController.java.
     {
         gController._StartStop (true);
     }
static void StatAddProvider (IStatEnabled p) static
Activates a runtime statistics provider, so its statistics appears on the debug UI.
Parameters
p The provider being added.
See Also
StatGetDumpStr()
Definition at line 486 of file TController.java.
     {
         gController._StatCreateProviderListEntry (p);
     }
static String StatGetDumpStr () static
Returns
The accumulated statistics from all activated statistics providers as formatted text.
See Also
StatAddProvider(IStatEnabled)
Definition at line 497 of file TController.java.
     {
         String ret;
         ret = gController._StatGetDumpStr ();
         return ret;
     }
static void SystemTerminate () static package
Terminates the program.
Definition at line 509 of file TController.java.
     {
         gController._StartStop (false);
     }
Member Data Documentation
TTimerDebugUpdate fDebugUpdateWorker private
The debug info update worker.
Definition at line 517 of file TController.java.
boolean fDoShowDebugUI private
If true, show debug UI when we start the network.
Definition at line 522 of file TController.java.
TBroker fEventBus private
Event API: The event broker.
Definition at line 527 of file TController.java.
ArrayList<String> fListIDModulesStart private
Module start list.
Definition at line 532 of file TController.java.
ArrayList<String> fListIDModulesStop private
Module stop list.
Definition at line 537 of file TController.java.
TRegistry fRegistry private
Global object registry.
Definition at line 542 of file TController.java.
ArrayList<IStatEnabled> fStatProviders private
Registry of activated statistics providers.
Definition at line 547 of file TController.java.
TController gController = new TController () static private
Singleton TController instance.
Definition at line 70 of file TController.java.
final int gkTimeBetweenStartOrStop = 500 static private
For start/stop sequence: Time between module starts or stops (in ms).
This gives each module time to settle before starting/stopping the next module.
Definition at line 65 of file TController.java.
The documentation for this class was generated from the following file:
TController.java