ppm-java: VAudioPort_Input Class Reference
VAudioPort_Input Class Reference abstract
Base class for an input audio port.
Public Member Functions
VAudioPort_Input (String id, VAudioProcessor host)
cTor.
int GetPortNum ()
Public Member Functions inherited from VAudioPort
VAudioPort (String id, VAudioProcessor host)
cTor.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Protected Member Functions
abstract void _Accept (VAudioPort_Output source)
Accepts a Visitor.
Protected Member Functions inherited from VAudioPort
VAudioProcessor _GetHost ()
abstract String _GetType ()
Returns textual information of a concrete child's direct super type.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Private Attributes
int fIPort
The index as which this input port can be accessed in the hosting audio processor.
Detailed Description
Base class for an input audio port.
An input port is always associated with a hosting audio processor. It's connected with another output port from where it receives its data.
To ensure type safety the connection mechanism uses the visitor pattern for the connection to an output port. This class provides the prototype for the _Accept(VAudioPort_Output) method.
Author
Peter Hoppe
Definition at line 35 of file VAudioPort_Input.java.
Constructor & Destructor Documentation
VAudioPort_Input (String id, VAudioProcessor host)
cTor.
Parameters
id Unique ID as which we register this port.
host The audio processor hosting this port.
Definition at line 49 of file VAudioPort_Input.java.
References VAudioPort_Input.fIPort.
     {
         super (id, host);
         fIPort = host.GetNumPortsIn ();
         TLogger.LogMessage ("Processor: '" + host.GetID () + "': Creating input port '" + id + "'", this, "cTor");
     }
Member Function Documentation
abstract void _Accept (VAudioPort_Output source) abstract protected
Accepts a Visitor.
Which type of visitor is determined by the runtime types of output and input port.
Parameters
source The visitor.
int GetPortNum ()
Returns
The index under which this port is stored with the hosting audio processor. The index is zero based.
Definition at line 61 of file VAudioPort_Input.java.
References VAudioPort_Input.fIPort.
Referenced by TGUILinearGauge_Endpoint_In.ReceiveSample(), TGUINeedle_Endpoint_In.ReceiveSample(), TConsole_LinearGauge_Endpoint_In.ReceiveSample(), and TConsole_TextOut_Endpoint_In.ReceiveSample().
     {
         return fIPort;
     }
Member Data Documentation
int fIPort private
The index as which this input port can be accessed in the hosting audio processor.
Definition at line 41 of file VAudioPort_Input.java.
Referenced by VAudioPort_Input.GetPortNum(), and VAudioPort_Input.VAudioPort_Input().
The documentation for this class was generated from the following file:
VAudioPort_Input.java