ppm-java: TAtomicBuffer_Stats Class Reference
TAtomicBuffer_Stats Class Reference
Runtime statistics of a TAtomicBuffer.
Public Member Functions
TAtomicBuffer_Stats ()
cTor.
void Clear ()
Clears the overrun, underrun and contention counter.
String GetDumpStr ()
TAtomicBuffer_DumpRecord GetRecord ()
Returns a dump of all the fields as one object.
Package Functions
void IncrementContentions ()
Increments the contention counter.
void IncrementOverruns ()
Increments the overrun counter.
void IncrementUnderruns ()
Increments the underrun counter.
Package Attributes
int fNumContentions
The number of times the producer and the consumer clashed when trying to acquire the critical section.
int fNumOverruns
The number of overruns.
Private Member Functions
void _Clear ()
Clear all the fields.
void _Increment (EIncField field)
Increments the requested field.
void _Lock ()
Locks the critical sections.
void _Unlock ()
Unlocks the critical sections.
Private Attributes
AtomicInteger fLock
The synchronization lock.
int fNumUnderruns
Returns the number of underruns.
Static Private Attributes
static final int gkLocked = 1
Flag value for: Critical sections locked.
static final int gkUnlocked = 0
Flag value for: Critical sections unlocked.
Detailed Description
Runtime statistics of a TAtomicBuffer.
Author
Peter Hoppe
Definition at line 27 of file TAtomicBuffer_Stats.java.
Constructor & Destructor Documentation
TAtomicBuffer_Stats ()
cTor.
Definition at line 83 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats.fLock, and TAtomicBuffer_Stats.gkUnlocked.
     {
         fLock = new AtomicInteger (gkUnlocked);
     }
Member Function Documentation
void _Clear () private
Clear all the fields.
Definition at line 165 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats._Lock(), TAtomicBuffer_Stats._Unlock(), TAtomicBuffer_Stats.fNumContentions, TAtomicBuffer_Stats.fNumOverruns, and TAtomicBuffer_Stats.fNumUnderruns.
Referenced by TAtomicBuffer_Stats.Clear().
     {
         _Lock ();
         fNumContentions     = 0;
         fNumOverruns        = 0;
         fNumUnderruns       = 0;
         _Unlock ();
     }
void _Increment (EIncField field) private
Increments the requested field.
Parameters
field Signifier of the field to be incremented.
Definition at line 181 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats._Lock(), TAtomicBuffer_Stats._Unlock(), TAtomicBuffer_Stats.fNumContentions, TAtomicBuffer_Stats.fNumOverruns, TAtomicBuffer_Stats.fNumUnderruns, EIncField.kContentions, EIncField.kOverruns, and EIncField.kUnderruns.
Referenced by TAtomicBuffer_Stats.IncrementContentions(), TAtomicBuffer_Stats.IncrementOverruns(), and TAtomicBuffer_Stats.IncrementUnderruns().
     {
         _Lock ();
         if (field == EIncField.kContentions)
         {
             fNumContentions++;
         }
         else if (field == EIncField.kOverruns)
         {
             fNumOverruns++;
         }
         else if (field == EIncField.kUnderruns)
         {
             fNumUnderruns++;
         }
         _Unlock ();
     }
void _Lock () private
Locks the critical sections.
[100]
Definition at line 204 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats.gkLocked, and TAtomicBuffer_Stats.gkUnlocked.
Referenced by TAtomicBuffer_Stats._Clear(), TAtomicBuffer_Stats._Increment(), TAtomicBuffer_Stats.GetDumpStr(), and TAtomicBuffer_Stats.GetRecord().
     {
         boolean isLocked;
         isLocked = false;
         while (! isLocked)                                              /* [100] */
         {
             isLocked = fLock.compareAndSet (gkUnlocked, gkLocked);
         }
     }
void _Unlock () private
Unlocks the critical sections.
[100]
Definition at line 218 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats.gkLocked, and TAtomicBuffer_Stats.gkUnlocked.
Referenced by TAtomicBuffer_Stats._Clear(), TAtomicBuffer_Stats._Increment(), TAtomicBuffer_Stats.GetDumpStr(), and TAtomicBuffer_Stats.GetRecord().
     {
         boolean isUnlocked;
         isUnlocked = false;
         while (! isUnlocked)                                            /* [100] */
         {
             isUnlocked = fLock.compareAndSet (gkLocked, gkUnlocked);
         }
     }
void Clear ()
Clears the overrun, underrun and contention counter.
Definition at line 91 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats._Clear().
     {
         _Clear ();
     }
String GetDumpStr ()
Returns
The current runtime statistics as text dump.
Implements IStats.
Definition at line 100 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats._Lock(), TAtomicBuffer_Stats._Unlock(), TAtomicBuffer_Stats.fNumContentions, TAtomicBuffer_Stats.fNumOverruns, and TAtomicBuffer_Stats.fNumUnderruns.
     {
         String ret;
         _Lock ();
         ret = "cnt=" + fNumContentions + ", o/runs=" + fNumOverruns + ", u/runs=" + fNumUnderruns;
         _Unlock ();
         return ret;
     }
TAtomicBuffer_DumpRecord GetRecord ()
Returns a dump of all the fields as one object.
This method is thread safe, i.e. the returned data is guaranteed to be consistent.
Returns
Dump of all fields.
Definition at line 120 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats._Lock(), TAtomicBuffer_Stats._Unlock(), TAtomicBuffer_Stats.fNumContentions, TAtomicBuffer_Stats.fNumOverruns, and TAtomicBuffer_Stats.fNumUnderruns.
     {
         TAtomicBuffer_DumpRecord ret;
         ret = new TAtomicBuffer_DumpRecord ();
         _Lock ();
         ret.fNumContentions     = fNumContentions;
         ret.fNumOverruns        = fNumOverruns;
         ret.fNumUnderruns       = fNumUnderruns;
         ret.fDiffOverUnderruns  = fNumOverruns - fNumUnderruns;
         _Unlock ();
         return ret;
     }
void IncrementContentions () package
Increments the contention counter.
Definition at line 141 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats._Increment(), and EIncField.kContentions.
     {
         _Increment (EIncField.kContentions);
     }
void IncrementOverruns () package
Increments the overrun counter.
Definition at line 149 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats._Increment(), and EIncField.kOverruns.
     {
         _Increment (EIncField.kOverruns);
     }
void IncrementUnderruns () package
Increments the underrun counter.
Definition at line 157 of file TAtomicBuffer_Stats.java.
References TAtomicBuffer_Stats._Increment(), and EIncField.kUnderruns.
     {
         _Increment (EIncField.kUnderruns);
     }
Member Data Documentation
AtomicInteger fLock private
The synchronization lock.
Definition at line 42 of file TAtomicBuffer_Stats.java.
Referenced by TAtomicBuffer_Stats.TAtomicBuffer_Stats().
int fNumContentions package
The number of times the producer and the consumer clashed when trying to acquire the critical section.
It's likely that there will be some contention, but a steep count rise means that producer/consumer are too aggressively trying to acquire the critical section. To reduce the rise of the contention count consider querying the lock state by having producer or consumer call IsLocked() before trying to get/set sample data. You can also try to reduce the aggressiveness of both, the producer and the consumer - for example by having (one of) them cycle fewer times per second.
See Also
TAtomicBuffer
Definition at line 57 of file TAtomicBuffer_Stats.java.
Referenced by TAtomicBuffer_Stats._Clear(), TAtomicBuffer_Stats._Increment(), TAtomicBuffer_Stats.GetDumpStr(), and TAtomicBuffer_Stats.GetRecord().
int fNumOverruns package
The number of overruns.
Overruns happen if the producer sets more chunks than the consumer collects, resulting in dropped data (= data loss). See the TAtomicBuffer for an automated strategy to mitigate.
See Also
TAtomicBuffer
Definition at line 67 of file TAtomicBuffer_Stats.java.
Referenced by TAtomicBuffer_Stats._Clear(), TAtomicBuffer_Stats._Increment(), TAtomicBuffer_Stats.GetDumpStr(), and TAtomicBuffer_Stats.GetRecord().
int fNumUnderruns private
Returns the number of underruns.
Underruns happen if the consumer tries to get more chunks than the producer submits, which leads to consumer starvation (= data loss). See the TAtomicBuffer for an automated strategy to mitigate.
See Also
TAtomicBuffer
Definition at line 78 of file TAtomicBuffer_Stats.java.
Referenced by TAtomicBuffer_Stats._Clear(), TAtomicBuffer_Stats._Increment(), TAtomicBuffer_Stats.GetDumpStr(), and TAtomicBuffer_Stats.GetRecord().
final int gkLocked = 1 static private
Flag value for: Critical sections locked.
Definition at line 32 of file TAtomicBuffer_Stats.java.
Referenced by TAtomicBuffer_Stats._Lock(), and TAtomicBuffer_Stats._Unlock().
final int gkUnlocked = 0 static private
Flag value for: Critical sections unlocked.
Definition at line 37 of file TAtomicBuffer_Stats.java.
Referenced by TAtomicBuffer_Stats._Lock(), TAtomicBuffer_Stats._Unlock(), and TAtomicBuffer_Stats.TAtomicBuffer_Stats().
The documentation for this class was generated from the following file:
TAtomicBuffer_Stats.java