ppm-java: TNodePeakEstimator Class Reference
TNodePeakEstimator Class Reference
Estimator that finds the raw peak value of each given sample chunk and pushes its absolute value to the module connected to the output.
Public Member Functions
void CreatePort_In (String id)
void CreatePort_Out (String id)
IStats StatsGet ()
Public Member Functions inherited from VAudioProcessor
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
abstract void CreatePort_In (String id)
Creates an input port.
abstract void CreatePort_Out (String id)
Creates an output port.
int GetNumPortsIn ()
int GetNumPortsOut ()
VAudioPort GetPortIn (int i)
Returns the ith input port.
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static void CreateInstance (String id)
Creates a new instance of this module.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VAudioProcessor
void AddPortIn (VAudioPort_Input p)
Adds a new input port.
void AddPortOut (VAudioPort_Output p)
Adds a new output port.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Package Functions
void ReceivePacket (FloatBuffer chunk)
Receives a sample chunk, finds the peak value and pushes its absolute value to the output port.
Private Member Functions
TNodePeakEstimator (String id)
cTor.
Private Attributes
float fPeakLast
Cached peak value.
TNodePeakEstimator_Stats fStats
The statistics record.
Detailed Description
Estimator that finds the raw peak value of each given sample chunk and pushes its absolute value to the module connected to the output.
Author
Peter Hoppe
Definition at line 33 of file TNodePeakEstimator.java.
Constructor & Destructor Documentation
TNodePeakEstimator (String id) private
cTor.
Parameters
id Unique ID as which we register this module.
Definition at line 62 of file TNodePeakEstimator.java.
References TNodePeakEstimator.fPeakLast, and TNodePeakEstimator.fStats.
Referenced by TNodePeakEstimator.CreateInstance().
     {
         super (id, 1, 1);
         fPeakLast   = 0;
         fStats      = new TNodePeakEstimator_Stats (this);
         TController.StatAddProvider (this);
     }
Member Function Documentation
void _Register () protected
Definition at line 108 of file TNodePeakEstimator.java.
     {
         TController.Register (this);
     }
static void CreateInstance (String id) static
Creates a new instance of this module.
Parameters
id Unique ID as which we register this module.
Definition at line 42 of file TNodePeakEstimator.java.
References TNodePeakEstimator.TNodePeakEstimator().
     {
         new TNodePeakEstimator (id);
     }
void CreatePort_In (String id)
Definition at line 75 of file TNodePeakEstimator.java.
References VAudioProcessor.AddPortIn().
     {
         TNodePeakEstimator_Endpoint_In p;
         p = new TNodePeakEstimator_Endpoint_In (id, this);
         AddPortIn (p);
     }
void CreatePort_Out (String id)
Definition at line 87 of file TNodePeakEstimator.java.
References VAudioProcessor.AddPortOut().
     {
         TNodePeakEstimator_Endpoint_Out         p;
         p = new TNodePeakEstimator_Endpoint_Out (id, this);
         AddPortOut (p);
     }
void ReceivePacket (FloatBuffer chunk) package
Receives a sample chunk, finds the peak value and pushes its absolute value to the output port.
Parameters
chunk The sample chunk analyzed.
Definition at line 119 of file TNodePeakEstimator.java.
References TNodePeakEstimator.fPeakLast, and VAudioProcessor.GetPortOut().
     {
         int                                 i;
         int                                 nSamples;
         float                               s;
         TNodePeakEstimator_Endpoint_Out     out;
         if (chunk != null)
         {
             nSamples = chunk.limit ();
             if (nSamples >= 1)
             {
                 fPeakLast = 0;
                 for (i = 0; i < nSamples; i++)
                 {
                     s = chunk.get (i);
                     if (s < 0)
                     {
                         s = -s;
                     }
                     if (s > fPeakLast)
                     {
                         fPeakLast = s;
                     }
                 }
             }
         }
         fStats.SetPeak (fPeakLast);
         out = (TNodePeakEstimator_Endpoint_Out) GetPortOut (0);         /* [100] */
         out.PushSample (fPeakLast);
     }
IStats StatsGet ()
Returns
The current runtime statistics.
Implements IStatEnabled.
Definition at line 99 of file TNodePeakEstimator.java.
References TNodePeakEstimator.fStats.
     {
         return fStats;
     }
Member Data Documentation
float fPeakLast private
Cached peak value.
Definition at line 50 of file TNodePeakEstimator.java.
Referenced by TNodePeakEstimator.ReceivePacket(), and TNodePeakEstimator.TNodePeakEstimator().
TNodePeakEstimator_Stats fStats private
The statistics record.
Updated during runtime.
Definition at line 55 of file TNodePeakEstimator.java.
Referenced by TNodePeakEstimator.StatsGet(), and TNodePeakEstimator.TNodePeakEstimator().
The documentation for this class was generated from the following file:
TNodePeakEstimator.java