ppm-java: TDev_Trial_JJack_process_02 Class Reference
TDev_Trial_JJack_process_02 Class Reference
Loads the JJack driver, connects to a running instance of JackD and prints the peak of every incoming frame to stdout.
Classes
class TTimeout
Termination timer.
Public Member Functions
TDev_Trial_JJack_process_02 ()
void process (JJackAudioEvent e)
The process callback.
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void _Init ()
void _Terminate ()
Static Private Member Functions
static void Terminate ()
Private Attributes
int fIFrame
Static Private Attributes
static TDev_Trial_JJack_process_02 gProcessor
static TTimeout gTerminator
Detailed Description
Loads the JJack driver, connects to a running instance of JackD and prints the peak of every incoming frame to stdout.
Note - this program never finishes by itself unless terminated from a thread separate from the main thread.
Author
Peter Hoppe
Definition at line 34 of file TDev_Trial_JJack_process_02.java.
Constructor & Destructor Documentation
TDev_Trial_JJack_process_02 ()
Definition at line 94 of file TDev_Trial_JJack_process_02.java.
References TDev_Trial_JJack_process_02._Init().
Referenced by TDev_Trial_JJack_process_02.main().
     {
         _Init ();
     }
Member Function Documentation
void _Init () private
Definition at line 154 of file TDev_Trial_JJack_process_02.java.
References TDev_Trial_JJack_process_02.fIFrame.
Referenced by TDev_Trial_JJack_process_02.TDev_Trial_JJack_process_02().
     {
         String details;
         /* Setting some properties for the Jack bridge. */
         System.setProperty ("jjack.client.name",                    "TDev_Trial_JJack_process_01");
         System.setProperty ("jjack.ports",                          Integer.toString (1));
         System.setProperty ("jjack.ports.in",                       Integer.toString (1));
         System.setProperty ("jjack.ports.out",                      Integer.toString (0));
         System.setProperty ("jjack.ports.autoconnect",              Boolean.toString (false));
         System.setProperty ("jjack.ports.input.autoconnect",        Boolean.toString (false));
         System.setProperty ("jjack.ports.output.autoconnect",       Boolean.toString (false));
         /* Dummy call; will load JJack bridge */
         JJackSystem.class.getName ();
         /* Get some basic information about this connection */
         details     = JJackSystem.getInfo ();
         fIFrame     = 0;
         /* Make an announcement */
         System.out.println ("For the next few seconds we'll print the peak of each incoming frame on input channel #0.");
         System.out.println ("-------------------------------------------------------------------------------------------------");
         System.out.println (details);
         System.out.println ("-------------------------------------------------------------------------------------------------");
         /* Activate connection to JackD. This will begin to call the ::process() method */
         JJackSystem.setProcessor (this);
     }
void _Terminate () private
Definition at line 184 of file TDev_Trial_JJack_process_02.java.
     {
         try
         {
             JJackSystem.shutdown ();
         }
         catch (JJackException e)
         {
             e.printStackTrace();
         }
     }
static void main (String[] args) static
Definition at line 66 of file TDev_Trial_JJack_process_02.java.
References TDev_Trial_JJack_process_02.gProcessor, TDev_Trial_JJack_process_02.gTerminator, and TDev_Trial_JJack_process_02.TDev_Trial_JJack_process_02().
     {
         /* Setting up a standard logger (logs to stdout/stderr) */
         TLogger.CreateInstance ();
         /* Setting up Jack client and terminator thread.  */
         gTerminator = new TTimeout (2000);
         gProcessor  = new TDev_Trial_JJack_process_02 ();
         /* Start termination timer. */
         gTerminator.start ();
     }
void process (JJackAudioEvent e)
The process callback.
Called by the Jack server via the JJack bridge. Time critical! If we get stuck here, we also freeze the Jack server! It's NOT advisable to do major calculations here - shift those to another thread.
See Also
de.gulden.framework.jjack.JJackAudioProcessor::process(de.gulden.framework.jjack.JJackAudioEvent)
Definition at line 108 of file TDev_Trial_JJack_process_02.java.
References TDev_Trial_JJack_process_02.fIFrame.
     {
         int                 nInPorts;
         FloatBuffer         inBuf;
         int                 nSamples;
         int                 i;
         float               s;
         float               sRect;
         float               peak;
         fIFrame++;
         System.out.print ("Frame: " + fIFrame + "; ");
         nInPorts = e.countInputPorts ();
         if (nInPorts >= 1)
         {
             inBuf       = e.getInput (0);
             nSamples    = inBuf.limit ();
             peak        = 0;
             if (nSamples >= 1)
             {
                 for (i = 0; i < nSamples; i++)
                 {
                     /* Get next sample. */
                     s = inBuf.get (i);
                     /* Rectify (i.e. mirror a negative sample to it's positive opposite). */
                     sRect = (s < 0)  ?  -s : s;
                     /* Determine peak value. */
                     peak = (sRect > peak)  ?  sRect : peak;
                 }
                 System.out.println ("Peak value (abs): " + peak + ".");
             }
             else
             {
                 System.out.println ("Empty frame (no samples). Peak value unavailable.");
             }
         }
         else
         {
             System.out.println ("No ports registered. Peak value unavailable.");
         }
     }
static void Terminate () static private
Definition at line 80 of file TDev_Trial_JJack_process_02.java.
Referenced by TDev_Trial_JJack_process_02.TTimeout.run().
     {
         System.out.println ("-------------------------------------------------------------------------------------------------");
         System.out.println ("Terminating...");
         System.out.println ("-------------------------------------------------------------------------------------------------");
         gProcessor._Terminate ();
         System.exit (0);
     }
Member Data Documentation
int fIFrame private
Definition at line 89 of file TDev_Trial_JJack_process_02.java.
Referenced by TDev_Trial_JJack_process_02._Init(), and TDev_Trial_JJack_process_02.process().
TDev_Trial_JJack_process_02 gProcessor static private
Definition at line 63 of file TDev_Trial_JJack_process_02.java.
Referenced by TDev_Trial_JJack_process_02.main().
TTimeout gTerminator static private
Definition at line 64 of file TDev_Trial_JJack_process_02.java.
Referenced by TDev_Trial_JJack_process_02.main().
The documentation for this class was generated from the following file:
TDev_Trial_JJack_process_02.java