ppm-java: TNodeIntegrator_PPMBallistics_Stats Class Reference
TNodeIntegrator_PPMBallistics_Stats Class Reference
Runtime statistics of a TNodeIntegrator_PPMBallistics.
Public Member Functions
TNodeIntegrator_PPMBallistics_Stats (TNodeIntegrator_PPMBallistics host)
cTor.
String GetDumpStr ()
Package Functions
void SetTimeCycle (double t)
Sets the time it took between the previous cycle and the current cycle.
void SetValueDBActual (double value)
Sets the computed output value after application of the PPM ballistics.
void SetValueDBRef (double value)
Sets the input value for the current cycle.
Private Member Functions
void _RecomputeDiff ()
Recomputes the difference between input value and output value.
Private Attributes
TNodeIntegrator_PPMBallistics fHost
The hosting module.
TAtomicDouble fTimeCycle
The time it took between the previous cycle and the current cycle.
TAtomicDouble fValueDBActual
The computed output value after application of the PPM ballistics.
TAtomicDouble fValueDBRef
The input value for the current cycle.
TAtomicDouble fValueErr
Difference between input value and output value.
Detailed Description
Runtime statistics of a TNodeIntegrator_PPMBallistics.
Author
peter
Definition at line 26 of file TNodeIntegrator_PPMBallistics_Stats.java.
Constructor & Destructor Documentation
TNodeIntegrator_PPMBallistics_Stats (TNodeIntegrator_PPMBallistics host)
cTor.
Parameters
host The hosting module.
Definition at line 58 of file TNodeIntegrator_PPMBallistics_Stats.java.
References TNodeIntegrator_PPMBallistics_Stats.fHost, TNodeIntegrator_PPMBallistics_Stats.fTimeCycle, TNodeIntegrator_PPMBallistics_Stats.fValueDBActual, TNodeIntegrator_PPMBallistics_Stats.fValueDBRef, and TNodeIntegrator_PPMBallistics_Stats.fValueErr.
     {
         fHost                   = host;
         fValueDBActual          = new TAtomicDouble ();
         fValueDBRef             = new TAtomicDouble ();
         fValueErr               = new TAtomicDouble ();
         fTimeCycle              = new TAtomicDouble ();
     }
Member Function Documentation
void _RecomputeDiff () private
Recomputes the difference between input value and output value.
Definition at line 119 of file TNodeIntegrator_PPMBallistics_Stats.java.
Referenced by TNodeIntegrator_PPMBallistics_Stats.SetValueDBActual(), and TNodeIntegrator_PPMBallistics_Stats.SetValueDBRef().
     {
         double yAct;
         double yRef;
         double yDiff;
         yAct    = fValueDBActual.Get ();
         yRef    = fValueDBRef.Get ();
         yDiff   = yRef - yAct;
         fValueErr.Set (yDiff);
     }
String GetDumpStr ()
Returns
The current runtime statistics as text dump.
Implements IStats.
Definition at line 71 of file TNodeIntegrator_PPMBallistics_Stats.java.
References TNodeIntegrator_PPMBallistics_Stats.fValueDBRef, TNodeIntegrator_PPMBallistics_Stats.fValueErr, and TAtomicDouble.Get().
     {
         String ret;
         ret = "TNodeIntegrator_PPMBallistics [" + fHost.GetID ()    + "]:\n"    +
               "    dBRef    = " + fValueDBRef.Get ()                + "\n"      +
               "    dBCur    = " + fValueDBActual.Get ()             + "\n"      +
               "    dBErr    = " + fValueErr.Get ()                  + "\n"      +
               "    tCycle   = " + fTimeCycle.Get ()                 + "\n";
         return ret;
     }
void SetTimeCycle (double t) package
Sets the time it took between the previous cycle and the current cycle.
Parameters
t Time [ms].
Definition at line 89 of file TNodeIntegrator_PPMBallistics_Stats.java.
     {
         fTimeCycle.Set (t);
     }
void SetValueDBActual (double value) package
Sets the computed output value after application of the PPM ballistics.
Parameters
value Output value.
Definition at line 99 of file TNodeIntegrator_PPMBallistics_Stats.java.
References TNodeIntegrator_PPMBallistics_Stats._RecomputeDiff().
     {
         fValueDBActual.Set (value);
         _RecomputeDiff ();
     }
void SetValueDBRef (double value) package
Sets the input value for the current cycle.
Parameters
value Input value.
Definition at line 110 of file TNodeIntegrator_PPMBallistics_Stats.java.
References TNodeIntegrator_PPMBallistics_Stats._RecomputeDiff().
     {
         fValueDBRef.Set (value);
         _RecomputeDiff ();
     }
Member Data Documentation
TNodeIntegrator_PPMBallistics fHost private
The hosting module.
Definition at line 31 of file TNodeIntegrator_PPMBallistics_Stats.java.
Referenced by TNodeIntegrator_PPMBallistics_Stats.TNodeIntegrator_PPMBallistics_Stats().
TAtomicDouble fTimeCycle private
The time it took between the previous cycle and the current cycle.
Definition at line 36 of file TNodeIntegrator_PPMBallistics_Stats.java.
Referenced by TNodeIntegrator_PPMBallistics_Stats.TNodeIntegrator_PPMBallistics_Stats().
TAtomicDouble fValueDBActual private
The computed output value after application of the PPM ballistics.
Definition at line 41 of file TNodeIntegrator_PPMBallistics_Stats.java.
Referenced by TNodeIntegrator_PPMBallistics_Stats.TNodeIntegrator_PPMBallistics_Stats().
TAtomicDouble fValueDBRef private
The input value for the current cycle.
Definition at line 46 of file TNodeIntegrator_PPMBallistics_Stats.java.
Referenced by TNodeIntegrator_PPMBallistics_Stats.GetDumpStr(), and TNodeIntegrator_PPMBallistics_Stats.TNodeIntegrator_PPMBallistics_Stats().
TAtomicDouble fValueErr private
Difference between input value and output value.
Definition at line 51 of file TNodeIntegrator_PPMBallistics_Stats.java.
Referenced by TNodeIntegrator_PPMBallistics_Stats.GetDumpStr(), and TNodeIntegrator_PPMBallistics_Stats.TNodeIntegrator_PPMBallistics_Stats().
The documentation for this class was generated from the following file:
TNodeIntegrator_PPMBallistics_Stats.java