ppm-java: TGUILinearGauge_Surrogate Class Reference
TGUILinearGauge_Surrogate Class Reference
The UI controller.
Public Member Functions
void CreatePort_In (String id)
void Start ()
Starts the module.
TGUILinearGauge_Surrogate_Stats StatsGet ()
void Stop ()
Stops the module.
Public Member Functions inherited from VFrontend
VFrontend (String id, int nMaxChanIn)
final void CreatePort_Out (String id)
Public Member Functions inherited from VAudioProcessor
VAudioProcessor (String id, int nMaxChanIn, int nMaxChanOut)
cTor.
abstract void CreatePort_In (String id)
Creates an input port.
abstract void CreatePort_Out (String id)
Creates an output port.
int GetNumPortsIn ()
int GetNumPortsOut ()
VAudioPort GetPortIn (int i)
Returns the ith input port.
VAudioPort_Input GetPortIn (String key)
Returns the input port associated with key.
VAudioPort_Output GetPortOut (int i)
Returns the ith output port.
VAudioPort_Output GetPortOut (String key)
Returns the output port associated with key.
Public Member Functions inherited from VAudioObject
VAudioObject (String id)
cTor.
Public Member Functions inherited from VBrowseable
VBrowseable (String id)
cTor
String GetID ()
Static Public Member Functions
static void CreateInstance (String id)
Creates a new instance of the frontend.
Protected Member Functions
void _Register ()
Protected Member Functions inherited from VFrontend
void _OnTerminate ()
Handler for: Frontend terminated.
Protected Member Functions inherited from VAudioProcessor
void AddPortIn (VAudioPort_Input p)
Adds a new input port.
void AddPortOut (VAudioPort_Output p)
Adds a new output port.
Protected Member Functions inherited from VBrowseable
abstract void _Register ()
Registers this object with the global registry.
Package Functions
void OnSigClip_Click ()
Event handler: User clicked on the clipping indicator.
void OnTerminate ()
Notification - UI terminated.
void SetLevel (float level, int iChannel)
For the given channel, sets the signal level.
Private Member Functions
TGUILinearGauge_Surrogate (String id)
cTor.
Private Attributes
TGUILinearGauge_WndPPM fGUI
The GUI instance.
TGUILinearGauge_Surrogate_Stats fStat
The runtime statistics.
Static Private Attributes
static TGUILinearGauge_Surrogate gGUI = null
The singleton.
static final float gkLvlClip = -1.0f
Clipping level.
static final float gkLvlWarn = -4.0f
Warning level.
Detailed Description
The UI controller.
provides client centered access to the UI.
Author
Peter Hoppe
Definition at line 25 of file TGUILinearGauge_Surrogate.java.
Constructor & Destructor Documentation
TGUILinearGauge_Surrogate (String id) private
cTor.
Parameters
id Unique ID as which we register this frontend.
Definition at line 73 of file TGUILinearGauge_Surrogate.java.
References TGUILinearGauge_Surrogate.fGUI, and TGUILinearGauge_Surrogate.fStat.
Referenced by TGUILinearGauge_Surrogate.CreateInstance().
     {
         super (id, 2);
         fGUI = new TGUILinearGauge_WndPPM (this);
         fStat = new TGUILinearGauge_Surrogate_Stats (this);
         TController.StatAddProvider (this);
     }
Member Function Documentation
void _Register () protected
Definition at line 128 of file TGUILinearGauge_Surrogate.java.
     {
         TController.Register (this);
     }
static void CreateInstance (String id) static
Creates a new instance of the frontend.
Parameters
id Unique ID as which we register this frontend.
Definition at line 49 of file TGUILinearGauge_Surrogate.java.
References TGUILinearGauge_Surrogate.gGUI, and TGUILinearGauge_Surrogate.TGUILinearGauge_Surrogate().
     {
         if (gGUI != null)
         {
             throw new IllegalStateException ("TGUILinearGauge_Surrogate is already instantiated.");
         }
         gGUI = new TGUILinearGauge_Surrogate (id);
     }
void CreatePort_In (String id)
Definition at line 86 of file TGUILinearGauge_Surrogate.java.
References VAudioProcessor.AddPortIn().
     {
         TGUILinearGauge_Endpoint_In       p;
         p = new TGUILinearGauge_Endpoint_In (id, this);
         fStat.AddChannel ();
         AddPortIn (p);
     }
void OnSigClip_Click () package
Event handler: User clicked on the clipping indicator.
This clears both clipping indicators.
Definition at line 137 of file TGUILinearGauge_Surrogate.java.
References EGUILinearGauge_ClipType.kClear.
     {
         fGUI.ClippingSet (EGUILinearGauge_ClipType.kClear, -1);
     }
void OnTerminate () package
Notification - UI terminated.
Definition at line 145 of file TGUILinearGauge_Surrogate.java.
References VBrowseable.GetID().
     {
         TController.OnTerminate (GetID ());
     }
void SetLevel (float level, int iChannel) package
For the given channel, sets the signal level.
Parameters
level The level, in dB.
iChannel Zero based index of the channel.
Definition at line 156 of file TGUILinearGauge_Surrogate.java.
References TGUILinearGauge_Surrogate.gkLvlClip, TGUILinearGauge_Surrogate.gkLvlWarn, EGUILinearGauge_ClipType.kError, and EGUILinearGauge_ClipType.kWarn.
     {
         float   lDisp;
         /* We update stats cycle time when channel #0 is being updated. */
         if (iChannel == 0)
             fStat.OnCycleTick ();
         /* Set clipping indicators. */
         if (level >= gkLvlClip)
         {
             fGUI.ClippingSet (EGUILinearGauge_ClipType.kError, iChannel);
         }
         else if (level >= gkLvlWarn)
         {
             fGUI.ClippingSet (EGUILinearGauge_ClipType.kWarn, iChannel);
         }
         /* Compute progress bar value */
         if (level > 0)
         {   /* ]0, ...] dB => hard limit to maximum */
             fStat.SetCalcSection (iChannel, 3);
             lDisp = 7.0f;
         }
         else if (level >= -24)
         {   /* [-24, 0] dB => working range 1..7 */                     /* [100] */
             fStat.SetCalcSection (iChannel, 2);
             lDisp = (level + 24) / 4 + 1;
         }
         else if (level >= -130)
         {
             /* [-130, -24[ dB => range 0..1 */                          /* [110] */
             fStat.SetCalcSection (iChannel, 1);
             lDisp = (level + 130) / 130;
         }
         else
         {
             /* below -130dB => hard limit to zero */
             fStat.SetCalcSection (iChannel, 0);
             lDisp = 0;
         }
         fStat.SetDBValue        (iChannel, level);
         fStat.SetDisplayValue   (iChannel, lDisp);
         fGUI.SetLevel           (lDisp, iChannel);
     }
void Start ()
Starts the module.
Implements IControllable.
Definition at line 99 of file TGUILinearGauge_Surrogate.java.
     {
         fGUI.setVisible (true);
         fGUI.setLocationRelativeTo (null);
     }
TGUILinearGauge_Surrogate_Stats StatsGet ()
Returns
The current runtime statistics.
Implements IStatEnabled.
Definition at line 110 of file TGUILinearGauge_Surrogate.java.
References TGUILinearGauge_Surrogate.fStat.
     {
         return fStat;
     }
void Stop ()
Stops the module.
Implements IControllable.
Definition at line 119 of file TGUILinearGauge_Surrogate.java.
     {
         fGUI.Terminate ();
     }
Member Data Documentation
TGUILinearGauge_WndPPM fGUI private
The GUI instance.
Definition at line 61 of file TGUILinearGauge_Surrogate.java.
Referenced by TGUILinearGauge_Surrogate.TGUILinearGauge_Surrogate().
TGUILinearGauge_Surrogate_Stats fStat private
The runtime statistics.
Definition at line 66 of file TGUILinearGauge_Surrogate.java.
Referenced by TGUILinearGauge_Surrogate.StatsGet(), and TGUILinearGauge_Surrogate.TGUILinearGauge_Surrogate().
TGUILinearGauge_Surrogate gGUI = null static private
The singleton.
Definition at line 32 of file TGUILinearGauge_Surrogate.java.
Referenced by TGUILinearGauge_Surrogate.CreateInstance().
final float gkLvlClip = -1.0f static private
Clipping level.
Definition at line 37 of file TGUILinearGauge_Surrogate.java.
Referenced by TGUILinearGauge_Surrogate.SetLevel().
final float gkLvlWarn = -4.0f static private
Warning level.
Definition at line 42 of file TGUILinearGauge_Surrogate.java.
Referenced by TGUILinearGauge_Surrogate.SetLevel().
The documentation for this class was generated from the following file:
TGUILinearGauge_Surrogate.java