ppm-java: TAtomicBuffer Class Reference
TAtomicBuffer Class Reference
An atomic-access wrapper around a FloatBuffer.
Public Member Functions
TAtomicBuffer ()
Creates a new atomic buffer with default policies:
TAtomicBuffer (EAtomicBuffer_CopyPolicy copyPolicy)
Creates a new atomic buffer with a custom EAtomicBuffer_CopyPolicy and default EAtomicBuffer_IfInvalidPolicy#kReturnEmpty.
TAtomicBuffer (EAtomicBuffer_CopyPolicy copyPolicy, EAtomicBuffer_IfInvalidPolicy ifInvalidPolicy)
Creates a new atomic buffer with a custom EAtomicBuffer_CopyPolicy and default EAtomicBuffer_IfInvalidPolicy#kReturnEmpty.
FloatBuffer Get ()
Returns the newest sample data.
boolean IsLocked ()
Returns true if the critical section is locked.
void Set (FloatBuffer fb)
Sets the new sample chunk.
void StatsClear ()
Clears the associated runtime statistics.
TAtomicBuffer_Stats StatsGet ()
Private Member Functions
FloatBuffer _DataGet (boolean doCopy)
An internal work method: Retrieves (a deep copy of) the newest sample chunk, or empty chunk, resp.
void _DataSet (FloatBuffer fb, boolean doCopy)
Store (a copy of the) new sample chunk, whether the consumer collected or not.
FloatBuffer _GetDeepCopy (FloatBuffer fb)
Creates a deep copy of the passed float buffer (for copy-on-write semantics).
void _Init (EAtomicBuffer_CopyPolicy copyPolicy, EAtomicBuffer_IfInvalidPolicy ifInvalidPolicy)
Common initialization method - used by the various cTors.
void _Lock ()
Definitely acquire the lock on the critical section (spin lock, as it's merry-go-round until lock has been acquired).
boolean _TryLock ()
Tentatively try to lock the critical section.
void _Unlock ()
Definitely unlock the critical section (spin lock, as it's merry-go-round until lock has been released).
Private Attributes
FloatBuffer fBuffer
The underlying data container.
EAtomicBuffer_CopyPolicy fCopyPolicy
The EAtomicBuffer_CopyPolicy.
AtomicInteger fFlag
The lock.
boolean fHasBeenCollected
Flag indicating whether the data in fBuffer has been collected.
EAtomicBuffer_IfInvalidPolicy fIfInvalidPolicy
The EAtomicBuffer_IfInvalidPolicy.
TAtomicBuffer_Stats fStats
The runtime statistics.
Static Private Attributes
static final int gkLocked = 1
Flag value: A thread acquired the lock.
static final int gkUnlocked = 0
Flag value: Buffer can be accessed.
Detailed Description
An atomic-access wrapper around a FloatBuffer.
Designed for situations where we need to transport data between a high priority thread and a low priority thread in a producer-consumer scenario. Example scenario: A thread operating audio hardware sends audio sample data to another thread updating the GUI. The audio hardware thread cannot afford to be blocked, hence has high priority. The GUI thread isn't time critical, and we can afford to have it loose some data.
The TAtomicBuffer guarantees that data can be passed from (to) a high priority thread within a fixed (short) time without blocking it. This comes at a cost - the associated low priority thread does not have the guarantee that all data actually reaches it - in highly contended situations the TAtomicBuffer would simply drop data where the low priority thread cannot keep up. If the low priority thread can't keep up with the streaming data it can't make full use of the stream anyway, so this seemed to be the best solution for data in contention situations.
The TAtomicBuffer copies the incoming data frames before they are passed on to the consumer. This is to protect the producer. If we pass on uncopied data frames and the consumer side does changes to the data then those changes would be seen on the producer side as well and cause unforeseen side effects and hard to track down errors. The extra protection comes with a performance penalty as the copying costs time. To protect the time critical thread from the performance loss we can set the time point at which the data is copied. If the producer is the time critical we copy when the consumer fetches. If the consumer is time critical we copy when the producer sets it. In some situations the data copy may be unnecessary in which case we can instruct the atomic buffer to omit any data copying. However, due to the real possibility of data corruption the data must then be copied separately, either on the producer or on the consumer side. The copy actions can be set at construction time via the copyPolicy parameter.
To monitor the quality of the data flow we offer various counters which can be queried by all parties (all clearable}:
Overrun counter: Increments each time the producer pushes a new packet whilst an old packet still awaits collection by the consumer. A steady increase of the overruns indicates that the consumer can't keep up with the producer and looses packets.
Underrun counter: Increments each time the consumer requests a packet whilst none has been pushed since the last collection. A steady increase of underruns indicates that the producer can't keep up with the consumer.
Contention counter: Increments each time the producer and the consumer are both trying to acquire access to the buffer at the same time. A steady increase of the contentions indicates that both, producer and consumer, are too aggressive trying to set and get data.
Clients can use the underrun and overrun counters for automatic dropout compensation. For example, a low priority consumer thread can, with each cycle:
read overrun and underrun counts
compute the difference: d = nOver - nUnder. If d is zero: All is well. If it's negative: Underruns. If it's positive: Overruns.
then compensate by adjusting the time to the next cycle:
d == 0: No adjustment.
d < 0: Underruns! Decrease read frequency => Increase cycle time by a fixed number of milliseconds.
d > 0: Overruns! Increase read frequency => Decrease cycle time by a fixed number of milliseconds.
If the contention counter has a steep rise then both, the producer and consumer are too aggressively trying to set and read data. As a mitigation strategy the party with the lower priority must be forced to yield whilst the higher priority party has the critical section. You can use the IsLocked() method for that:
while (myBuffer.IsLocked())
{
    try
    {
        Thread.sleep (2);
    } catch (ThatInterruptedExceptionISeeNoUseFor e){}
}
This is not a pretty solution, but it works - best use sparingly, if you have to.
Don't assume the counters are precise. Overall access to the counters isn't thread safe (it seemed overkill to implement that, too). Whilst each counter is using an atomic integer (and should be thread safe by itself), we still can have scenarios such as one thread incrementing the underrun counter whilst another thread reads the overrun counter. Due to lack of overall counter thread safety the counters can only serve as guideline to assess the various reasons for dropped data. Them counters aren't brilliant, but good enough for simple diagnosis.
Clients can customize what's returned to the consumer thread when no valid data is available upon call to Get(). Default is to return an empty sample chunk (in effect saying - zero samples available). But it means that for every invalid Get() call we create a new empty FloatBuffer which doesn't really feel that good. Therefore there's also the possibility to have Get() return null which allows consumers to operate in a similar fashion as it's done with AtomicInteger#compareAndSet(int, int):
// At some place:
TAtomicBuffer myBuf = new TAtomicBuffer (ECopyPolicy.kCopyOnGet, EIfInvalidPolicy.kReturnNull)
// Inside consumer thread
do
{
    chunk = myBuf.Get ();
    try {
    Thread.sleep (yieldTime); // Can be a few mSec so the processor doesn't grind to a halt.
    } catch (ThatInterruptedExceptionISeeNoUseFor e){}
} while (chunk == null);
// Now do nifty stuff with the sample chunk.
For synchronization between producer and consumer the TAtomicBuffer makes use of an AtomicInteger flag; more specifically, the AtomicInteger#compareAndSet(int, int) method. This method is guaranteed to be atomic, i.e. allow access to the enclosed integer only by a single thread at a time without blocking the other threads. We don't use the standard synchronized mutex as that one does block threads which haven't acquired it. This can block the time critical thread, leading to priority inversion (where the low priority thread blocks the high priority one). Additionally, on some platforms the synchronized primitive is quite costly, i.e. time consuming. The AtomicInteger#compareAndSet(int, int) is much faster.
Author
Peter Hoppe
Definition at line 171 of file TAtomicBuffer.java.
Constructor & Destructor Documentation
TAtomicBuffer ()
Creates a new atomic buffer with default policies:
EAtomicBuffer_CopyPolicy#kCopyOnSet
EAtomicBuffer_IfInvalidPolicy#kReturnEmpty
Definition at line 221 of file TAtomicBuffer.java.
References TAtomicBuffer._Init(), EAtomicBuffer_CopyPolicy.kCopyOnSet, and EAtomicBuffer_IfInvalidPolicy.kReturnEmpty.
     {
         _Init (EAtomicBuffer_CopyPolicy.kCopyOnSet, EAtomicBuffer_IfInvalidPolicy.kReturnEmpty);
     }
TAtomicBuffer (EAtomicBuffer_CopyPolicy copyPolicy)
Creates a new atomic buffer with a custom EAtomicBuffer_CopyPolicy and default EAtomicBuffer_IfInvalidPolicy#kReturnEmpty.
Parameters
copyPolicy The desired copy policy. Determines which thread is treated as high priority thread, and which one as low priority thread.
Definition at line 234 of file TAtomicBuffer.java.
References TAtomicBuffer._Init(), and EAtomicBuffer_IfInvalidPolicy.kReturnEmpty.
     {
         _Init (copyPolicy, EAtomicBuffer_IfInvalidPolicy.kReturnEmpty);
     }
TAtomicBuffer (EAtomicBuffer_CopyPolicy copyPolicy, EAtomicBuffer_IfInvalidPolicy ifInvalidPolicy)
Creates a new atomic buffer with a custom EAtomicBuffer_CopyPolicy and default EAtomicBuffer_IfInvalidPolicy#kReturnEmpty.
Parameters
copyPolicy The desired copy policy. Determines which thread is treated as high priority thread, and which one as low priority thread.
ifInvalidPolicy The desired invalid data policy. Determines what is returned to the consumer thread when there's no valid data.
Definition at line 250 of file TAtomicBuffer.java.
References TAtomicBuffer._Init().
     {
         _Init (copyPolicy, ifInvalidPolicy);
     }
Member Function Documentation
FloatBuffer _DataGet (boolean doCopy) private
An internal work method: Retrieves (a deep copy of) the newest sample chunk, or empty chunk, resp.
null if there's stale data. If there was just stale data we will increment the underrun counter.
Parameters
doCopy Return a deep copy, not the original FloatBuffer object.
Returns
The (deep copy of the) latest sample chunk.
Definition at line 436 of file TAtomicBuffer.java.
References TAtomicBuffer._GetDeepCopy(), TAtomicBuffer.fBuffer, TAtomicBuffer.fHasBeenCollected, TAtomicBuffer.fIfInvalidPolicy, and EAtomicBuffer_IfInvalidPolicy.kReturnEmpty.
Referenced by TAtomicBuffer.Get().
     {
         FloatBuffer ret;
         /*
          * Note, it's mandatory to NEVER do: fBuffer=FloatBuffer.allocate (0)!
          * Otherwise, if doCopy == false, we will set ret=fBuffer,
          * then fBuffer=FloatBuffer.allocate(0) which is in effect
          * ret=FloatBuffer.allocate (0) since ret==fBuffer! Thus the consumer
          * will receive an empty data set even though there was valid data!
          * However we neither want to pass on stale data to the consumer.
          * Our compromise is: When data is stale, we create an empty data
          * set or null and pass that back to the consumer.
          */
         if (! fHasBeenCollected)
         {   /* Ah! Some fresh data is ready to collect! */
             if (doCopy)
             {   /* The consumer thread is low priority. */
                 ret = _GetDeepCopy (fBuffer);                           /* [100] */
             }
             else
             {   /* The consumer is high priority - can't afford to copy. */
                 ret = fBuffer;
             }
         }
         else
         {   /* Ouch! We are sitting on stale data! Increment underrun
                counter and return empty chunk or null. */
             fStats.IncrementUnderruns ();
             if (fIfInvalidPolicy == EAtomicBuffer_IfInvalidPolicy.kReturnEmpty)
             {
                 ret = FloatBuffer.allocate (0);
             }
             else
             {
                 ret = null;
             }
         }
         /* Mark data as stale. For simplicity we ignore whatever fHasBeenCollected was before */
         fHasBeenCollected = true;
         return ret;
     }
void _DataSet (FloatBuffer fb, boolean doCopy) private
Store (a copy of the) new sample chunk, whether the consumer collected or not.
If there was stale data (i.e. uncollected since last _DataSet(..) we will increment the overrun counter.
Parameters
fb The sample chunk to be stored.
doCopy If true, store a deep copy instead of the original.
Definition at line 490 of file TAtomicBuffer.java.
References TAtomicBuffer._GetDeepCopy(), TAtomicBuffer.fBuffer, and TAtomicBuffer.fHasBeenCollected.
Referenced by TAtomicBuffer.Set().
     {
         if (doCopy)
         {   /* The producer thread is low priority. */
             fBuffer = _GetDeepCopy (fb);
         }
         else
         {   /* The producer is high priority - can't afford to copy. */
             fBuffer = fb;
         }
         if (! fHasBeenCollected)
         {   /* Ouch! We were sitting on stale data which means the consumer
                wasn't able to collect in time. Increment the overrun counter */
             fStats.IncrementOverruns ();
         }
         /* Mark data as fresh. For simplicity we ignore whatever fHasBeenCollected was before */
         fHasBeenCollected = false;
     }
FloatBuffer _GetDeepCopy (FloatBuffer fb) private
Creates a deep copy of the passed float buffer (for copy-on-write semantics).
Parameters
fb The FloatBuffer to be copied.
Returns
The deep copy. Essentially, this is a new (separate) object.
Definition at line 517 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._DataGet(), and TAtomicBuffer._DataSet().
     {
         int         i;
         int         nNums;
         float       v;
         FloatBuffer ret;
         nNums   = fb.capacity ();
         ret     = FloatBuffer.allocate (nNums);
         if (nNums >= 1)
         {
             for (i = 0; i < nNums; i++)
             {
                 v = fb.get (i);
                 ret.put (v);
             }
         }
         return ret;
     }
void _Init (EAtomicBuffer_CopyPolicy copyPolicy, EAtomicBuffer_IfInvalidPolicy ifInvalidPolicy) private
Common initialization method - used by the various cTors.
Parameters
copyPolicy The copy policy.
ifInvalidPolicy The "what do I return if no good data" policy.
Definition at line 544 of file TAtomicBuffer.java.
References TAtomicBuffer.fBuffer, TAtomicBuffer.fCopyPolicy, TAtomicBuffer.fFlag, TAtomicBuffer.fHasBeenCollected, TAtomicBuffer.fIfInvalidPolicy, TAtomicBuffer.fStats, and TAtomicBuffer.gkUnlocked.
Referenced by TAtomicBuffer.TAtomicBuffer().
     {
         fStats              = new TAtomicBuffer_Stats ();
         fFlag               = new AtomicInteger (gkUnlocked);
         fBuffer             = FloatBuffer.allocate (0);
         fCopyPolicy         = copyPolicy;
         fIfInvalidPolicy    = ifInvalidPolicy;
         fHasBeenCollected   = true;
     }
void _Lock () private
Definitely acquire the lock on the critical section (spin lock, as it's merry-go-round until lock has been acquired).
Definition at line 558 of file TAtomicBuffer.java.
References TAtomicBuffer.gkLocked, and TAtomicBuffer.gkUnlocked.
Referenced by TAtomicBuffer.Get(), and TAtomicBuffer.Set().
     {
         boolean isLocked;
         do
         {
             isLocked = fFlag.compareAndSet (gkUnlocked, gkLocked);
         } while (! isLocked);                                           /* [120] */
     }
boolean _TryLock () private
Tentatively try to lock the critical section.
Returns
true if lock acquired, false if acquiring failed.
Definition at line 573 of file TAtomicBuffer.java.
References TAtomicBuffer.gkLocked, and TAtomicBuffer.gkUnlocked.
Referenced by TAtomicBuffer.Get(), and TAtomicBuffer.Set().
     {
         boolean ret;
         ret = fFlag.compareAndSet (gkUnlocked, gkLocked);
         return ret;
     }
void _Unlock () private
Definitely unlock the critical section (spin lock, as it's merry-go-round until lock has been released).
Definition at line 586 of file TAtomicBuffer.java.
References TAtomicBuffer.gkLocked, and TAtomicBuffer.gkUnlocked.
Referenced by TAtomicBuffer.Get(), and TAtomicBuffer.Set().
     {
         boolean isUnlocked;
         do
         {
             isUnlocked = fFlag.compareAndSet (gkLocked, gkUnlocked);
         }
         while (! isUnlocked);                                           /* [120] */
     }
FloatBuffer Get ()
Returns the newest sample data.
Meant for the consumer thread. Note that at some stage there's a deep copying; therefore we will never return the original FloatBuffer object.
If there was no new sample data (i.e. stale data = that particular chunk has already been collected before) or if there was contention with the producer thread then we'll return either an empty sample chunk or null. See introduction for further information.
Returns
The newest sample data, or empty chunk, resp. null.
Definition at line 268 of file TAtomicBuffer.java.
References TAtomicBuffer._DataGet(), TAtomicBuffer._Lock(), TAtomicBuffer._TryLock(), TAtomicBuffer._Unlock(), TAtomicBuffer.fCopyPolicy, TAtomicBuffer.fIfInvalidPolicy, EAtomicBuffer_CopyPolicy.kCopyOnGet, EAtomicBuffer_CopyPolicy.kCopyOnSet, and EAtomicBuffer_IfInvalidPolicy.kReturnEmpty.
     {
         boolean         isLocked;
         FloatBuffer     ret;
         if (fCopyPolicy == EAtomicBuffer_CopyPolicy.kCopyOnGet)
         {   /* Consumer has low priority, i.e. can wait until the lock is free. */
             _Lock ();
             ret = _DataGet (true);
             _Unlock ();
         }
         else if (fCopyPolicy == EAtomicBuffer_CopyPolicy.kCopyOnSet)
         {   /* Consumer has high priority, i.e. will give up trying if it can't acquire the lock */
             isLocked = _TryLock ();                                     /* [110] */
             if (isLocked)
             {
                 ret = _DataGet (false);
                 _Unlock ();
             }
             else
             {   /* Consumer clashed with producer. Increment
                    contention counter and return empty chunk
                    or null. */
                 fStats.IncrementContentions ();
                 if (fIfInvalidPolicy == EAtomicBuffer_IfInvalidPolicy.kReturnEmpty)
                 {
                     ret = FloatBuffer.allocate (0);
                 }
                 else
                 {
                     ret = null;
                 }
             }
         }
         else
         {
             /* No copying. This is dangerous, but sometimes necessary.
              * Clients must make sure the producer or the consumer do
              * their own data copying. Since we can't tell who's
              * high and who's low priority we treat this case as if both,
              * producer and consumer are high priority. */
             isLocked = _TryLock ();
             if (isLocked)
             {
                 ret = _DataGet (false);
                 _Unlock ();
             }
             else
             {   /* Consumer clashed with producer. Increment
                 contention counter and return empty chunk
                 or null. */
                 fStats.IncrementContentions ();
                 if (fIfInvalidPolicy == EAtomicBuffer_IfInvalidPolicy.kReturnEmpty)
                 {
                     ret = FloatBuffer.allocate (0);
                 }
                 else
                 {
                     ret = null;
                 }
             }
         }
         return ret;
     }
boolean IsLocked ()
Returns true if the critical section is locked.
It's not thread-safe because by the time the result is returned the blocking thread may already have (un)locked the critical section. However, it's good enough to be used for automatic resolution of high contention situations. See the introduction for an automated strategy to reduce contentions.
Returns
true if the critical section is locked right now.
Definition at line 345 of file TAtomicBuffer.java.
References TAtomicBuffer.gkUnlocked.
     {
         int     flag;
         boolean ret;
         flag = fFlag.getAndAdd (0);
         ret  = (flag == gkUnlocked);
         return ret;
     }
void Set (FloatBuffer fb)
Sets the new sample chunk.
If there is stale data it will be overwritten. Meant for the producer thread.
Parameters
fb Sample chunk to set.
Definition at line 362 of file TAtomicBuffer.java.
References TAtomicBuffer._DataSet(), TAtomicBuffer._Lock(), TAtomicBuffer._TryLock(), TAtomicBuffer._Unlock(), TAtomicBuffer.fCopyPolicy, EAtomicBuffer_CopyPolicy.kCopyOnGet, and EAtomicBuffer_CopyPolicy.kCopyOnSet.
     {
         boolean isLocked;
         if (fCopyPolicy == EAtomicBuffer_CopyPolicy.kCopyOnSet)
         {   /* Producer has low priority, i.e. can wait until the lock is free. */
             _Lock ();                                                   /* [120] */
             _DataSet (fb, true);
             _Unlock ();
         }
         else if (fCopyPolicy == EAtomicBuffer_CopyPolicy.kCopyOnGet)
         {   /* Producer has high priority, i.e. will give up trying if it can't acquire the lock */
             isLocked = _TryLock ();                                     /* [110] */
             if (isLocked)
             {
                 _DataSet (fb, false);
                 _Unlock ();
             }
             else
             {
                 fStats.IncrementContentions ();                         /* [130] */
             }
         }
         else
         {   /* No copying. This is dangerous, but sometimes necessary.
              * Clients must make sure the producer or the consumer do
              * their own data copying. Since we can't tell who's
              * high and who's low priority we treat this case as if both,
              * producer and consumer are high priority. */
             isLocked = _TryLock ();
             if (isLocked)
             {
                 _DataSet (fb, false);
                 _Unlock ();
             }
             else
             {
                 fStats.IncrementContentions ();
             }
         }
     }
void StatsClear ()
Clears the associated runtime statistics.
Not thread safe, but good enough to use for automatic compensation of problems.
See Also
TAtomicBuffer_Stats
Definition at line 411 of file TAtomicBuffer.java.
     {
         fStats.Clear ();
     }
TAtomicBuffer_Stats StatsGet ()
Returns
The associated runtime statistics. Not thread safe, but good enough to use for automatic compensation of problems.
See Also
TAtomicBuffer_Stats
Implements IStatEnabled.
Definition at line 423 of file TAtomicBuffer.java.
References TAtomicBuffer.fStats.
     {
         return fStats;
     }
Member Data Documentation
FloatBuffer fBuffer private
The underlying data container.
Definition at line 186 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._DataGet(), TAtomicBuffer._DataSet(), and TAtomicBuffer._Init().
EAtomicBuffer_CopyPolicy fCopyPolicy private
The EAtomicBuffer_CopyPolicy.
Definition at line 191 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._Init(), TAtomicBuffer.Get(), and TAtomicBuffer.Set().
AtomicInteger fFlag private
The lock.
Definition at line 196 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._Init().
boolean fHasBeenCollected private
Flag indicating whether the data in fBuffer has been collected.
To detect stale data (underrun/overrun detection)
Definition at line 202 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._DataGet(), TAtomicBuffer._DataSet(), and TAtomicBuffer._Init().
EAtomicBuffer_IfInvalidPolicy fIfInvalidPolicy private
The EAtomicBuffer_IfInvalidPolicy.
Definition at line 207 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._DataGet(), TAtomicBuffer._Init(), and TAtomicBuffer.Get().
TAtomicBuffer_Stats fStats private
The runtime statistics.
Definition at line 212 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._Init(), and TAtomicBuffer.StatsGet().
final int gkLocked = 1 static private
Flag value: A thread acquired the lock.
Definition at line 176 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._Lock(), TAtomicBuffer._TryLock(), and TAtomicBuffer._Unlock().
final int gkUnlocked = 0 static private
Flag value: Buffer can be accessed.
Definition at line 181 of file TAtomicBuffer.java.
Referenced by TAtomicBuffer._Init(), TAtomicBuffer._Lock(), TAtomicBuffer._TryLock(), TAtomicBuffer._Unlock(), and TAtomicBuffer.IsLocked().
The documentation for this class was generated from the following file:
TAtomicBuffer.java